#!/usr/bin/env bash
# Build NedoOS kernel symbols (user.l, main.sld, syscode.c) from a NedoOS checkout,
# on macOS / Linux, without IAR (FatFS exports come from fatfs4os/fatfs.exp).
#
#   generate-symbols.sh <nedoos-checkout> <flavor> <out-dir>
#   flavor: evo (sd_boot.$C, Wiznet) | evo-esp (sd_bootesp.$C, ESPNET)
#
# The sources are copied to a temporary folder; the checkout is not touched.
set -euo pipefail

NEDOOS=${1:?NedoOS checkout}
FLAVOR=${2:?flavor: evo or evo-esp}
OUT=${3:?output folder}
mkdir -p "$OUT"; OUT=$(cd "$OUT" && pwd)
JOBS=$(( $(sysctl -n hw.ncpu 2>/dev/null || nproc) / 2 )); JOBS=$(( JOBS < 1 ? 1 : JOBS ))

WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

case "$FLAVOR" in
  evo)     INETDRV=0x01 ;;
  evo-esp) INETDRV=0x02 ;;
  *) echo "unknown flavor $FLAVOR" >&2; exit 1 ;;
esac

# 1. sjasmplus from the copy shipped with NedoOS (the version the kernel is built with)
cp -R "$NEDOOS/tools/src/sjasmplus" "$WORK/sjasmplus"
make -C "$WORK/sjasmplus" -j "$JOBS" USE_LUA=0 >"$WORK/sjasmplus.log" 2>&1
SJ="$WORK/sjasmplus/sjasmplus"

# 2. kernel sources and the flags build_kernel_evo*.bat writes
mkdir -p "$WORK/src" "$WORK/us"
cp -R "$NEDOOS/src/kernel" "$NEDOOS/src/_sdk" "$NEDOOS/src/fatfs4os" "$WORK/src/"
cat >"$WORK/src/_sdk/syssets.asm" <<EOF
atm=1
atm2clock=0
sys_npages=192
NEMOIDE=1
SYSDRV=12
INETDRV=$INETDRV
PS2KBD=0x01
 define NGSSD
 define ATMRESIDENT
EOF

# 3. FatFS entry points: normally generated by the IAR build, here from fatfs.exp
{
  echo ';FatFS calls'
  echo 'ffsfunc'
  awk 'NF==2 { print "." $1 " EQU 0x" $2 }' "$WORK/src/fatfs4os/fatfs.exp"
} >"$WORK/src/kernel/ffsfunc.asm"

# 4. assemble (same order as build.bat), with source-level debug output for page roles
cd "$WORK/src/kernel"
"$SJ" --nologo --msg=war ngsinst.asm
"$SJ" --nologo --msg=war --sld=main.sld main.asm

mkdir -p "$OUT"
cp "$WORK/us/user.l" main.sld syscode.c initcode.c "$OUT/"
git -C "$NEDOOS" rev-parse --short HEAD >"$OUT/nedoos-revision.txt" 2>/dev/null || true
cp "$WORK/src/_sdk/syssets.asm" "$OUT/"
echo "symbols for $FLAVOR in $OUT ($(wc -l <"$OUT/user.l") labels)"
