# 06: eve-emu with switchable antialiasing models (EVE_AA_MODEL), run on the BT8XX goldens.
eve_variant(aa256 OVERLAY_DIR ${CMAKE_CURRENT_LIST_DIR}/overlay EXTRA ${EVE_COMMON}/eve-poc-stub.cpp)
find_package(ZLIB REQUIRED)
add_executable(golden-run ${CMAKE_CURRENT_LIST_DIR}/golden-run.cpp)
target_link_libraries(golden-run PRIVATE eve-lib-aa256 ZLIB::ZLIB)
if(APPLE AND EXISTS ${CMAKE_CURRENT_LIST_DIR}/metal-aa.mm)
    add_executable(metal-aa ${CMAKE_CURRENT_LIST_DIR}/metal-aa.mm)
    target_include_directories(metal-aa PRIVATE ${EVE_COMMON})
    target_link_libraries(metal-aa PRIVATE eve-lib-base)
    set_source_files_properties(${CMAKE_CURRENT_LIST_DIR}/metal-aa.mm PROPERTIES COMPILE_OPTIONS "-ffp-contract=off")
    target_compile_options(metal-aa PRIVATE -fobjc-arc)
    target_compile_definitions(metal-aa PRIVATE EVE_METAL_AA_SOURCE="${CMAKE_CURRENT_LIST_DIR}/eve-aa.metal")
    target_link_libraries(metal-aa PRIVATE "-framework Metal" "-framework Foundation")
endif()
