"""Hand names and comments for NextZXOS ROM 2 (the +3DOS / IDEDOS / NextZXOS API page).

API names: NextZXOS_and_esxDOS_APIs (updated 2023-05-24); each name sits on the `JP` of the call address.
The SD card driver was named from its SPI conversation (docs/inprogress/2026-10-07-zx-next/esxdos-and-sd.md section 4.2).
"""

LISTING = 'nextzx/next-rom2.asm'
SYMFILE = 'next-rom2.map'
TITLE = 'NextZXOS ROM 2 (+3DOS / IDEDOS / NextZXOS API), shown at #0000'

HEADER = [
    ";" + "=" * 75,
    "; ZX Spectrum Next - NextZXOS ROM 2: the +3DOS-compatible API, IDEDOS, NextZXOS calls",
    "; Image: machines/next/enNextZX.rom, bytes #8000-#BFFF (16K ROM number 2), shown at #0000",
    "; Call addresses #0056-#01D8 are JP entries (the API document lists them as ROM 2 addresses).",
    "; The SD card driver (SPI conversation, CMD0 ... CMD24) is at #18D6-#1A82.",
    ";" + "=" * 75,
]

API = {
    0x0056: ('IDE_STREAM_OPEN', 'Open stream to a channel'),
    0x0059: ('IDE_STREAM_CLOSE', 'Close stream and attached channel'),
    0x005C: ('IDE_STREAM_IN', 'Get byte from current stream'),
    0x005F: ('IDE_STREAM_OUT', 'Write byte to current stream'),
    0x0062: ('IDE_STREAM_PTR', 'Get or set pointer information for current stream'),
    0x00A0: ('IDE_VERSION', 'Get IDEDOS version number'),
    0x00A3: ('IDE_INTERFACE', 'Initialise card interfaces'),
    0x00A6: ('IDE_INIT', 'Initialise IDEDOS'),
    0x00A9: ('IDE_DRIVE', 'Get unit handle'),
    0x00AC: ('IDE_SECTOR_READ', 'Low-level sector read'),
    0x00AF: ('IDE_SECTOR_WRITE', 'Low-level sector write'),
    0x00B2: ('IDE_FORMAT', 'Format a partition'),
    0x00B5: ('IDE_PARTITION_FIND', 'Find named partition'),
    0x00B8: ('IDE_PARTITION_NEW', 'Create partition'),
    0x00BB: ('IDE_PARTITION_INIT', 'Initialise partition'),
    0x00BE: ('IDE_PARTITION_ERASE', 'Delete a partition'),
    0x00C1: ('IDE_PARTITION_RENAME', 'Rename a partition'),
    0x00C4: ('IDE_PARTITON_READ', 'Read a partition entry'),
    0x00C7: ('IDE_PARTITION_WRITE', 'Write a partition entry'),
    0x00CA: ('IDE_PARTITION_WINFO', 'Write type-specific partition information'),
    0x00CD: ('IDE_PARTITION_OPEN', 'Open a partition'),
    0x00D0: ('IDE_PARTITION_CLOSE', 'Close a partition'),
    0x00D3: ('IDE_PARTITION_GETINFO', 'Get byte from type-specific partition information'),
    0x00D6: ('IDE_PARTITION_SETINFO', 'Set byte in type-specific partition information'),
    0x00D9: ('IDE_SWAP_OPEN', ''),
    0x00DC: ('IDE_SWAP_CLOSE', 'Close a swap partition'),
    0x00DF: ('IDE_SWAP_OUT', 'Write block to swap partition'),
    0x00E2: ('IDE_SWAP_IN', 'Read block from swap partition'),
    0x00E5: ('IDE_SWAP_EX', ''),
    0x00E8: ('IDE_SWAP_POS', 'Get current block number in swap partition'),
    0x00EB: ('IDE_SWAP_MOVE', 'Set current block number in swap partition'),
    0x00EE: ('IDE_SWAP_RESIZE', 'Change block size of swap partition'),
    0x00F1: ('IDE_DOS_MAP', ''),
    0x00F4: ('IDE_DOS_UNMAP', ''),
    0x00F7: ('IDE_DOS_MAPPING', ''),
    0x00FA: ('IDE_DOS_UNPERMANENT', 'Remove permanent drive mapping'),
    0x00FD: ('IDE_SNAPLOAD', ''),
    0x0100: ('DOS_INITIALISE', 'Initialise +3DOS'),
    0x0103: ('DOS_VERSION', 'Get +3DOS issue and version numbers'),
    0x0106: ('DOS_OPEN', 'Create and/or open a file'),
    0x0109: ('DOS_CLOSE', 'Close a file'),
    0x010C: ('DOS_ABANDON', 'Abandon a file'),
    0x010F: ('DOS_REF_HEAD', 'Point at the header data for this file'),
    0x0112: ('DOS_READ', 'Read bytes into memory'),
    0x0115: ('DOS_WRITE', 'Write bytes from memory'),
    0x0118: ('DOS_BYTE_READ', 'Read a byte'),
    0x011B: ('DOS_BYTE_WRITE', 'Write a byte'),
    0x011E: ('DOS_CATALOG', 'Catalog disk directory'),
    0x0121: ('DOS_FREE_SPACE', 'Free space on disk'),
    0x0124: ('DOS_DELETE', 'Delete a file'),
    0x0127: ('DOS_RENAME', 'Rename a file'),
    0x012A: ('DOS_BOOT', 'Boot an operating system or other program'),
    0x012D: ('DOS_SET_DRIVE', 'Set/get default drive'),
    0x0130: ('DOS_SET_USER', 'Set/get default user number'),
    0x0133: ('DOS_GET_POSITION', 'Get file pointer for random access'),
    0x0136: ('DOS_SET_POSITION', 'Set file pointer for random access'),
    0x0139: ('DOS_GET_EOF', 'Get end of file position for random access'),
    0x013C: ('DOS_GET_1346', 'Get memory usage in pages 1, 3, 4, 6'),
    0x013F: ('DOS_SET_1346', 'Re-allocate memory usage in pages 1, 3, 4, 6'),
    0x0142: ('DOS_FLUSH', 'Bring disk up to date'),
    0x0145: ('DOS_SET_ACCESS', "Change open file's access mode"),
    0x0148: ('DOS_SET_ATTRIBUTES', "Change a file's attributes"),
    0x014B: ('DOS_OPEN_DRIVE', 'Open a drive as a single file'),
    0x014E: ('DOS_SET_MESSAGE', 'Enable/disable error messages'),
    0x0151: ('DOS_REF_XDPB', 'Point at XDPB for low level disk access'),
    0x0154: ('DOS_MAP_B', 'Map B: onto unit 0 or 1'),
    0x0157: ('DD_INTERFACE', 'Is the floppy disk driver interface present?'),
    0x015A: ('DD_INIT', 'Initialise disk driver'),
    0x015D: ('DD_SETUP', 'Specify drive parameters'),
    0x0160: ('DD_SET_RETRY', 'Set try/retry count'),
    0x0163: ('DD_READ_SECTOR', 'Read a sector'),
    0x0166: ('DD_WRITE_SECTOR', 'Write a sector'),
    0x0169: ('DD_CHECK_SECTOR', 'Check a sector'),
    0x016C: ('DD_FORMAT', 'Format a track'),
    0x016F: ('DD_READ_ID', 'Read a sector identifier'),
    0x0172: ('DD_TEST_UNSUITABLE', 'Test media suitability'),
    0x0175: ('DD_LOGIN', 'Log in disk, initialise XDPB'),
    0x0178: ('DD_SEL_FORMAT', 'Pre-initialise XDPB for DD FORMAT'),
    0x017B: ('DD_ASK_1', 'Is unit 1 (external drive) present?'),
    0x017E: ('DD_DRIVE_STATUS', 'Fetch drive status'),
    0x0181: ('DD_EQUIPMENT', 'What type of drive?'),
    0x0184: ('DD_ENCODE', 'Set intercept routine for copy protection'),
    0x0187: ('DD_L_XDPB', 'Initialise an XDPB from a disk specification'),
    0x018A: ('DD_L_DPB', 'Initialise a DPB from a disk specification'),
    0x018D: ('DD_L_SEEK', 'uPD765A seek driver'),
    0x0190: ('DD_L_READ', 'uPD765A read driver'),
    0x0193: ('DD_L_WRITE', 'uPD765A write driver'),
    0x0196: ('DD_L_ON_MOTOR', 'Motor on, wait for motor-on time'),
    0x0199: ('DD_L_T_OFF_MOTOR', 'Start the motor-off ticker'),
    0x019C: ('DD_L_OFF_MOTOR', 'Turn the motor off'),
    0x01A2: ('IDE_IDENTIFY', 'Return IDE drive identity information'),
    0x01A5: ('IDE_PARTITIONS', 'Get number of open partitions'),
    0x01B1: ('IDE_PATH', ''),
    0x01B4: ('IDE_CAPACITY', ''),
    0x01B7: ('IDE_GET_LFN', ''),
    0x01BA: ('IDE_BROWSER', ''),
    0x01BD: ('IDE_BANK', ''),
    0x01C0: ('IDE_BASIC', ''),
    0x01C3: ('IDE_WINDOW_LINEIN', ''),
    0x01C6: ('IDE_WINDOW_STRING', ''),
    0x01C9: ('IDE_INTEGER_VAR', ''),
    0x01CC: ('IDE_RTC', ''),
    0x01CF: ('IDE_DRIVER', ''),
    0x01D2: ('IDE_MOUNT', ''),
    0x01D5: ('IDE_MODE', ''),
    0x01D8: ('IDE_TOKENISER', ''),
}

NAMES = {a: n for a, (n, c) in API.items()}
COMMENTS = {a: c for a, (n, c) in API.items()}

# SD card driver, ROM 2 offsets (same code, other addresses: nxtmmc.asm #1F0F-#1FDD)
NAMES.update({
    0x1897: 'SectorToCardAddress',
    0x18D6: 'SdCommandZeroArg',
    0x18D8: 'SdCommandZeroHL',
    0x18DC: 'SdCommandCrcFF',
    0x18DE: 'SdCommand',
    0x1904: 'SdReadRegister',
    0x1925: 'SdWaitNotFF',
    0x1933: 'SdWaitDataToken',
    0x1944: 'SdReadBlock',
    0x1961: 'SdDeselect',
    0x196D: 'SdStopTransmission',
    0x197A: 'SdWriteBlock',
    0x19C7: 'SdReadCsdLoop',
    0x19DD: 'SdCardInit',
    0x1A68: 'SdReadOcr',
    0x1A82: 'SdCheckCardType',
})
COMMENTS.update({
    0x1897: 'IX = card descriptor (+1..+4 base sector, +7..+10 size, +16 flags: bit 1 = block addressed).\n'
            'DE:BC = sector in the partition; returns the card address in HL:DE (shifted to bytes for SDSC).',
    0x18D6: 'Send a command (A = #40 | n) with argument 0 and CRC #FF.',
    0x18DC: 'A = command, HL:DE = argument, B = #FF: CRC byte. Selects card 0 (OUT #E7,#FE) or card 1 (#FD)\n'
            'by Z, sends the six bytes with OUT (C),A / LD A,x spacing (16 CPU clocks per byte), then waits\n'
            'for a response byte that is not #FF (up to #32 * 256 reads). Carry = response received, A = R1.',
    0x18DE: 'As SdCommand with B = CRC.',
    0x1904: 'CMD9 (SEND_CSD): wait for data token #FE, read 18 bytes (16 + CRC).',
    0x1925: 'Poll IN (#EB) until a byte other than #FF (or about #32 * 256 tries).',
    0x1933: 'Wait for the data token #FE (up to 10 polls).',
    0x1944: 'CMD17 (READ_SINGLE_BLOCK): token wait, two INIR of 256 bytes into (IX), two CRC bytes, deselect.',
    0x1961: 'Common exit: deselect (OUT #E7,#FF) and two dummy reads; preserves AF.',
    0x196D: 'CMD12 (STOP_TRANSMISSION) and wait for the busy byte to clear.',
    0x197A: 'CMD24 (WRITE_BLOCK): token #FE, two OTIR of 256 bytes from (IX), two CRC bytes #FF #FF,\n'
            'data response must be xxx00101, then busy wait and CMD13 (SEND_STATUS, #4D): R2 must be zero.',
    0x19DD: 'Card initialization: CMD12, CMD0 (CRC #95), CMD8 (arg #1AA, CRC #87), CMD55 + ACMD41 loop (HCS set\n'
            'when CMD8 answered), CMD58 (OCR, CCS bit decides SDHC), CMD16 (#200) for SDSC.',
    0x1A68: 'CMD58 (READ_OCR): A = OCR byte 0 AND #C0 compared with #C0 (power-up done + CCS).',
})
