<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Compile Include="$(ZxSrc)/ZXMAK2.Host.Presentation/**/*.cs" />
    <ProjectReference Include="ZXMAK2.Dependency.csproj" />
    <ProjectReference Include="ZXMAK2.Engine.Cpu.csproj" />
    <ProjectReference Include="ZXMAK2.Engine.csproj" />
    <ProjectReference Include="ZXMAK2.Host.csproj" />
    <ProjectReference Include="ZXMAK2.Logging.csproj" />
    <ProjectReference Include="ZXMAK2.Mvvm.csproj" />
  </ItemGroup>
</Project>
