#pragma once

/// @file nextregtable.h
/// @brief The NextREG space as data: number, name, access and whole-byte reset value of every register of the
/// distribution's registers.txt ("The Next Registers" v2.4), generated by tools/machines/next/fpga-extract/gen-nextreg-table.py.
/// The board takes its reset values from it and the `next_regs` report prints it.

#include <cstddef>
#include <cstdint>

struct NextRegInfo
{
    uint8_t number;
    const char* name;
    bool readable;
    bool writable;
    bool hasReset;  ///< the text gives one reset value for the whole byte (per-bit resets stay with the device)
    uint8_t reset;
};

const NextRegInfo* NextRegTable(size_t& count);
const NextRegInfo* FindNextReg(uint8_t number);
