"""BIOS function numbers (RST #08 / RST #18, number in register C).

Names from Tolik-Trek Shared_Includes constants/BIOS_equ.inc (dd760c8), the
naming the current community BIOS uses; BIOS 3.04 implements a subset (the
listings mark functions whose table entry is the "not implemented" stub).
"""

NAMES = {
    0x40: 'HDD_INIT',
    0x41: 'HDD_RECAL',
    0x42: 'HDD_TEST_IDE',
    0x43: 'HDD_PREPARE',
    0x44: 'HDD_READ_BPB',
    0x45: 'HDD_READ',
    0x46: 'HDD_WRITE',
    0x47: 'HDD_PART',
    0x48: 'HDD_READ_NEXT',
    0x50: 'DRV_GET_NAME',
    0x51: 'DRV_RESET',
    0x52: 'DRV_READ_LONG',
    0x53: 'DRV_WRITE_LONG',
    0x54: 'DRV_VERIFY',
    0x55: 'DRV_READ',
    0x56: 'DRV_WRITE',
    0x57: 'DRV_DETECT',
    0x58: 'DRV_GET_PAR',
    0x59: 'DRV_SET_PAR',
    0x5A: 'DRV_VERSION',
    0x5E: 'DRV_EXTENDED',
    0x5F: 'DRV_LIST',
    0x80: 'LP_OPEN_S',
    0x81: 'LP_PRINT_ALL',
    0x82: 'LP_PRINT_SYM',
    0x83: 'LP_PRINT_ATR',
    0x84: 'LP_SET_PLACE',
    0x85: 'LP_PRINT_LINE',
    0x86: 'LP_PRINT_LINE2',
    0x87: 'LP_PRINT_LINE3',
    0x88: 'LP_PRINT_LINE4',
    0x89: 'LP_CLS_WIN',
    0x8A: 'LP_SCROLL_UD',
    0x8B: 'LP_PRINT_LINE5',
    0x8C: 'LP_PRINT_LINE6',
    0x8D: 'LP_CLS_WIN2',
    0x8E: 'LP_GET_PLACE',
    0x8F: 'FN_TURBO',
    0x92: 'GetMemRMD',
    0x93: 'FreeMemRMD',
    0x94: 'GetMemPageRMD',
    0x97: 'CheckInit',
    0x98: 'RAMD_CALC_PAGE',
    0x99: 'SET_DISK_REDIR',
    0x9A: 'GET_DISK_REDIR',
    0x9B: 'GET_RAMD_NUM',
    0x9C: 'SWAP_RAM_DRIVES',
    0x9D: 'DivMemBlocks',
    0x9E: 'MergeMemBlocks',
    0x9F: 'FullInit',
    0xA1: 'PIC_POINT',
    0xA4: 'PIC_SET_PAL',  # also PIC_GET_PAL
    0xA6: 'SET_PAL_INIT',
    0xB0: 'WIN_OPEN',
    0xB1: 'WIN_CLOSE',
    0xB2: 'WIN_COPY',
    0xB3: 'WIN_RESTORE',
    0xB4: 'WIN_GET_SYM',
    0xB5: 'WIN_PUT_SYM',
    0xB6: 'WIN_SET_ZG',
    0xB7: 'WIN_MOVE',
    0xB8: 'WIN_GET_ZG',
    0xC0: 'GetMemSize',
    0xC1: 'InitMem',
    0xC2: 'GetMem',
    0xC3: 'FreeMem',
    0xC4: 'GetMemPage',
    0xC5: 'GetMemBlkPages',
    0xC6: 'GetBanksPorts',
    0xC7: 'GetMemPageNext',
    0xC8: 'BLK_RD_WR',
    0xC9: 'BLK_TO_RAMD',
    0xCA: 'RAMD_CLEAR',
    0xCB: 'RAMD_TO_DRV',
    0xCC: 'FDD_TO_DRV',
    0xCD: 'HDD_TO_DRV',
    0xCE: 'GET_RAMD_ST',
    0xCF: 'GET_DRV_ST',
    0xE0: 'LP_PR_LINE_DIR',
    0xED: 'FN_CRIPT',
    0xEF: 'FN_VERSION',
    0xF2: 'FN_SYNC',
    0xF4: 'DCP_CONFIG',
    0xF5: 'CMOS_TEST',
    0xF6: 'CMOS_RD',
    0xF7: 'CMOS_WR',
    0xF8: 'SET_PORTS',
    0xF9: 'READ_PORTS',
    0xFB: 'GOTO_SPECTRUM',
    0xFC: 'ZX_MEMORY_MANAGER',
    0xFD: 'REINIT',
}
