#include <gtest/gtest.h>
#include <cmath>
#include <complex>
#include <vector>
#include "emulator/emulatorcontext.h"
#include "emulator/cpu/core.h"
#include "emulator/sound/soundmanager.h"
#include "emulator/sound/beeper.h"
#include "emulator/sound/audio.h"

class BeeperTest : public ::testing::Test
{
protected:
    EmulatorContext* ctx = nullptr;
    SoundManager* sm = nullptr;

    void SetUp() override
    {
        ctx = new EmulatorContext(LoggerLevel::LogError);
        ctx->config.frame = 71680;  // Standard Pentagon/ZX128 frame duration in T-states
        ctx->emulatorState.current_z80_frequency_multiplier = 1;
        sm = new SoundManager(ctx);
        sm->reset();

        sm->getBeeperChain().setPunchEnabled(false);
        sm->getBeeperChain().setRoomMode(AudioCharacterChain::RoomMode::Off);
    }

    void TearDown() override
    {
        delete sm;
        delete ctx;
    }
};

TEST_F(BeeperTest, BeeperRegisteredInDeviceRegistry)
{
    auto* beeperDev = sm->device(AudioSourceType::Beeper);
    ASSERT_NE(beeperDev, nullptr);
    EXPECT_EQ(beeperDev->name, "Beeper");
}

TEST_F(BeeperTest, PortOutGeneratesBandLimitedOutput)
{
    Beeper& beeper = sm->getBeeper();

    sm->handleFrameStart();
    // Simulate port #FE write with EAR=1 (bit 4) at T=1000
    beeper.handlePortOut(0b0001'0000, 1000);
    sm->handleFrameEnd();

    const int16_t* buffer = sm->deviceBuffer(AudioSourceType::Beeper);
    ASSERT_NE(buffer, nullptr);

    // After step delta, samples after T=1000 should show high amplitude (~7500)
    int nonZeroCount = 0;
    for (size_t i = 0; i < SAMPLES_PER_FRAME * 2; i++)
    {
        if (std::abs(buffer[i]) > 1000)
            nonZeroCount++;
    }
    EXPECT_GT(nonZeroCount, 100);
}

TEST_F(BeeperTest, TapeAudioFeedsIntoBlipBuf)
{
    Beeper& beeper = sm->getBeeper();

    sm->handleFrameStart();
    // Feed tape audio sample amplitude 5000 at T=500
    beeper.handleTapeAudio(5000, 500);
    sm->handleFrameEnd();

    const int16_t* buffer = sm->deviceBuffer(AudioSourceType::Beeper);
    ASSERT_NE(buffer, nullptr);

    // Verify non-zero output generated by blip_buf
    bool foundAudio = false;
    for (size_t i = 0; i < SAMPLES_PER_FRAME * 2; i++)
    {
        if (std::abs(buffer[i]) > 1000)
        {
            foundAudio = true;
            break;
        }
    }
    EXPECT_TRUE(foundAudio);
}

TEST_F(BeeperTest, MultiplePortOutTransitionsStayBandLimited)
{
    Beeper& beeper = sm->getBeeper();

    sm->handleFrameStart();
    // High-frequency square wave (toggle EAR bit every 100 T-states)
    for (uint32_t t = 0; t < 70000; t += 100)
    {
        uint8_t earBit = ((t / 100) % 2 == 0) ? 0b0001'0000 : 0b0000'0000;
        beeper.handlePortOut(earBit, t);
    }
    sm->handleFrameEnd();

    const int16_t* buffer = sm->deviceBuffer(AudioSourceType::Beeper);
    ASSERT_NE(buffer, nullptr);

    // Verify no sample exceeds valid int16 range and signal is clean
    for (size_t i = 0; i < SAMPLES_PER_FRAME * 2; i++)
    {
        EXPECT_GE(buffer[i], -32768);
        EXPECT_LE(buffer[i], 32767);
    }
}

namespace {

void runRadix2FFT(std::vector<std::complex<double>>& x)
{
    const size_t N = x.size();
    if (N <= 1) return;

    for (size_t i = 1, j = 0; i < N; i++)
    {
        size_t bit = N >> 1;
        for (; j & bit; bit >>= 1)
            j ^= bit;
        j ^= bit;
        if (i < j)
            std::swap(x[i], x[j]);
    }

    for (size_t len = 2; len <= N; len <<= 1)
    {
        double ang = -2.0 * M_PI / len;
        std::complex<double> wlen(std::cos(ang), std::sin(ang));
        for (size_t i = 0; i < N; i += len)
        {
            std::complex<double> w(1.0, 0.0);
            for (size_t j = 0; j < len / 2; j++)
            {
                std::complex<double> u = x[i + j];
                std::complex<double> v = x[i + j + len / 2] * w;
                x[i + j] = u + v;
                x[i + j + len / 2] = u - v;
                w *= wlen;
            }
        }
    }
}

} // namespace

TEST_F(BeeperTest, TapePilotSpectralPurity)
{
    Beeper& beeper = sm->getBeeper();

    // Standard ZX Spectrum Tape Pilot tone: 2168 T-states half-period (807.195 Hz fundamental)
    constexpr uint32_t halfPeriodTStates = 2168;
    constexpr uint32_t frameLengthTStates = 71680;

    std::vector<double> pcmBuffer;
    pcmBuffer.reserve(25 * SAMPLES_PER_FRAME);

    uint64_t nextToggleTState = 0;
    uint8_t earBit = 0b0001'0000;

    // Synthesize 25 frames (~0.5 sec @ 50 Hz frame rate)
    for (int frame = 0; frame < 25; frame++)
    {
        sm->handleFrameStart();

        uint64_t frameStartT = static_cast<uint64_t>(frame) * frameLengthTStates;
        uint64_t frameEndT = static_cast<uint64_t>(frame + 1) * frameLengthTStates;

        while (nextToggleTState < frameEndT)
        {
            uint32_t relativeTState = static_cast<uint32_t>(nextToggleTState - frameStartT);
            beeper.handlePortOut(earBit, relativeTState);
            earBit ^= 0b0001'0000;  // Toggle EAR
            nextToggleTState += halfPeriodTStates;
        }

        sm->handleFrameEnd();

        const int16_t* devBuf = sm->deviceBuffer(AudioSourceType::Beeper);
        ASSERT_NE(devBuf, nullptr);

        size_t samplesThisFrame = static_cast<size_t>(std::round(frameLengthTStates * 44100.0 / 3500000.0));
        for (size_t i = 0; i < samplesThisFrame; i++)
        {
            pcmBuffer.push_back(static_cast<double>(devBuf[i * 2]));
        }
    }

    // FFT size N = 16384 (power of 2)
    constexpr size_t N = 16384;
    ASSERT_GE(pcmBuffer.size(), N);

    std::vector<std::complex<double>> fftBuf(N);
    // Apply Hann window to eliminate spectral leakage
    for (size_t i = 0; i < N; i++)
    {
        double hann = 0.5 * (1.0 - std::cos(2.0 * M_PI * i / (N - 1)));
        fftBuf[i] = std::complex<double>(pcmBuffer[i] * hann, 0.0);
    }

    runRadix2FFT(fftBuf);

    double sampleRate = 44100.0;
    double binHz = sampleRate / N;  // ~2.69 Hz per bin

    // Find fundamental peak near 807 Hz (bin ~300)
    size_t targetBin = static_cast<size_t>(std::round(807.195 / binHz));
    size_t fundBin = targetBin;
    double fundMag = 0.0;

    for (size_t b = targetBin - 10; b <= targetBin + 10; b++)
    {
        double mag = std::abs(fftBuf[b]);
        if (mag > fundMag)
        {
            fundMag = mag;
            fundBin = b;
        }
    }

    double fundHz = fundBin * binHz;
    EXPECT_NEAR(fundHz, 807.2, 5.0);
    ASSERT_GT(fundMag, 1e5);  // Strong fundamental signal

    // 1. Check sub-harmonic energy (< 700 Hz)
    double maxSubHarmonicMag = 0.0;
    for (size_t b = 5; b < static_cast<size_t>(700.0 / binHz); b++)
    {
        double mag = std::abs(fftBuf[b]);
        if (mag > maxSubHarmonicMag)
            maxSubHarmonicMag = mag;
    }
    double subHarmonicDb = 20.0 * std::log10(maxSubHarmonicMag / fundMag);
    EXPECT_LT(subHarmonicDb, -35.0);  // Sub-harmonic energy must be <-35 dB

    // 2. Check for parasitic / aliasing non-harmonic spurs up to Nyquist (20 kHz)
    double maxParasiticMag = 0.0;

    for (size_t b = 10; b < N / 2; b++)
    {
        double hz = b * binHz;
        if (hz > 20000.0) break;

        // Skip legitimate odd harmonics (1f, 3f, 5f, 7f... within ±15 Hz window)
        bool isOddHarmonic = false;
        for (int k = 1; k <= 25; k += 2)
        {
            double harmHz = k * fundHz;
            if (std::abs(hz - harmHz) < 15.0)
            {
                isOddHarmonic = true;
                break;
            }
        }

        if (!isOddHarmonic)
        {
            double mag = std::abs(fftBuf[b]);
            if (mag > maxParasiticMag)
            {
                maxParasiticMag = mag;
            }
        }
    }

    double parasiticDb = 20.0 * std::log10(maxParasiticMag / fundMag);
    EXPECT_LT(parasiticDb, -30.0);  // Parasitic spurs must be <-30 dB relative to fundamental
}

TEST_F(BeeperTest, DemarcheAcrossTheEdgeTapeOutAudioNoParasiticRumble)
{
    Beeper& beeper = sm->getBeeper();
    constexpr uint32_t frameLengthTStates = 71680;
    constexpr uint32_t togglePeriodTStates = 2202;  // Demarche Across the Edge Phase 2 period

    std::vector<int16_t> phrasePcm;
    std::vector<int16_t> silencePcm;

    uint64_t nextToggleTState = 0;
    uint8_t portVal = 0b0000'0000;

    // Phase 1: Play 10 frames of 1-bit MIC sound (Across the Edge Phase 2)
    for (int frame = 0; frame < 10; frame++)
    {
        sm->handleFrameStart();
        uint64_t frameStartT = static_cast<uint64_t>(frame) * frameLengthTStates;
        uint64_t frameEndT = static_cast<uint64_t>(frame + 1) * frameLengthTStates;

        while (nextToggleTState < frameEndT)
        {
            uint32_t relativeTState = static_cast<uint32_t>(nextToggleTState - frameStartT);
            portVal ^= 0b0000'1000;  // Toggle MIC (bit 3)
            beeper.handlePortOut(portVal, relativeTState);
            nextToggleTState += togglePeriodTStates;
        }

        sm->handleFrameEnd();

        const int16_t* devBuf = sm->deviceBuffer(AudioSourceType::Beeper);
        ASSERT_NE(devBuf, nullptr);

        for (size_t i = 0; i < SAMPLES_PER_FRAME; i++)
            phrasePcm.push_back(devBuf[i * 2]);
    }

    // Phase 2: Play 10 frames of SILENCE after sound phrase ends (no MIC toggles)
    for (int frame = 10; frame < 20; frame++)
    {
        sm->handleFrameStart();
        // No port writes during silent frames
        sm->handleFrameEnd();

        const int16_t* devBuf = sm->deviceBuffer(AudioSourceType::Beeper);
        ASSERT_NE(devBuf, nullptr);

        for (size_t i = 0; i < SAMPLES_PER_FRAME; i++)
            silencePcm.push_back(devBuf[i * 2]);
    }

    // Verify sound phrase produced strong audio signal
    int activeCount = 0;
    for (int16_t s : phrasePcm)
    {
        if (std::abs(s) > 1000)
            activeCount++;
    }
    EXPECT_GT(activeCount, 1000);

    // Verify silent frames decay to near 0 (no lingering DC offset > 1000)
    int lingeringDcCount = 0;
    for (size_t i = silencePcm.size() / 2; i < silencePcm.size(); i++)
    {
        if (std::abs(silencePcm[i]) > 1000)
            lingeringDcCount++;
    }
    EXPECT_EQ(lingeringDcCount, 0) << "Lingering DC bias detected during silent frames after demo sound phrase!";
}

TEST_F(BeeperTest, MicToggleHasNonZeroDeltaRegardlessOfEarState)
{
    Beeper& beeper = sm->getBeeper();

    // 1. EAR = 0: Toggle MIC (0b0000'0000 -> 0b0000'1000)
    //    Hardware DAC delta = 1600 (0.73V - 0.39V = 0.34V)
    beeper.reset();
    sm->handleFrameStart();
    beeper.handlePortOut(0b0000'0000, 100);
    beeper.handlePortOut(0b0000'1000, 500);
    sm->handleFrameEnd();

    const int16_t* bufEar0 = sm->deviceBuffer(AudioSourceType::Beeper);
    int maxEar0 = 0;
    for (size_t i = 0; i < SAMPLES_PER_FRAME * 2; i++)
        maxEar0 = std::max(maxEar0, (int)std::abs(bufEar0[i]));

    EXPECT_GT(maxEar0, 500) << "MIC toggle when EAR=0 must generate audible audio!";

    // 2. EAR = 1: Toggle MIC (0b0001'0000 -> 0b0001'1000)
    //    Hardware DAC delta = 600 (3.79V - 3.66V = 0.13V)
    beeper.reset();
    sm->handleFrameStart();
    beeper.handlePortOut(0b0001'0000, 100);
    beeper.handlePortOut(0b0001'1000, 500);
    sm->handleFrameEnd();

    const int16_t* bufEar1 = sm->deviceBuffer(AudioSourceType::Beeper);
    int maxEar1 = 0;
    for (size_t i = 0; i < SAMPLES_PER_FRAME * 2; i++)
        maxEar1 = std::max(maxEar1, (int)std::abs(bufEar1[i]));

    EXPECT_GT(maxEar1, 100) << "MIC toggle when EAR=1 must generate audible audio! (Must not mute to zero delta)";
}
