graph TD
    D[From Page 9 Logic] --> CHECK_V_FLAG{IS<br/>V = 1?};
    CHECK_V_FLAG -- No --> INT_RESET_BUSY[INTRO RESET BUSY];
    CHECK_V_FLAG -- Yes --> SET_HLD[SET HLD];
    SET_HLD --> CHECK_15MS{HAS<br/>15 MS*<br/>EXPIRED?};
    CHECK_15MS -- No --> CHECK_15MS;
    CHECK_15MS -- Yes --> CHECK_HLT{IS<br/>HLT = 1?};
    CHECK_HLT -- No --> CHECK_HLT;
    CHECK_HLT -- Yes --> CHECK_5_INDEX{HAVE<br/>5 INDEX<br/>HOLES<br/>PASSED?};
    CHECK_5_INDEX -- Yes --> INT_RESET_SEEK_ERR[INTRQ, RESET BUSY<br/>SET SEEK ERROR];
    CHECK_5_INDEX -- No --> CHECK_IDAM{HAS<br/>ID AM BEEN<br/>DETECTED?};
    CHECK_IDAM -- No --> CHECK_5_INDEX;
    CHECK_IDAM -- Yes --> CHECK_CRC_ERR{IS<br/>THERE A<br/>CRC ERROR?};
    CHECK_CRC_ERR -- Yes --> SET_CRC_ERR[SET<br/>CRC<br/>ERROR];
    CHECK_CRC_ERR -- No --> RESET_CRC[RESET<br/>CRC];
    SET_CRC_ERR --> CHECK_TR_MATCH{DOES<br/>TR = TRACK<br/>ADDRESS OF ID<br/>FIELD?};
    RESET_CRC --> CHECK_TR_MATCH;
    CHECK_TR_MATCH -- No --> CHECK_5_INDEX;
    CHECK_TR_MATCH -- Yes --> INT_RESET_BUSY_OK[INTRO<br/>RESET BUSY];

    subgraph Notes
        NOTE1[NOTE: IF TEST = 0, THERE IS NO 15MS DELAY];
        NOTE2[IF TEST = 1 AND CLK = 1 MHz, THERE IS A 30MS DELAY];
    end