graph TD
    DR_TO_DSR[DR TO DSR] --> CHECK_TR_EQ_DSR{DOES<br/>TR = DSR?};
    CHECK_TR_EQ_DSR -- Yes --> D;

    CHECK_TR_EQ_DSR -- No --> CHECK_DSR_GT_TR{IS<br/>DSR > TR?};
    CHECK_DSR_GT_TR -- No --> RESET_DIR[RESET DIRECTION];
    CHECK_DSR_GT_TR -- Yes --> SET_DIR[SET DIRECTION];

    RESET_DIR --> CHECK_DIR_0{IS<br/>DIRECTION = 0?};
    SET_DIR --> CHECK_DIR_0;

    CHECK_DIR_0 -- No --> INC_TR[+1 TO TR];
    CHECK_DIR_0 -- Yes --> CHECK_AT_TRACK_0{IS HEAD AT<br/>TRACK 0 AND<br/>DIRECTION = 0?};
    CHECK_AT_TRACK_0 -- Yes --> ZERO_TO_TR[0 TO TR] --> D;
    CHECK_AT_TRACK_0 -- No --> DEC_TR[-1 TO TR];

    INC_TR --> ISSUE_STEP[ISSUE<br/>ONE STEP PULSE];
    DEC_TR --> ISSUE_STEP;
    ISSUE_STEP --> DELAY[DELAY ACCORDING<br/>TO R1, R0 FIELD];
    DELAY --> CHECK_CMD_STEP_TYPE{IS COMMAND<br/>A STEP, STEP-IN,<br/>OR STEP-OUT?};
    CHECK_CMD_STEP_TYPE -- Yes --> D;
    CHECK_CMD_STEP_TYPE -- No --> DR_TO_DSR;
