flowchart TD
    READ_LOGIC_2[2] --> CHECK_DATA_AM{HAS<br/>DATA AM<br/>OCCURED<br/>IN TIME?};
    CHECK_DATA_AM -- No --> INT_REC_NOT_FOUND[INTRO, RESET BUSY<br/>SET RECORD-NOT FOUND];
    CHECK_DATA_AM -- Yes --> SET_REC_TYPE[PUT RECORD TYPE IN<br/>STATUS REG BIT 5];
    SET_REC_TYPE --> CHECK_FIRST_BYTE{HAS<br/>FIRST BYTE<br/>BEEN ASSEMBLED<br/>IN DSR?};
    CHECK_FIRST_BYTE -- No --> CHECK_FIRST_BYTE;
    CHECK_FIRST_BYTE -- Yes --> SET_DRQ[SET DRQ];
    SET_DRQ --> CHECK_NEXT_BYTE{HAS<br/>NEXT BYTE<br/>BEEN ASSEMBLED<br/>IN DSR?};
    CHECK_NEXT_BYTE -- No --> CHECK_NEXT_BYTE
    CHECK_NEXT_BYTE -- Yes --> CHECK_DR_READ{HAS<br/>DR BEEN<br/>READ BY<br/>COMPUTER<br/> DRQ == 0?};
    CHECK_DR_READ -- No --> SET_DATA_LOST[SET DATA<br/>LOST];
    CHECK_DR_READ -- Yes --> CHECK_ALL_BYTES_IN{HAVE<br/>ALL BYTES<br/>BEEN INPUTTED?};
    SET_DATA_LOST --> CHECK_ALL_BYTES_IN;
    CHECK_ALL_BYTES_IN -- No --> SET_DRQ;
    CHECK_ALL_BYTES_IN -- Yes --> CHECK_CRC_ERR{CRC<br/>ERROR?};
    CHECK_CRC_ERR -- Yes --> INT_CRC_ERR[INTRQ, RESET BUSY<br/>SET CRC ERROR];
    CHECK_CRC_ERR -- No --> CHECK_M_FLAG{IS<br/>M = 1?};
    CHECK_M_FLAG -- No --> INT_RESET_BUSY[INTRO RESET BUSY];
    CHECK_M_FLAG -- Yes --> INC_SECTOR_REG[+1 TO<br/>SECTOR REG] --> ID_SEARCH_1[1];