flowchart TD
    ENTER[ENTER] --> CHECK_CMD_TYPE{HAS A TYPE I<br/>COMMAND BEEN<br/>RECEIVED?};
    CHECK_CMD_TYPE -- No --> ENTER;
    CHECK_CMD_TYPE -- Yes --> SET_BUSY_ETC[SET BUSY, RESET CRC,<br/>SEEK ERROR, DRQ; INTRO];
    SET_BUSY_ETC --> CHECK_H_FLAG{IS H=1?};
    CHECK_H_FLAG -- Yes --> SET_HLD[SET HLD];
    CHECK_H_FLAG -- No --> RESET_HLD[RESET HLD];
    SET_HLD --> CHECK_STEP_IN{IS COMMAND<br/>A STEP-IN?};
    RESET_HLD --> CHECK_STEP_IN;
    CHECK_STEP_IN -- Yes --> SET_DIR_IN[SET DIRECTION] --> A;
    CHECK_STEP_IN -- No --> CHECK_STEP_OUT{IS COMMAND<br/>A STEP-OUT?};
    CHECK_STEP_OUT -- Yes --> RESET_DIR[RESET DIRECTION] --> A;
    CHECK_STEP_OUT -- No --> CHECK_STEP{IS COMMAND<br/>A STEP?};
    CHECK_STEP -- Yes --> A;
    CHECK_STEP -- No --> CHECK_SEEK{IS COMMAND<br/>A SEEK?};
    CHECK_SEEK -- No --> RESTORE[RESTORE];
    RESTORE --> FF_TO_TR[FFh TO TR];
    FF_TO_TR --> ZERO_TO_DR[0 TO DR];
    ZERO_TO_DR --> A;
    CHECK_SEEK -- Yes --> CHECK_U_FLAG{IS U=1?};
    CHECK_U_FLAG -- Yes --> SET_DIR_SEEK[SET DIRECTION] --> B;
    CHECK_U_FLAG -- No --> SET_DIR_SEEK_NO_U[SET DIRECTION] --> C;

    subgraph Seek/Step Logic
      A --> DR_TO_DSR[DR TO DSR];
      B --> DR_TO_DSR;
      C --> DR_TO_DSR;
    end