flowchart TD
    A[Connector A - Normal Write] --> DR_TO_DSR[DR TO DSR];
    DR_TO_DSR --> SET_DRQ[SET DRQ];
    SET_DRQ --> CHECK_INDEX_PULSE{PHYS<br/>INDEX MARK?};
    CHECK_INDEX_PULSE -- Yes --> INT_RESET_BUSY_DONE[INTRO RESET BUSY];
    CHECK_INDEX_PULSE -- No --> CHECK_DR_LOADED{HAS<br/>DR BEEN<br/>LOADED?};
    CHECK_DR_LOADED -- No --> WRITE_ZEROS[WRITE<br/>BYTE OF ZEROS<br/>SET DATA LOST];
    WRITE_ZEROS --> A;
    CHECK_DR_LOADED -- Yes --> B[Connector B - Check Data Pattern];

    B[Connector B - Check Data Pattern] --> CHECK_DDEN{DDEN<br/>= 0?};
    CHECK_DDEN -- No --> CHECK_DSR_F7_FM{DOES<br/>DSR = F7?};
    CHECK_DSR_F7_FM -- Yes --> WRITE_CRC_FM[WRITE 2 CRC<br/>CHARS. CLK=FF];
    CHECK_DSR_F7_FM -- No --> CHECK_DSR_FC_FM{DOES<br/>DSR = FC?};
    CHECK_DSR_FC_FM -- Yes --> WRITE_FC_FM[WRITE FC<br/>CLK = D7];
    CHECK_DSR_FC_FM -- No --> CHECK_DSR_SPECIAL_FM{DOES<br/>DSR = FD, FE,<br/>OR F8-FB?};
    CHECK_DSR_SPECIAL_FM -- Yes --> WRITE_SPECIAL_FM[WRITE FD, FE OR<br/>F8-FB. CLK = C7<br/>INITIALIZE CRC];
    CHECK_DSR_SPECIAL_FM -- No --> WRITE_DSR_FM[WRITE DSR<br/>CLK = FF];

    CHECK_DDEN -- Yes --> CHECK_DSR_F5_MFM{DOES<br/>DSR = F5?};
    CHECK_DSR_F5_MFM -- Yes --> WRITE_A1_MFM[WRITE A1 IN MFM<br/>WITH MISSING CLOCK<br/>INITIALIZE CRC];
    CHECK_DSR_F5_MFM -- No --> CHECK_DSR_F6_MFM{DOES<br/>DSR = F6?};
    CHECK_DSR_F6_MFM -- Yes --> WRITE_C2_MFM[WRITE C2 IN MFM<br/>WITH MISSING CLOCK];
    CHECK_DSR_F6_MFM -- No --> CHECK_DSR_F7_MFM{DOES<br/>DSR = F7?};
    CHECK_DSR_F7_MFM -- Yes --> WRITE_CRC_MFM[WRITE 2 CRC<br/>CHARS];
    CHECK_DSR_F7_MFM -- No --> WRITE_DSR_MFM[WRITE DSR<br/>IN MFM];

    WRITE_CRC_FM --> A;
    WRITE_FC_FM --> A;
    WRITE_SPECIAL_FM --> A;
    WRITE_DSR_FM --> A;
    WRITE_A1_MFM --> A;
    WRITE_C2_MFM --> A;
    WRITE_CRC_MFM --> A;
    WRITE_DSR_MFM --> A;