flowchart TD
    WRITE_LOGIC_3[3] --> DELAY_GAP2[DELAY 2 BYTES OF GAP];
    DELAY_GAP2 --> SET_DRQ[SET DRQ];
    SET_DRQ --> DELAY_GAP8[DELAY 8 BYTES OF GAP];
    DELAY_GAP8 --> CHECK_DR_LOADED{HAS<br/>DR BEEN<br/>LOADED BY<br/>COMPUTER<br/>DRQ = 0?};
    CHECK_DR_LOADED -- No --> INT_LOST_DATA[INTRO, RESET BUSY<br/>SET LOST DATA];
    CHECK_DR_LOADED -- Yes --> DELAY_GAP1[DELAY 1 BYTE OF GAP];
    DELAY_GAP1 --> CHECK_DDEN{DDEN<br/>= 0?};
    CHECK_DDEN -- No --> WRITE_ZEROS_FM[TURN ON WG & WRITE<br/>6 BYTES OF ZEROS];
    CHECK_DDEN -- Yes --> DELAY_11B[DELAY 11 BYTES];
    DELAY_11B --> WRITE_ZEROS_MFM[TURN ON WG & WRITE<br/>12 BYTES OF ZEROS];
    WRITE_ZEROS_FM --> WRITE_DATA_AM[WRITE DATA AM<br/>ACCORDING TO A0 FIELD<br/>OF WRITE COMMAND];
    WRITE_ZEROS_MFM --> WRITE_DATA_AM;
    WRITE_DATA_AM --> DR_TO_DSR[DR TO DSR. SET DRQ];
    DR_TO_DSR --> CHECK_DR_LOADED2{HAS<br/>DR BEEN<br/>LOADED<br/>DRQ = 0?};
    CHECK_DR_LOADED2 -- No --> SET_DATA_LOST2[SET DATA<br/>LOST];
    SET_DATA_LOST2 --> WRITE_ZERO_BYTE[WRITE BYTE<br/>OF ZEROS];
    CHECK_DR_LOADED2 -- Yes --> WRITE_BYTE[WRITE BYTE TO DISK];
    WRITE_ZERO_BYTE --> CHECK_ALL_WRITTEN{HAVE<br/>ALL BYTES<br/>BEEN WRITTEN?};
    WRITE_BYTE --> CHECK_ALL_WRITTEN;
    CHECK_ALL_WRITTEN -- No --> DR_TO_DSR;
    CHECK_ALL_WRITTEN -- Yes --> WRITE_CRC[WRITE CRC];
    WRITE_CRC --> WRITE_FF[WRITE 1 BYTE OF FF];
    WRITE_FF --> WG_OFF[TURN OFF WG];
    WG_OFF --> CHECK_M_FLAG{IS<br/>M = 1?};
    CHECK_M_FLAG -- No --> INT_RESET_BUSY[INTRO RESET BUSY];
    CHECK_M_FLAG -- Yes --> INC_SECTOR_REG[+1 TO<br/>SECTOR REG] --> ID_SEARCH_1[1];