graph TD
    ENTER[ENTER] --> CHECK_CMD_TYPE{IS<br/>TYPE II<br/>COMMAND<br/>RECEIVED?};
    CHECK_CMD_TYPE -- No --> ENTER;
    CHECK_CMD_TYPE -- Yes --> SET_BUSY_STATUS[SET BUSY, RESET DRQ, LOST<br/>DATA, RECORD NOT FOUND, &<br/>STATUS BITS 5 & 6; INTRQ];
    SET_BUSY_STATUS --> CHECK_DISK_READY{IS<br/>DISK<br/>READY?};
    CHECK_DISK_READY -- No --> INT_RESET_BUSY_INIT[INTRQ<br/>RESET BUSY];
    CHECK_DISK_READY -- Yes --> SET_HLD[SET HLD];
    SET_HLD --> CHECK_E_FLAG{IS E=1?};
    CHECK_E_FLAG -- No --> CHECK_HLT_NO_DELAY{IS HLT=1?};
    CHECK_E_FLAG -- Yes --> CHECK_15MS{HAS<br/>15 MS*<br/>EXPIRED?};
    CHECK_15MS -- No --> CHECK_15MS;
    CHECK_15MS -- Yes --> CHECK_HLT{IS HLT=1?};
    CHECK_HLT_NO_DELAY --> CHECK_TG43;
    CHECK_HLT -- No --> CHECK_HLT;
    CHECK_HLT -- Yes --> CHECK_TG43{IS<br/>TR > 43?};
    CHECK_TG43 -- No --> RESET_TG43[RESET TG43];
    CHECK_TG43 -- Yes --> SET_TG43[SET<br/>TG43];
    RESET_TG43 --> CHECK_WPRT{IS<br/>WRITE<br/>PROTECT<br/>ON?};
    SET_TG43 --> CHECK_WPRT;
    CHECK_WPRT -- Yes --> INT_RESET_WPRT[INTRO, RESET BUSY<br/>SET WRITE PROTECT];
    CHECK_WPRT -- No --> CHECK_CMD_WRITE{IS<br/>COMMAND<br/>A<br/>WRITE?};
    CHECK_CMD_WRITE -- No --> ID_SEARCH_1[1];
    CHECK_CMD_WRITE -- Yes --> ID_SEARCH_1[1];

    subgraph Note
        NOTE[*NOTE: IF TEST=0, THERE IS NO 15MS DELAY,<br/>IF TEST=1 AND CLK=1MHz, THERE IS 30MS DELAY];
    end