graph TD
    ID_SEARCH_1[1] --> CHECK_5_INDEX{HAVE<br/>5 INDEX HOLES<br/>PASSED?};
    CHECK_5_INDEX -- Yes --> INT_REC_NOT_FOUND[INTRO, RESET BUSY<br/>SET RECORD-NOT FOUND];
    CHECK_5_INDEX -- No --> CHECK_IDAM{HAS<br/>IDAM<br/>BEEN<br/>DETECTED?};
    CHECK_IDAM -- No --> CHECK_5_INDEX;
    CHECK_IDAM -- Yes --> CHECK_TR_MATCH{DOES<br/>TR = TRACK<br/>ADDRESS OF ID<br/>FIELD?};
    CHECK_TR_MATCH -- No --> CHECK_5_INDEX;
    CHECK_TR_MATCH -- Yes --> CHECK_SR_MATCH{DOES<br/>SR = SECTOR<br/>ADDRESS OF ID<br/>FIELD?};
    CHECK_SR_MATCH -- No --> CHECK_5_INDEX;
    CHECK_SR_MATCH -- Yes --> CHECK_SIDE_MATCH{DOES<br/>S = SIDE NO.<br/>OF<br/>ID FIELD?};
    CHECK_SIDE_MATCH -- No --> CHECK_5_INDEX;
    CHECK_SIDE_MATCH -- Yes --> STORE_LENGTH[BRING IN SECTOR LENGTH FIELD<br/>STORE LENGTH IN INTERNAL<br/>REGISTER];
    STORE_LENGTH --> CHECK_CRC_ERROR{IS<br/>THERE A<br/>CRC ERROR?};
    CHECK_CRC_ERROR -- Yes --> SET_CRC_STATUS[SET CRC<br/>STATUS ERROR] --> CHECK_5_INDEX;
    CHECK_CRC_ERROR -- No --> RESET_CRC[RESET<br/>CRC];
    RESET_CRC --> CHECK_CMD_WRITE{IS<br/>COMMAND<br/>A<br/>WRITE?};
    CHECK_CMD_WRITE -- No --> READ_LOGIC_2[2];
    CHECK_CMD_WRITE -- Yes --> WRITE_LOGIC_3[3];