graph TD
    ENTER[ENTER] --> CHECK_CMD_TYPE{IS<br/>THIS A<br/>WRITE TRACK?};
    CHECK_CMD_TYPE -- No --> ENTER;
    CHECK_CMD_TYPE -- Yes --> SET_BUSY_STATUS[SET BUSY, RESET DRQ,<br/>LOST DATA, STATUS<br/>BITS 4, 5];
    SET_BUSY_STATUS --> CHECK_DISK_READY{IS<br/>DISK<br/>READY?};
    CHECK_DISK_READY -- No --> INT_RESET_BUSY_INIT[INTRO<br/>RESET BUSY];
    CHECK_DISK_READY -- Yes --> SET_HLD[SET HLD];
    SET_HLD --> CHECK_15MS{HAS<br/>15 MS<br/>EXPIRED?};
    CHECK_15MS -- No --> CHECK_15MS;
    CHECK_15MS -- Yes --> CHECK_HLT{IS<br/>HLT = 1?};
    CHECK_HLT -- No --> CHECK_HLT;
    CHECK_HLT -- Yes --> TG43_UPDATE[TG43 UPDATE];
    TG43_UPDATE --> CHECK_WPRT{IS<br/>WPRT = 0?};
    CHECK_WPRT -- Yes --> INT_RESET_WPRT[INTRO, RESET<br/>BUSY. SET WPRT];
    CHECK_WPRT -- No --> SET_DRQ_INIT[SET DRQ];
    SET_DRQ_INIT --> DELAY_3BYTES[DELAY 3 BYTE<br/>TIMES];
    DELAY_3BYTES --> CHECK_DRQ_SVC{HAS<br/>DRQ BEEN<br/>SERVICED?};
    CHECK_DRQ_SVC -- No --> INT_LOST_DATA[SET INTRQ<br/>LOST DATA<br/>RESET BUSY];
    CHECK_DRQ_SVC -- Yes --> CHECK_INDEX_PULSE_INIT{HAS<br/>INDEX<br/>PULSE<br/>OCCURED?};

    CHECK_INDEX_PULSE_INIT -- No --> DR_TO_DSR;
    CHECK_INDEX_PULSE_INIT -- Yes --> CHECK_PATTERN;

    DR_TO_DSR --> SET_DRQ_LOOP[SET DRQ];
    SET_DRQ_LOOP --> CHECK_INDEX_PULSE_LOOP{PHYS<br/>INDEX MARK?};
    CHECK_INDEX_PULSE_LOOP -- Yes --> INT_RESET_BUSY_DONE[INTRO RESET BUSY];
    CHECK_INDEX_PULSE_LOOP -- No --> CHECK_DR_LOADED{HAS<br/>DR BEEN<br/>LOADED?};
    CHECK_DR_LOADED -- No --> WRITE_ZEROS[WRITE<br/>BYTE OF ZEROS<br/>SET DATA LOST];
    WRITE_ZEROS --> CHECK_INDEX_PULSE_LOOP;
    CHECK_DR_LOADED -- Yes --> CHECK_PATTERN;


    CHECK_PATTERN --> CHECK_DDEN{DDEN<br/>= 0?};

    CHECK_DDEN -- No --> CHECK_DSR_F7_FM{DOES<br/>DSR = F7?};
    CHECK_DSR_F7_FM -- Yes --> WRITE_CRC_FM[WRITE 2 CRC<br/>CHARS. CLK = FF];
    CHECK_DSR_F7_FM -- No --> CHECK_DSR_FC_FM{DOES<br/>DSR = FC?};
    CHECK_DSR_FC_FM -- Yes --> WRITE_FC_FM[WRITE FC<br/>CLK = D7];
    CHECK_DSR_FC_FM -- No --> CHECK_DSR_SPECIAL_FM{DOES<br/>DSR = FD, FE,<br/>OR F8-FB?};
    CHECK_DSR_SPECIAL_FM -- Yes --> WRITE_SPECIAL_FM[WRITE FD, FE OR<br/>F8-FB. CLK = C7<br/>INITIALIZE CRC];
    CHECK_DSR_SPECIAL_FM -- No --> WRITE_DSR_FM[WRITE DSR<br/>CLK = FF];

    CHECK_DDEN -- Yes --> CHECK_DSR_F5_MFM{DOES<br/>DSR = F5?};
    CHECK_DSR_F5_MFM -- Yes --> WRITE_A1_MFM[WRITE A1 IN MFM<br/>WITH MISSING CLOCK<br/>INITIALIZE CRC];
    CHECK_DSR_F5_MFM -- No --> CHECK_DSR_F6_MFM{DOES<br/>DSR = F6?};
    CHECK_DSR_F6_MFM -- Yes --> WRITE_C2_MFM[WRITE C2 IN MFM<br/>WITH MISSING CLOCK];
    CHECK_DSR_F6_MFM -- No --> CHECK_DSR_F7_MFM{DOES<br/>DSR = F7?};
    CHECK_DSR_F7_MFM -- Yes --> WRITE_CRC_MFM[WRITE 2 CRC<br/>CHARS];
    CHECK_DSR_F7_MFM -- No --> WRITE_DSR_MFM[WRITE DSR<br/>IN MFM];

    WRITE_CRC_FM --> CHECK_INDEX_PULSE_LOOP;
    WRITE_FC_FM --> CHECK_INDEX_PULSE_LOOP;
    WRITE_SPECIAL_FM --> CHECK_INDEX_PULSE_LOOP;
    WRITE_DSR_FM --> CHECK_INDEX_PULSE_LOOP;
    WRITE_A1_MFM --> CHECK_INDEX_PULSE_LOOP;
    WRITE_C2_MFM --> CHECK_INDEX_PULSE_LOOP;
    WRITE_CRC_MFM --> CHECK_INDEX_PULSE_LOOP;
    WRITE_DSR_MFM --> CHECK_INDEX_PULSE_LOOP;