flowchart TD
    ENTER[ENTER] --> CHECK_CMD_TYPE{HAS A TYPE I<br/>COMMAND BEEN<br/>RECEIVED?};
    CHECK_CMD_TYPE -- No --> ENTER;
    CHECK_CMD_TYPE -- Yes --> SET_BUSY_ETC[SET BUSY, RESET CRC,<br/>SEEK ERROR, DRQ; INTRO];
    SET_BUSY_ETC --> CHECK_H_FLAG{IS H=1?};
    CHECK_H_FLAG -- Yes --> SET_HLD[SET HLD];
    CHECK_H_FLAG -- No --> RESET_HLD[RESET HLD];

    SET_HLD --> CHECK_CMD_TYPE_BRANCH{Command Type?};
    RESET_HLD --> CHECK_CMD_TYPE_BRANCH;

    CHECK_CMD_TYPE_BRANCH -- Step-In --> SET_DIR_IN[SET DIRECTION] --> DR_TO_DSR;
    CHECK_CMD_TYPE_BRANCH -- Step-Out --> RESET_DIR_CMD[RESET DIRECTION] --> DR_TO_DSR;
    CHECK_CMD_TYPE_BRANCH -- Step --> DR_TO_DSR;
    CHECK_CMD_TYPE_BRANCH -- Seek --> CHECK_U_FLAG{IS U=1?};
    CHECK_CMD_TYPE_BRANCH -- Restore --> RESTORE_LOGIC[RESTORE];

    CHECK_U_FLAG -- Yes --> SET_DIR_SEEK_U1[SET DIRECTION] --> DR_TO_DSR;
    CHECK_U_FLAG -- No --> SET_DIR_SEEK_U0[SET DIRECTION] --> DR_TO_DSR;

    RESTORE_LOGIC --> FF_TO_TR[FFh TO TR];
    FF_TO_TR --> ZERO_TO_DR[0 TO DR] --> DR_TO_DSR;

    DR_TO_DSR[DR TO DSR] --> CHECK_TR_EQ_DSR{DOES<br/>TR = DSR?};

    CHECK_TR_EQ_DSR -- Yes --> D_OUT[ D ];

    CHECK_TR_EQ_DSR -- No --> CHECK_DSR_GT_TR{IS<br/>DSR > TR?};
    CHECK_DSR_GT_TR -- No --> RESET_DIR_SEEK[RESET DIRECTION];
    CHECK_DSR_GT_TR -- Yes --> SET_DIR_SEEK_EXE[SET DIRECTION];

    RESET_DIR_SEEK --> CHECK_DIR_0{IS<br/>DIRECTION = 0?};
    SET_DIR_SEEK_EXE --> CHECK_DIR_0;

    CHECK_DIR_0 -- No --> INC_TR[+1 TO TR];
    CHECK_DIR_0 -- Yes --> CHECK_AT_TRACK_0{IS HEAD AT<br/>TRACK 0 AND<br/>DIRECTION = 0?};

    CHECK_AT_TRACK_0 -- Yes --> ZERO_TO_TR[0 TO TR] --> D_OUT;

    CHECK_AT_TRACK_0 -- No --> DEC_TR[-1 TO TR];

    INC_TR --> ISSUE_STEP[ISSUE<br/>ONE STEP PULSE];
    DEC_TR --> ISSUE_STEP;
    ISSUE_STEP --> DELAY[DELAY ACCORDING<br/>TO R1, R0 FIELD];

    DELAY --> CHECK_CMD_STEP_TYPE{IS COMMAND<br/>A STEP, STEP-IN,<br/>OR STEP-OUT?};

    CHECK_CMD_STEP_TYPE -- Yes --> D_OUT;

    CHECK_CMD_STEP_TYPE -- No --> DR_TO_DSR;

    