#include "loaders/disk/loader_dsk.h"

#include <gtest/gtest.h>

#include <cstring>
#include <filesystem>
#include <numeric>
#include <vector>

#include <common/filehelper.h>
#include <common/stringhelper.h>

#include "_helpers/testpathhelper.h"
#include "emulator/cpu/core.h"
#include "emulator/emulatorcontext.h"
#include "emulator/io/fdc/diskimage.h"
#include "emulator/io/fdc/wd1793.h"

/// DSK / EDSK loader tests (docs/inprogress/2026-09-02-universal-track-model/loader-dsk.md, section 4)
/// Fixtures are generated by core/tests/emulator/io/fdc/tools/dsk_image_generator.py

using Spec = DiskImage::TrackFormatSpec;

class LoaderDSK_Test : public ::testing::Test
{
protected:
    EmulatorContext* _context = nullptr;
    CoreCUT* _core = nullptr;
    Z80* _z80 = nullptr;

    static constexpr const char* PLUS3_FIXTURE = "loaders/dsk/plus3-blank.dsk";
    static constexpr const char* EDSK_FIXTURE = "loaders/dsk/edsk-protected.dsk";

protected:
    void SetUp() override
    {
        _context = new EmulatorContext(LoggerLevel::LogError);
        _context->pModuleLogger->TurnOffLoggingForAll();

        _core = new CoreCUT(_context);
        _z80 = new Z80(_context);
        _core->_z80 = _z80;
        _context->pCore = _core;
    }

    void TearDown() override
    {
        if (_context)
        {
            if (_context->pCore)
            {
                _core->_z80 = nullptr;
                delete _z80;
                _context->pCore = nullptr;
                delete _core;
            }
            delete _context;
        }
    }

    static std::vector<uint8_t> readFile(const std::string& path)
    {
        std::vector<uint8_t> result;
        if (FileHelper::FileExists(path))
        {
            size_t size = FileHelper::GetFileSize(path);
            result.resize(size);
            if (size > 0) FileHelper::ReadFileToBuffer(path, result.data(), size);
        }
        return result;
    }

    static void removeFile(const std::string& path)
    {
        std::error_code ec;
        std::filesystem::remove(path, ec);
    }

    static std::string scratch(const char* name) { return TestPathHelper::GetTestScratchPath(name); }
    static std::string fixture(const char* name) { return TestPathHelper::GetTestDataPath(name); }

    /// Data pattern used by the generator for the EDSK fixture
    static uint8_t pattern(int track, int index, size_t i) { return static_cast<uint8_t>((track * 37 + index * 11 + i) & 0xFF); }

    static std::vector<uint8_t> patternBlock(int track, int index, size_t size)
    {
        std::vector<uint8_t> out(size);
        for (size_t i = 0; i < size; i++) out[i] = pattern(track, index, i);
        return out;
    }

    /// Load a fixture through the loader; returns the image (caller owns it)
    DiskImage* load(const char* name, std::vector<std::string>* warnings = nullptr)
    {
        LoaderDSK loader(_context, fixture(name));
        bool ok = loader.loadImage();
        EXPECT_TRUE(ok) << name << ": " << (loader.lastWarnings().empty() ? "" : loader.lastWarnings()[0]);
        if (warnings) *warnings = loader.lastWarnings();
        return ok ? loader.getImage() : nullptr;
    }

    static std::vector<uint8_t> sectorData(const DiskImage::Sector* sector)
    {
        return sector && sector->hasData ? std::vector<uint8_t>(sector->data, sector->data + sector->dataSize) : std::vector<uint8_t>();
    }

    static bool streamsEqual(const DiskImage::Track* a, const DiskImage::Track* b)
    {
        return a->rawSize() == b->rawSize() && a->encoding() == b->encoding() &&
               std::memcmp(a->rawData(), b->rawData(), a->rawSize()) == 0 && a->clockBitmap() == b->clockBitmap();
    }

    /// Sector list, data, flags and weak bytes of every track are identical
    static void expectSameContent(DiskImage* a, DiskImage* b)
    {
        ASSERT_EQ(a->getCylinders(), b->getCylinders());
        ASSERT_EQ(a->getSides(), b->getSides());

        for (uint8_t c = 0; c < a->getCylinders(); c++)
        {
            for (uint8_t h = 0; h < a->getSides(); h++)
            {
                DiskImage::Track* ta = a->getTrackForCylinderAndSide(c, h);
                DiskImage::Track* tb = b->getTrackForCylinderAndSide(c, h);
                ASSERT_NE(ta, nullptr);
                ASSERT_NE(tb, nullptr);
                EXPECT_EQ(ta->encoding(), tb->encoding()) << "cylinder " << (int)c << " side " << (int)h;
                ASSERT_EQ(ta->sectorCount(), tb->sectorCount()) << "cylinder " << (int)c << " side " << (int)h;

                for (size_t i = 0; i < ta->sectorCount(); i++)
                {
                    const DiskImage::Sector* sa = ta->getRawSector(i);
                    const DiskImage::Sector* sb = tb->getRawSector(i);
                    std::string where = StringHelper::Format("cylinder %d side %d physical sector %zu", c, h, i);
                    EXPECT_EQ(sa->number(), sb->number()) << where;
                    EXPECT_EQ(sa->cylinder(), sb->cylinder()) << where;
                    EXPECT_EQ(sa->head(), sb->head()) << where;
                    EXPECT_EQ(sa->sizeCode(), sb->sizeCode()) << where;
                    EXPECT_EQ(sa->dataSize, sb->dataSize) << where;
                    EXPECT_EQ(sa->hasData, sb->hasData) << where;
                    EXPECT_EQ(sa->deleted, sb->deleted) << where;
                    EXPECT_EQ(sa->idCrcValid, sb->idCrcValid) << where;
                    EXPECT_EQ(sa->dataCrcValid, sb->dataCrcValid) << where;
                    EXPECT_EQ(sectorData(sa), sectorData(sb)) << where;
                    if (sa->hasData && sb->hasData)
                    {
                        for (size_t bIdx = 0; bIdx < sa->dataSize; bIdx++)
                        {
                            EXPECT_EQ(ta->weakByte(sa->dataOffset + bIdx), tb->weakByte(sb->dataOffset + bIdx)) << where << " byte " << bIdx;
                        }
                    }
                }
            }
        }
    }
};

/// region <Detection>

TEST_F(LoaderDSK_Test, Detect_Standard)
{
    const char* sig = "MV - CPCEMU Disk-File\r\nDisk-Info\r\n";
    bool extended = true;
    EXPECT_TRUE(LoaderDSK::detect(reinterpret_cast<const uint8_t*>(sig), 34, &extended));
    EXPECT_FALSE(extended);

    // The +3 fixture is a standard image
    std::vector<uint8_t> data = readFile(fixture(PLUS3_FIXTURE));
    ASSERT_GE(data.size(), 256u);
    extended = true;
    EXPECT_TRUE(LoaderDSK::detect(data.data(), data.size(), &extended));
    EXPECT_FALSE(extended);

    LoaderDSK loader(_context, fixture(PLUS3_FIXTURE));
    ASSERT_TRUE(loader.loadImage());
    EXPECT_FALSE(loader.isExtended());
    EXPECT_EQ(loader.getCreator(), "dsk_image_gen");
    delete loader.getImage();

    // Not DSK
    const uint8_t udi[] = {'U', 'D', 'I', '!', 0, 0, 0, 0, 0, 0};
    EXPECT_FALSE(LoaderDSK::detect(udi, sizeof(udi), &extended));
    EXPECT_FALSE(LoaderDSK::detect(reinterpret_cast<const uint8_t*>(sig), 7, nullptr));
    EXPECT_FALSE(LoaderDSK::detect(nullptr, 0, nullptr));
}

TEST_F(LoaderDSK_Test, Detect_Extended)
{
    const char* sig = "EXTENDED CPC DSK File\r\nDisk-Info\r\n";
    bool extended = false;
    EXPECT_TRUE(LoaderDSK::detect(reinterpret_cast<const uint8_t*>(sig), 34, &extended));
    EXPECT_TRUE(extended);

    std::vector<uint8_t> data = readFile(fixture(EDSK_FIXTURE));
    ASSERT_GE(data.size(), 256u);
    extended = false;
    EXPECT_TRUE(LoaderDSK::detect(data.data(), data.size(), &extended));
    EXPECT_TRUE(extended);

    LoaderDSK loader(_context, fixture(EDSK_FIXTURE));
    ASSERT_TRUE(loader.loadImage());
    EXPECT_TRUE(loader.isExtended());
    delete loader.getImage();
}

/// endregion </Detection>

/// region <Load>

TEST_F(LoaderDSK_Test, Load_Plus3_Geometry)
{
    std::vector<std::string> warnings;
    DiskImage* image = load(PLUS3_FIXTURE, &warnings);
    ASSERT_NE(image, nullptr);
    EXPECT_TRUE(warnings.empty()) << warnings[0];

    EXPECT_EQ(image->getCylinders(), 40);
    EXPECT_EQ(image->getSides(), 1);
    EXPECT_TRUE(image->getLoaded());
    EXPECT_FALSE(image->isDirty());
    EXPECT_EQ(image->getFilePath(), fixture(PLUS3_FIXTURE));

    for (uint8_t t = 0; t < 40; t++)
    {
        DiskImage::Track* track = image->getTrackForCylinderAndSide(t, 0);
        ASSERT_NE(track, nullptr) << "track " << (int)t;
        EXPECT_EQ(track->rawSize(), 6250u) << "track " << (int)t;
        EXPECT_EQ(track->encoding(), DiskImage::Encoding::MFM);
        EXPECT_TRUE(track->hasClockMarks());
        EXPECT_NE(track->indexMarkOffset(), DiskImage::Sector::NO_OFFSET) << "+3 tracks carry an index mark";
        EXPECT_FALSE(track->isDirty());
        ASSERT_EQ(track->sectorCount(), 9u) << "track " << (int)t;

        for (size_t i = 0; i < 9; i++)
        {
            const DiskImage::Sector* sector = track->getRawSector(i);
            EXPECT_EQ(sector->number(), i + 1) << "track " << (int)t << " physical " << i;
            EXPECT_EQ(sector->cylinder(), t);
            EXPECT_EQ(sector->head(), 0);
            EXPECT_EQ(sector->sizeCode(), DiskImage::SECTOR_SIZE_512);
            EXPECT_EQ(sector->dataSize, 512);
            EXPECT_TRUE(sector->hasData);
            EXPECT_TRUE(sector->idCrcValid);
            EXPECT_TRUE(sector->dataCrcValid);
            EXPECT_FALSE(sector->deleted);
        }
    }

    // A data track of the blank disk is byte-for-byte the TrackFormatSpec::plus3() layout
    DiskImage reference(40, 1);
    reference.getTrackForCylinderAndSide(5, 0)->formatTrack(5, 0, Spec::plus3());
    EXPECT_TRUE(streamsEqual(image->getTrackForCylinderAndSide(5, 0), reference.getTrackForCylinderAndSide(5, 0)));

    // +3DOS disk specification in the boot sector
    const DiskImage::Sector* boot = image->getTrackForCylinderAndSide(0, 0)->findSector(1);
    ASSERT_NE(boot, nullptr);
    EXPECT_EQ(boot->data[0], 0x00);
    EXPECT_EQ(boot->data[2], 0x28);
    EXPECT_EQ(boot->data[3], 0x09);
    EXPECT_EQ(boot->data[4], 0x02);
    EXPECT_EQ(boot->data[8], 0x2A);
    EXPECT_EQ(boot->data[9], 0x52);
    unsigned sum = 0;
    for (size_t i = 0; i < 512; i++) sum += boot->data[i];
    EXPECT_EQ(sum % 256, 3u);

    delete image;
}

TEST_F(LoaderDSK_Test, Load_Cpc_SectorIds_C1_C9)
{
    DiskImage* image = load(EDSK_FIXTURE);
    ASSERT_NE(image, nullptr);
    EXPECT_EQ(image->getCylinders(), 7);
    EXPECT_EQ(image->getSides(), 1);

    DiskImage::Track* track = image->getTrackForCylinderAndSide(0, 0);
    ASSERT_EQ(track->sectorCount(), 9u);
    for (size_t i = 0; i < 9; i++)
    {
        const DiskImage::Sector* sector = track->getRawSector(i);
        EXPECT_EQ(sector->number(), 0xC1 + i);
        EXPECT_EQ(sector->cylinder(), 0);
        EXPECT_EQ(sector->dataSize, 512);
        EXPECT_TRUE(sector->idCrcValid);
        EXPECT_TRUE(sector->dataCrcValid);
        EXPECT_EQ(sectorData(sector), patternBlock(0, static_cast<int>(i), 512));
    }
    EXPECT_NE(track->findSector(0xC5), nullptr);
    EXPECT_EQ(track->findSector(1), nullptr) << "IDs are preserved, not renumbered";

    // The ID fields hold the CPC numbers, so a sector search by number works through the index
    EXPECT_EQ(track->findSector(0xC9)->id->sector, 0xC9);

    delete image;
}

TEST_F(LoaderDSK_Test, Load_Status_Bits)
{
    DiskImage* image = load(EDSK_FIXTURE);
    ASSERT_NE(image, nullptr);

    // Track 1: sector 3 has a deleted data mark (ST2 bit 6)
    DiskImage::Track* deletedTrack = image->getTrackForCylinderAndSide(1, 0);
    ASSERT_EQ(deletedTrack->sectorCount(), 9u);
    for (uint8_t r = 1; r <= 9; r++)
    {
        const DiskImage::Sector* s = deletedTrack->findSector(r);
        ASSERT_NE(s, nullptr);
        EXPECT_EQ(s->deleted, r == 3) << "sector " << (int)r;
        EXPECT_EQ(s->dataAddressMark(), r == 3 ? 0xF8 : 0xFB) << "sector " << (int)r;
        EXPECT_TRUE(s->hasData);
        EXPECT_TRUE(s->idCrcValid);
        EXPECT_TRUE(s->dataCrcValid) << "deleted mark keeps a valid CRC";
        EXPECT_EQ(sectorData(s), patternBlock(1, r - 1, 512));
    }

    // Track 2: sector 2 data CRC error (ST1 bit 5 + ST2 bit 5), sector 4 ID CRC error (ST1 bit 5 alone)
    DiskImage::Track* crcTrack = image->getTrackForCylinderAndSide(2, 0);
    ASSERT_EQ(crcTrack->sectorCount(), 9u);
    for (uint8_t r = 1; r <= 9; r++)
    {
        const DiskImage::Sector* s = crcTrack->findSector(r);
        ASSERT_NE(s, nullptr) << "sector " << (int)r;
        EXPECT_TRUE(s->hasData);
        EXPECT_EQ(s->dataCrcValid, r != 2) << "sector " << (int)r;
        EXPECT_EQ(s->idCrcValid, r != 4) << "sector " << (int)r;
        EXPECT_FALSE(s->deleted);
        EXPECT_EQ(sectorData(s), patternBlock(2, r - 1, 512)) << "data is kept even when its CRC is bad";
    }

    // Track 3: sector 5 is ID-only (ST1 bit 2, no data)
    DiskImage::Track* idOnlyTrack = image->getTrackForCylinderAndSide(3, 0);
    ASSERT_EQ(idOnlyTrack->sectorCount(), 9u);
    for (uint8_t r = 1; r <= 9; r++)
    {
        const DiskImage::Sector* s = idOnlyTrack->findSector(r);
        ASSERT_NE(s, nullptr) << "sector " << (int)r;
        EXPECT_EQ(s->hasData, r != 5) << "sector " << (int)r;
        EXPECT_TRUE(s->idCrcValid);
        if (r == 5)
        {
            EXPECT_EQ(s->data, nullptr);
            EXPECT_EQ(s->damOffset, DiskImage::Sector::NO_OFFSET);
            EXPECT_FALSE(s->dataCrcValid);
        }
    }

    delete image;
}

TEST_F(LoaderDSK_Test, Load_WeakSector_MultiCopy)
{
    DiskImage* image = load(EDSK_FIXTURE);
    ASSERT_NE(image, nullptr);

    DiskImage::Track* track = image->getTrackForCylinderAndSide(4, 0);
    ASSERT_EQ(track->sectorCount(), 9u);
    EXPECT_TRUE(track->hasWeakBits());

    const DiskImage::Sector* weak = track->findSector(6);
    ASSERT_NE(weak, nullptr);
    ASSERT_TRUE(weak->hasData);
    EXPECT_EQ(weak->dataSize, 512) << "two copies do not change the sector size";
    EXPECT_EQ(sectorData(weak), patternBlock(4, 5, 512)) << "the first copy is stored";
    EXPECT_TRUE(weak->dataCrcValid);

    // Bytes 10, 200 and 511 differ between the copies
    EXPECT_TRUE(track->weakByte(weak->dataOffset + 10));
    EXPECT_TRUE(track->weakByte(weak->dataOffset + 200));
    EXPECT_TRUE(track->weakByte(weak->dataOffset + 511));
    EXPECT_FALSE(track->weakByte(weak->dataOffset + 0));
    EXPECT_FALSE(track->weakByte(weak->dataOffset + 11));
    EXPECT_FALSE(track->weakByte(weak->dataOffset + 199));
    EXPECT_FALSE(track->weakByte(weak->dataOffset + 510));

    size_t weakCount = 0;
    for (size_t i = 0; i < track->rawSize(); i++) if (track->weakByte(i)) weakCount++;
    EXPECT_EQ(weakCount, 3u);

    // Other sectors and tracks are not weak
    const DiskImage::Sector* solid = track->findSector(7);
    for (size_t i = 0; i < solid->dataSize; i++) EXPECT_FALSE(track->weakByte(solid->dataOffset + i));
    EXPECT_FALSE(image->getTrackForCylinderAndSide(0, 0)->hasWeakBits());
    EXPECT_FALSE(image->getTrackForCylinderAndSide(6, 0)->hasWeakBits());

    delete image;
}

TEST_F(LoaderDSK_Test, Load_Unformatted_Track)
{
    DiskImage* image = load(EDSK_FIXTURE);
    ASSERT_NE(image, nullptr);

    DiskImage::Track* track = image->getTrackForCylinderAndSide(5, 0);
    ASSERT_NE(track, nullptr);
    EXPECT_EQ(track->sectorCount(), 0u);
    EXPECT_EQ(track->rawSize(), 6250u);
    EXPECT_EQ(track->encoding(), DiskImage::Encoding::MFM);
    EXPECT_EQ(track->indexMarkOffset(), DiskImage::Sector::NO_OFFSET);
    EXPECT_FALSE(track->hasClockMarks());
    size_t gapBytes = 0;
    for (size_t i = 0; i < track->rawSize(); i++) if (track->rawData()[i] == 0x4E) gapBytes++;
    EXPECT_EQ(gapBytes, 6250u);

    // The track after the unformatted one is located correctly
    DiskImage::Track* next = image->getTrackForCylinderAndSide(6, 0);
    ASSERT_EQ(next->sectorCount(), 9u);
    for (uint8_t r = 1; r <= 9; r++)
    {
        const DiskImage::Sector* s = next->findSector(r);
        ASSERT_NE(s, nullptr);
        EXPECT_EQ(s->cylinder(), 6);
        EXPECT_EQ(sectorData(s), patternBlock(6, r - 1, 512));
    }

    delete image;
}

/// endregion </Load>

/// region <Save>

TEST_F(LoaderDSK_Test, Save_RoundTrip)
{
    const char* fixtures[] = {PLUS3_FIXTURE, EDSK_FIXTURE};

    for (const char* name : fixtures)
    {
        std::string target = scratch("roundtrip.dsk");
        removeFile(target);

        LoaderDSK loader(_context, fixture(name));
        ASSERT_TRUE(loader.loadImage()) << name;
        DiskImage* image = loader.getImage();

        ASSERT_TRUE(loader.writeImage(target)) << name << ": " << (loader.lastWarnings().empty() ? "" : loader.lastWarnings()[0]);
        EXPECT_TRUE(loader.lastWarnings().empty()) << name << ": " << loader.lastWarnings()[0];
        EXPECT_FALSE(image->isDirty());
        EXPECT_EQ(image->getFilePath(), target);

        // Always Extended DSK with our creator
        std::vector<uint8_t> saved = readFile(target);
        ASSERT_GE(saved.size(), 256u);
        bool extended = false;
        EXPECT_TRUE(LoaderDSK::detect(saved.data(), saved.size(), &extended));
        EXPECT_TRUE(extended) << name;
        EXPECT_EQ(std::memcmp(saved.data(), "EXTENDED CPC DSK File\r\nDisk-Info\r\n", 34), 0);
        EXPECT_EQ(std::memcmp(saved.data() + 0x22, "unreal-ng     ", 14), 0);
        EXPECT_EQ(saved[0x30], image->getCylinders());
        EXPECT_EQ(saved[0x31], image->getSides());

        LoaderDSK back(_context, target);
        ASSERT_TRUE(back.loadImage()) << name << ": " << (back.lastWarnings().empty() ? "" : back.lastWarnings()[0]);
        EXPECT_TRUE(back.isExtended());
        EXPECT_EQ(back.getCreator(), "unreal-ng");
        DiskImage* reloaded = back.getImage();

        expectSameContent(image, reloaded);

        // Saving again produces the same bytes (deterministic)
        ASSERT_TRUE(back.writeImage(target));
        EXPECT_EQ(readFile(target), saved) << name;

        removeFile(target);
        delete reloaded;
        delete image;
    }
}

TEST_F(LoaderDSK_Test, Save_TrackInfo_Gap3_Filler_And_SectorList)
{
    DiskImage* image = load(PLUS3_FIXTURE);
    ASSERT_NE(image, nullptr);

    LoaderDSK loader(_context, "");
    std::vector<uint8_t> out;
    std::vector<std::string> warnings;
    ASSERT_TRUE(loader.serialize(image, out, warnings));
    EXPECT_TRUE(warnings.empty());

    // Track block size: 256 + 9 * 512 = 0x1300 => 0x13 in the size table
    const size_t trackBlock = 256 + 9 * 512;
    EXPECT_EQ(out.size(), 256 + 40 * trackBlock);
    for (size_t t = 0; t < 40; t++) EXPECT_EQ(out[0x34 + t], 0x13) << "track " << t;
    EXPECT_EQ(out[0x32], 0);
    EXPECT_EQ(out[0x33], 0);

    // Track 7 info block
    const uint8_t* info = out.data() + 256 + 7 * trackBlock;
    EXPECT_EQ(std::memcmp(info, "Track-Info\r\n", 12), 0);
    EXPECT_EQ(info[0x10], 7);
    EXPECT_EQ(info[0x11], 0);
    EXPECT_EQ(info[0x12], 1) << "data rate SD/DD";
    EXPECT_EQ(info[0x13], 2) << "MFM";
    EXPECT_EQ(info[0x14], 2) << "N";
    EXPECT_EQ(info[0x15], 9) << "S";
    EXPECT_EQ(info[0x16], 0x2A) << "GAP#3 measured from the stream";
    EXPECT_EQ(info[0x17], 0xE5) << "filler";
    for (size_t i = 0; i < 9; i++)
    {
        const uint8_t* entry = info + 0x18 + 8 * i;
        EXPECT_EQ(entry[0], 7);
        EXPECT_EQ(entry[1], 0);
        EXPECT_EQ(entry[2], i + 1);
        EXPECT_EQ(entry[3], 2);
        EXPECT_EQ(entry[4], 0);
        EXPECT_EQ(entry[5], 0);
        EXPECT_EQ(entry[6] | (entry[7] << 8), 512);
    }
    EXPECT_EQ(info[256], 0xE5) << "first data byte";

    // Status bits and lengths of the EDSK fixture
    DiskImage* edsk = load(EDSK_FIXTURE);
    ASSERT_NE(edsk, nullptr);
    out.clear();
    ASSERT_TRUE(loader.serialize(edsk, out, warnings));
    EXPECT_TRUE(warnings.empty());

    auto trackInfo = [&](size_t t) -> const uint8_t*
    {
        size_t pos = 256;
        for (size_t i = 0; i < t; i++) pos += static_cast<size_t>(out[0x34 + i]) * 256;
        return out.data() + pos;
    };

    EXPECT_EQ(out[0x34 + 5], 0) << "unformatted track has size 0";
    EXPECT_EQ(out[0x34 + 4], (256 + 8 * 512 + 2 * 512) / 256) << "weak sector stored twice";

    const uint8_t* t0 = trackInfo(0);
    EXPECT_EQ(t0[0x16], 0x4E) << "CPC data format GAP#3 survives";
    EXPECT_EQ(t0[0x18 + 2], 0xC1);
    EXPECT_EQ(t0[0x18 + 8 * 8 + 2], 0xC9);

    const uint8_t* t1 = trackInfo(1);
    EXPECT_EQ(t1[0x18 + 2 * 8 + 5] & 0x40, 0x40) << "deleted => ST2 bit 6";

    const uint8_t* t2 = trackInfo(2);
    EXPECT_EQ(t2[0x18 + 1 * 8 + 4], 0x20) << "data CRC error => ST1 bit 5";
    EXPECT_EQ(t2[0x18 + 1 * 8 + 5], 0x20) << "data CRC error => ST2 bit 5";
    EXPECT_EQ(t2[0x18 + 3 * 8 + 4], 0x20) << "ID CRC error => ST1 bit 5";
    EXPECT_EQ(t2[0x18 + 3 * 8 + 5], 0x00) << "ID CRC error => ST2 clear";

    const uint8_t* t3 = trackInfo(3);
    EXPECT_EQ(t3[0x18 + 4 * 8 + 4] & 0x04, 0x04) << "ID-only => ST1 bit 2";
    EXPECT_EQ(t3[0x18 + 4 * 8 + 6] | (t3[0x18 + 4 * 8 + 7] << 8), 0) << "ID-only => length 0";

    const uint8_t* t4 = trackInfo(4);
    EXPECT_EQ(t4[0x18 + 5 * 8 + 6] | (t4[0x18 + 5 * 8 + 7] << 8), 1024) << "weak => two copies";

    delete edsk;
    delete image;
}

TEST_F(LoaderDSK_Test, Save_Synthetic_Fm_And_MixedSizes)
{
    // FM track, a 1024-byte sector track, a TR-DOS track and a long-gap track survive the DSK round trip
    DiskImage image(4, 2);
    image.getTrackForCylinderAndSide(0, 0)->formatTrack(0, 0, Spec::ibm3740());
    image.getTrackForCylinderAndSide(0, 1)->formatTrack(0, 1, Spec::ibm(5, DiskImage::SECTOR_SIZE_1024, 1, 0x50, 0xAA));
    image.getTrackForCylinderAndSide(1, 0)->formatTrack(1, 0, Spec::trdos());

    Spec mixed = Spec::ibm(4, DiskImage::SECTOR_SIZE_256, 1, 0x30, 0x11);
    mixed.sectorSizeCodes = {0, 1, 2, 3};
    mixed.sectorCylinders = {1, 1, 200, 1};
    mixed.sectorHeads = {1, 0, 1, 1};
    image.getTrackForCylinderAndSide(1, 1)->formatTrack(1, 1, mixed);

    DiskImage::Track* patterned = image.getTrackForCylinderAndSide(2, 0);
    std::vector<uint8_t> data = patternBlock(2, 3, 256);
    patterned->writeSectorData(3, data.data(), data.size());
    patterned->getSector(5)->setDataAddressMark(0xF8);
    patterned->getSector(5)->recalculateDataCRC();
    patterned->setWeakByte(patterned->getSector(7)->dataOffset + 100, true);
    patterned->reindex();

    LoaderDSK loader(_context, "");
    std::vector<uint8_t> out;
    std::vector<std::string> warnings;
    ASSERT_TRUE(loader.serialize(&image, out, warnings));
    EXPECT_TRUE(warnings.empty()) << warnings[0];

    LoaderDSK reader(_context, "");
    DiskImage* reloaded = reader.parse(out.data(), out.size(), warnings);
    ASSERT_NE(reloaded, nullptr) << (warnings.empty() ? "" : warnings[0]);

    expectSameContent(&image, reloaded);
    EXPECT_EQ(reloaded->getTrackForCylinderAndSide(0, 0)->encoding(), DiskImage::Encoding::FM);
    EXPECT_EQ(reloaded->getTrackForCylinderAndSide(0, 0)->rawSize(), 3125u);
    EXPECT_EQ(reloaded->getTrackForCylinderAndSide(0, 1)->getRawSector(0)->dataSize, 1024);
    EXPECT_EQ(reloaded->getTrackForCylinderAndSide(1, 1)->getRawSector(2)->cylinder(), 200);
    EXPECT_EQ(reloaded->getTrackForCylinderAndSide(1, 1)->getRawSector(1)->head(), 0);
    EXPECT_EQ(sectorData(reloaded->getTrackForCylinderAndSide(2, 0)->getSector(3)), data);
    EXPECT_TRUE(reloaded->getTrackForCylinderAndSide(2, 0)->getSector(5)->deleted);

    delete reloaded;
}

TEST_F(LoaderDSK_Test, CreateBlankPlus3Image)
{
    DiskImage* image = LoaderDSK::createBlankPlus3Image();
    ASSERT_NE(image, nullptr);
    EXPECT_EQ(image->getCylinders(), 40);
    EXPECT_EQ(image->getSides(), 1);
    EXPECT_FALSE(image->isDirty());

    DiskImage* fixtureImage = load(PLUS3_FIXTURE);
    ASSERT_NE(fixtureImage, nullptr);
    for (uint8_t t = 1; t < 40; t++)
    {
        EXPECT_TRUE(streamsEqual(image->getTrackForCylinderAndSide(t, 0), fixtureImage->getTrackForCylinderAndSide(t, 0))) << "track " << (int)t;
    }
    EXPECT_EQ(image->getTrackForCylinderAndSide(0, 0)->sectorCount(), 9u);
    EXPECT_EQ(image->getTrackForCylinderAndSide(0, 0)->findSector(1)->data[0], 0xE5) << "no disk specification: +3DOS assumes the standard format";

    delete fixtureImage;
    delete image;
}

/// endregion </Save>

/// region <Controller>

TEST_F(LoaderDSK_Test, Wd1793_ReadSector_512)
{
    DiskImage* image = load(PLUS3_FIXTURE);
    ASSERT_NE(image, nullptr);

    // Put a recognisable pattern into track 12 sector 5 (the blank disk holds 0xE5 everywhere)
    DiskImage::Track* track = image->getTrackForCylinderAndSide(12, 0);
    std::vector<uint8_t> pattern(512);
    for (size_t i = 0; i < 512; i++) pattern[i] = static_cast<uint8_t>((i * 7) ^ 0x5A);
    track->writeSectorData(4, pattern.data(), pattern.size());

    WD1793CUT fdc(_context);
    fdc.getDrive()->insertDisk(image);
    fdc._beta128Register = WD1793CUT::BETA128_COMMAND_BITS::BETA_CMD_RESET;  // MFM (the DENSITY bit selects FM)
    fdc._drive = 0;
    fdc.wakeUp();
    fdc._time = 1000;
    fdc.prolongFDDMotorRotation();
    fdc._trackRegister = 12;
    fdc._selectedDrive->setTrack(12);
    fdc._sideUp = false;
    fdc._sectorRegister = 5;
    fdc._commandRegister = 0x80;
    fdc._lastDecodedCmd = WD1793::WD_CMD_READ_SECTOR;
    fdc.cmdReadSector(0x00);

    std::vector<uint8_t> read;
    for (size_t clk = 1000; clk < 1000 + 3'500'000 * 3 && fdc._state != WD1793::S_IDLE; clk += 100)
    {
        fdc._time = clk;
        fdc.process();
        if (fdc._beta128status & WD1793::DRQ) read.push_back(fdc.readDataRegister());
    }

    EXPECT_EQ(fdc._state, WD1793::S_IDLE);
    ASSERT_EQ(read.size(), 512u);
    EXPECT_EQ(read, pattern);
    EXPECT_FALSE(fdc._statusRegister & WD1793::WDS_CRCERR);
    EXPECT_FALSE(fdc._statusRegister & WD1793::WDS_NOTFOUND);

    // An untouched sector of the blank disk reads as 512 x 0xE5
    fdc._sectorRegister = 9;
    fdc._commandRegister = 0x80;
    fdc._lastDecodedCmd = WD1793::WD_CMD_READ_SECTOR;
    fdc.cmdReadSector(0x00);
    read.clear();
    const size_t start = fdc._time + 1000;
    for (size_t clk = start; clk < start + 3'500'000 * 3 && fdc._state != WD1793::S_IDLE; clk += 100)
    {
        fdc._time = clk;
        fdc.process();
        if (fdc._beta128status & WD1793::DRQ) read.push_back(fdc.readDataRegister());
    }
    ASSERT_EQ(read.size(), 512u);
    EXPECT_EQ(read, std::vector<uint8_t>(512, 0xE5));

    fdc.getDrive()->ejectDisk();
    delete image;
}

/// endregion </Controller>

/// region <Negative>

TEST_F(LoaderDSK_Test, Negative_Truncated)
{
    std::vector<uint8_t> edsk = readFile(fixture(EDSK_FIXTURE));
    std::vector<uint8_t> dsk = readFile(fixture(PLUS3_FIXTURE));
    ASSERT_GT(edsk.size(), 256u + 3 * 4864);
    ASSERT_GT(dsk.size(), 256u + 5 * 4864);

    LoaderDSK loader(_context, "");
    std::vector<std::string> warnings;

    // Shorter than the disk information block
    EXPECT_EQ(loader.parse(edsk.data(), 100, warnings), nullptr);
    ASSERT_FALSE(warnings.empty());
    EXPECT_NE(warnings.back().find("truncated"), std::string::npos);

    // Cut inside the sector data of track 3 (extended)
    warnings.clear();
    EXPECT_EQ(loader.parse(edsk.data(), 256 + 3 * 4864 + 256 + 1000, warnings), nullptr);
    ASSERT_FALSE(warnings.empty());
    EXPECT_NE(warnings.back().find("truncated"), std::string::npos);

    // Cut inside the track information block of track 4 (extended)
    warnings.clear();
    EXPECT_EQ(loader.parse(edsk.data(), 256 + 3 * 4864 + 4352 + 100, warnings), nullptr);
    ASSERT_FALSE(warnings.empty());
    EXPECT_NE(warnings.back().find("truncated"), std::string::npos);

    // Cut inside track 5 of the standard image
    warnings.clear();
    EXPECT_EQ(loader.parse(dsk.data(), 256 + 5 * 4864 + 256 + 3 * 512 + 17, warnings), nullptr);
    ASSERT_FALSE(warnings.empty());
    EXPECT_NE(warnings.back().find("truncated"), std::string::npos);

    // Wrong signature
    std::vector<uint8_t> bad = dsk;
    std::memcpy(bad.data(), "NOT A DSK", 9);
    warnings.clear();
    EXPECT_EQ(loader.parse(bad.data(), bad.size(), warnings), nullptr);
    ASSERT_FALSE(warnings.empty());
    EXPECT_NE(warnings.back().find("Not a DSK"), std::string::npos);

    // Missing Track-Info signature
    bad = dsk;
    bad[256] = 'X';
    warnings.clear();
    EXPECT_EQ(loader.parse(bad.data(), bad.size(), warnings), nullptr);
    ASSERT_FALSE(warnings.empty());
    EXPECT_NE(warnings.back().find("Track-Info"), std::string::npos);

    // Impossible geometry
    bad = dsk;
    bad[0x31] = 3;
    warnings.clear();
    EXPECT_EQ(loader.parse(bad.data(), bad.size(), warnings), nullptr);
    bad[0x31] = 1;
    bad[0x30] = 0;
    warnings.clear();
    EXPECT_EQ(loader.parse(bad.data(), bad.size(), warnings), nullptr);
    bad[0x30] = 100;
    warnings.clear();
    EXPECT_EQ(loader.parse(bad.data(), bad.size(), warnings), nullptr);

    // Missing file
    LoaderDSK missing(_context, scratch("does-not-exist.dsk"));
    EXPECT_FALSE(missing.loadImage());
    EXPECT_FALSE(missing.lastWarnings().empty());

    // Nothing to save
    LoaderDSK empty(_context, "");
    EXPECT_FALSE(empty.writeImage(scratch("nothing.dsk")));
    EXPECT_FALSE(empty.lastWarnings().empty());
}

TEST_F(LoaderDSK_Test, Load_LayoutLargerThanTrack_Grows)
{
    // 18 x 256 with GAP#3 0x2A needs more than 6250 bytes: the track grows with a warning
    std::vector<uint8_t> file(256 + 256 + 18 * 256, 0);
    std::memcpy(file.data(), "EXTENDED CPC DSK File\r\nDisk-Info\r\n", 34);
    file[0x30] = 1;
    file[0x31] = 1;
    file[0x34] = static_cast<uint8_t>((256 + 18 * 256) / 256);
    uint8_t* info = file.data() + 256;
    std::memcpy(info, "Track-Info\r\n", 12);
    info[0x13] = 2;
    info[0x14] = 1;
    info[0x15] = 18;
    info[0x16] = 0x2A;
    info[0x17] = 0xE5;
    for (size_t i = 0; i < 18; i++)
    {
        uint8_t* entry = info + 0x18 + 8 * i;
        entry[2] = static_cast<uint8_t>(i + 1);
        entry[3] = 1;
        entry[6] = 0x00;
        entry[7] = 0x01;
        std::memset(file.data() + 512 + i * 256, static_cast<int>(i), 256);
    }

    LoaderDSK loader(_context, "");
    std::vector<std::string> warnings;
    DiskImage* image = loader.parse(file.data(), file.size(), warnings);
    ASSERT_NE(image, nullptr) << (warnings.empty() ? "" : warnings[0]);
    ASSERT_FALSE(warnings.empty());
    EXPECT_NE(warnings[0].find("grown"), std::string::npos);

    DiskImage::Track* track = image->getTrack(0);
    EXPECT_GT(track->rawSize(), 6250u);
    EXPECT_LE(track->rawSize(), DiskImage::RawTrack::MAX_TRACK_SIZE);
    ASSERT_EQ(track->sectorCount(), 18u);
    EXPECT_EQ(track->findSector(18)->data[0], 17);
    EXPECT_TRUE(track->findSector(18)->dataCrcValid);

    delete image;
}

/// endregion </Negative>
