#include "loaders/disk/loader_mgt.h"

#include <gtest/gtest.h>

#include <algorithm>
#include <cstring>
#include <filesystem>
#include <vector>

#include <common/filehelper.h>
#include <common/stringhelper.h>

#include "_helpers/testpathhelper.h"
#include "emulator/cpu/core.h"
#include "emulator/emulatorcontext.h"
#include "emulator/io/fdc/diskimage.h"
#include "emulator/io/fdc/wd1793.h"

/// MGT / IMG loader tests (docs/inprogress/2026-09-02-universal-track-model/loader-mgt.md, section 4)
///
/// Fixtures: testdata/loaders/mgt/synthetic.{mgt,img} generated by
/// core/tests/emulator/io/fdc/tools/mgt_hobeta_generator.py - every sector starts with
/// byte 0 = cylinder, byte 1 = (side << 4) | sector number, followed by a deterministic pattern.

using Spec = DiskImage::TrackFormatSpec;
using TrackOrder = LoaderMGT::TrackOrder;

class LoaderMGT_Test : public ::testing::Test
{
protected:
    EmulatorContext* _context = nullptr;
    CoreCUT* _core = nullptr;
    Z80* _z80 = nullptr;

protected:
    void SetUp() override
    {
        _context = new EmulatorContext(LoggerLevel::LogError);
        _context->pModuleLogger->TurnOffLoggingForAll();

        _core = new CoreCUT(_context);
        _z80 = new Z80(_context);
        _core->_z80 = _z80;
        _context->pCore = _core;
    }

    void TearDown() override
    {
        if (_context)
        {
            if (_context->pCore)
            {
                _core->_z80 = nullptr;
                delete _z80;
                _context->pCore = nullptr;
                delete _core;
            }
            delete _context;
        }
    }

    static std::vector<uint8_t> readFile(const std::string& path)
    {
        std::vector<uint8_t> result;
        if (FileHelper::FileExists(path))
        {
            size_t size = FileHelper::GetFileSize(path);
            result.resize(size);
            if (size > 0) FileHelper::ReadFileToBuffer(path, result.data(), size);
        }
        return result;
    }

    static void removeFile(const std::string& path)
    {
        std::error_code ec;
        std::filesystem::remove(path, ec);
    }

    static std::string join(const std::vector<std::string>& items, const char* separator = "; ")
    {
        std::string result;
        for (const std::string& item : items)
        {
            if (!result.empty()) result += separator;
            result += item;
        }
        return result;
    }

    static std::string fixture(const char* name) { return TestPathHelper::GetTestDataPath(name); }
    static std::string scratch(const char* name) { return TestPathHelper::GetTestScratchPath(name); }

    /// Expected content of a synthetic sector (mirrors mgt_hobeta_generator.py)
    static std::vector<uint8_t> expectedSector(uint8_t cylinder, uint8_t side, uint8_t number)
    {
        std::vector<uint8_t> data(LoaderMGT::SECTOR_SIZE);
        data[0] = cylinder;
        data[1] = static_cast<uint8_t>((side << 4) | number);
        for (size_t i = 2; i < data.size(); i++)
        {
            data[i] = static_cast<uint8_t>((cylinder * 7 + side * 13 + number * 3 + i) & 0xFF);
        }
        return data;
    }

    /// Every sector of every track carries the synthetic pattern for its own (cylinder, side, number)
    static void verifySyntheticContent(DiskImage* image, const char* label)
    {
        ASSERT_EQ(image->getCylinders(), 80) << label;
        ASSERT_EQ(image->getSides(), 2) << label;

        for (uint8_t c = 0; c < 80; c++)
        {
            for (uint8_t s = 0; s < 2; s++)
            {
                DiskImage::Track* track = image->getTrackForCylinderAndSide(c, s);
                ASSERT_NE(track, nullptr) << label;
                ASSERT_EQ(track->sectorCount(), 10u) << label << " cyl " << (int)c << " side " << (int)s;

                for (uint8_t n = 1; n <= 10; n++)
                {
                    DiskImage::Sector* sector = track->getSector(static_cast<uint8_t>(n - 1));
                    ASSERT_NE(sector, nullptr) << label;
                    ASSERT_TRUE(sector->hasData) << label;
                    ASSERT_EQ(sector->dataSize, 512) << label;
                    EXPECT_EQ(sector->number(), n) << label;
                    EXPECT_EQ(sector->cylinder(), c) << label;
                    EXPECT_EQ(sector->head(), s) << label;

                    std::vector<uint8_t> expected = expectedSector(c, s, n);
                    ASSERT_EQ(std::memcmp(sector->data, expected.data(), expected.size()), 0)
                        << label << ": cyl " << (int)c << " side " << (int)s << " sector " << (int)n
                        << " carries data tagged cyl " << (int)sector->data[0] << " side " << (sector->data[1] >> 4)
                        << " sector " << (sector->data[1] & 0x0F);
                }
            }
        }
    }
};

/// region <Detection / geometry>

TEST_F(LoaderMGT_Test, Detect_BySize_And_Extension)
{
    // 80 cylinders, both extensions, any case, with or without a dot, or a full path
    EXPECT_TRUE(LoaderMGT::detect(819200, "mgt"));
    EXPECT_TRUE(LoaderMGT::detect(819200, ".mgt"));
    EXPECT_TRUE(LoaderMGT::detect(819200, ".MGT"));
    EXPECT_TRUE(LoaderMGT::detect(819200, "img"));
    EXPECT_TRUE(LoaderMGT::detect(819200, ".IMG"));
    EXPECT_TRUE(LoaderMGT::detect(819200, "/some/dir.with.dots/game.img"));

    // 40 cylinders
    EXPECT_TRUE(LoaderMGT::detect(409600, ".mgt"));
    EXPECT_TRUE(LoaderMGT::detect(409600, ".img"));
    EXPECT_EQ(LoaderMGT::cylindersForSize(819200), 80);
    EXPECT_EQ(LoaderMGT::cylindersForSize(409600), 40);

    // Wrong extension or size
    EXPECT_FALSE(LoaderMGT::detect(819200, ".trd"));
    EXPECT_FALSE(LoaderMGT::detect(819200, ".dsk"));
    EXPECT_FALSE(LoaderMGT::detect(819200, ""));
    EXPECT_FALSE(LoaderMGT::detect(655360, ".mgt"));
    EXPECT_FALSE(LoaderMGT::detect(819201, ".mgt"));
    EXPECT_FALSE(LoaderMGT::detect(0, ".mgt"));
    EXPECT_EQ(LoaderMGT::cylindersForSize(655360), 0);

    // Track order follows the extension
    EXPECT_EQ(LoaderMGT::orderForExtension(".mgt"), TrackOrder::CylinderMajor);
    EXPECT_EQ(LoaderMGT::orderForExtension("disk.IMG"), TrackOrder::SideMajor);
    EXPECT_EQ(LoaderMGT::orderForExtension("noext"), TrackOrder::CylinderMajor);

    // The fixtures load with the right geometry
    LoaderMGT loader(_context, fixture("loaders/mgt/synthetic.mgt"));
    ASSERT_TRUE(loader.loadImage()) << join(loader.lastWarnings(), "; ");
    DiskImage* image = loader.getImage();
    ASSERT_NE(image, nullptr);
    EXPECT_EQ(image->getCylinders(), 80);
    EXPECT_EQ(image->getSides(), 2);
    EXPECT_TRUE(image->getLoaded());
    EXPECT_FALSE(image->isDirty());
    EXPECT_EQ(image->getFilePath(), fixture("loaders/mgt/synthetic.mgt"));
    delete image;

    // A 40-cylinder dump: first half of the .img file is exactly side 0 of 80 cylinders, but parsed as a
    // 409600-byte .mgt buffer it must produce 40 cylinders x 2 sides
    std::vector<uint8_t> full = readFile(fixture("loaders/mgt/synthetic.mgt"));
    ASSERT_EQ(full.size(), 819200u);
    std::vector<std::string> warnings;
    DiskImage* half = loader.parse(full.data(), 409600, TrackOrder::CylinderMajor, warnings);
    ASSERT_NE(half, nullptr) << join(warnings, "; ");
    EXPECT_EQ(half->getCylinders(), 40);
    EXPECT_EQ(half->getSides(), 2);
    // The first 40 cylinders of a cylinder-major dump are the first 40 cylinders of the disk
    EXPECT_EQ(half->getTrackForCylinderAndSide(39, 1)->getSector(9)->data[0], 39);
    EXPECT_EQ(half->getTrackForCylinderAndSide(39, 1)->getSector(9)->data[1], (1 << 4) | 10);
    delete half;

    // Wrong size is refused with a warning
    DiskImage* bad = loader.parse(full.data(), 1000, TrackOrder::CylinderMajor, warnings);
    EXPECT_EQ(bad, nullptr);
    EXPECT_FALSE(warnings.empty());

    LoaderMGT missing(_context, fixture("loaders/mgt/does-not-exist.mgt"));
    EXPECT_FALSE(missing.loadImage());
    EXPECT_FALSE(missing.lastWarnings().empty());
}

TEST_F(LoaderMGT_Test, Load_TrackOrder_Mgt_vs_Img)
{
    // The two fixtures carry the same disk in the two track orders. Both must land every sector on its own
    // (cylinder, side) - the sector tags make a misplaced track visible.
    LoaderMGT mgtLoader(_context, fixture("loaders/mgt/synthetic.mgt"));
    ASSERT_TRUE(mgtLoader.loadImage()) << join(mgtLoader.lastWarnings(), "; ");
    DiskImage* fromMgt = mgtLoader.getImage();

    LoaderMGT imgLoader(_context, fixture("loaders/mgt/synthetic.img"));
    ASSERT_TRUE(imgLoader.loadImage()) << join(imgLoader.lastWarnings(), "; ");
    DiskImage* fromImg = imgLoader.getImage();

    verifySyntheticContent(fromMgt, ".mgt");
    verifySyntheticContent(fromImg, ".img");

    // Same track content from both files (raw stream included: identical format, identical data)
    for (uint8_t c = 0; c < 80; c++)
    {
        for (uint8_t s = 0; s < 2; s++)
        {
            DiskImage::Track* a = fromMgt->getTrackForCylinderAndSide(c, s);
            DiskImage::Track* b = fromImg->getTrackForCylinderAndSide(c, s);
            ASSERT_EQ(a->rawSize(), b->rawSize());
            EXPECT_EQ(std::memcmp(a->rawData(), b->rawData(), a->rawSize()), 0) << "cyl " << (int)c << " side " << (int)s;
        }
    }

    // The files themselves are different (tracks are in a different order) although they hold the same disk
    std::vector<uint8_t> mgtBytes = readFile(fixture("loaders/mgt/synthetic.mgt"));
    std::vector<uint8_t> imgBytes = readFile(fixture("loaders/mgt/synthetic.img"));
    ASSERT_EQ(mgtBytes.size(), imgBytes.size());
    EXPECT_NE(std::memcmp(mgtBytes.data(), imgBytes.data(), mgtBytes.size()), 0);

    // Track order override: parsing the .img bytes as cylinder-major puts cylinder 0 side 1 data
    // (file track 1 in .mgt order) where the .img actually stores cylinder 1 side 0
    std::vector<std::string> warnings;
    DiskImage* wrongOrder = mgtLoader.parse(imgBytes.data(), imgBytes.size(), TrackOrder::CylinderMajor, warnings);
    ASSERT_NE(wrongOrder, nullptr);
    DiskImage::Sector* misplaced = wrongOrder->getTrackForCylinderAndSide(0, 1)->getSector(0);
    EXPECT_EQ(misplaced->data[0], 1);           // Tagged cylinder 1
    EXPECT_EQ(misplaced->data[1], (0 << 4) | 1);// side 0, sector 1
    delete wrongOrder;

    // setTrackOrder() overrides the extension: loading the .img with a forced CylinderMajor order misplaces,
    // forcing SideMajor on the .mgt path name with .img content restores the right placement
    LoaderMGTCUT forced(_context, fixture("loaders/mgt/synthetic.img"));
    forced.setTrackOrder(TrackOrder::CylinderMajor);
    EXPECT_EQ(forced.effectiveOrder(fixture("loaders/mgt/synthetic.img")), TrackOrder::CylinderMajor);
    forced.setTrackOrder(TrackOrder::Auto);
    EXPECT_EQ(forced.effectiveOrder(fixture("loaders/mgt/synthetic.img")), TrackOrder::SideMajor);
    EXPECT_EQ(forced.effectiveOrder("x.mgt"), TrackOrder::CylinderMajor);

    // Offsets: .mgt interleaves sides, .img keeps them apart
    EXPECT_EQ(LoaderMGTCUT::trackOffset(80, 0, 1, TrackOrder::CylinderMajor), 5120u);
    EXPECT_EQ(LoaderMGTCUT::trackOffset(80, 1, 0, TrackOrder::CylinderMajor), 10240u);
    EXPECT_EQ(LoaderMGTCUT::trackOffset(80, 1, 0, TrackOrder::SideMajor), 5120u);
    EXPECT_EQ(LoaderMGTCUT::trackOffset(80, 0, 1, TrackOrder::SideMajor), 80u * 5120u);
    EXPECT_EQ(LoaderMGTCUT::trackOffset(40, 0, 1, TrackOrder::SideMajor), 40u * 5120u);

    delete fromMgt;
    delete fromImg;
}

TEST_F(LoaderMGT_Test, Format_PlusD_Fits)
{
    Spec spec = Spec::plusD();
    EXPECT_TRUE(spec.fits()) << "10 x 512 with gap3 = 0x18 must fit into a 6250-byte MFM track (" << spec.totalBytes() << " bytes)";
    EXPECT_EQ(spec.sectorCount(), 10u);
    EXPECT_LE(spec.totalBytes(), spec.trackLength);

    // A track formatted with the spec reindexes to 10 sectors numbered 1..10, N = 2, valid CRCs
    DiskImage image(1, 1);
    DiskImage::Track* track = image.getTrackForCylinderAndSide(0, 0);
    track->formatTrack(5, 0, spec);
    ASSERT_EQ(track->sectorCount(), 10u);
    for (uint8_t n = 1; n <= 10; n++)
    {
        DiskImage::Sector* sector = track->getSector(static_cast<uint8_t>(n - 1));
        ASSERT_NE(sector, nullptr) << "sector " << (int)n;
        EXPECT_EQ(sector->number(), n);
        EXPECT_EQ(sector->cylinder(), 5);
        EXPECT_EQ(sector->sizeCode(), 2);
        EXPECT_EQ(sector->dataSize, 512);
        EXPECT_TRUE(sector->hasData);
        EXPECT_TRUE(sector->isIDCRCValid());
        EXPECT_TRUE(sector->isDataCRCValid());
    }
    EXPECT_EQ(track->getSector(10), nullptr) << "no sector 11";
    EXPECT_FALSE(LoaderMGT::isPlusDGeometry(&image)) << "one cylinder, one side is not an MGT disk even with +D tracks";

    // Loaded fixture: same layout on every track, CRCs valid after the data copy
    LoaderMGT loader(_context, fixture("loaders/mgt/synthetic.mgt"));
    ASSERT_TRUE(loader.loadImage());
    DiskImage* loaded = loader.getImage();
    EXPECT_TRUE(LoaderMGT::isPlusDGeometry(loaded));
    for (uint8_t c = 0; c < 80; c++)
    {
        for (uint8_t s = 0; s < 2; s++)
        {
            DiskImage::Track* t = loaded->getTrackForCylinderAndSide(c, s);
            ASSERT_EQ(t->sectorCount(), 10u);
            ASSERT_EQ(t->rawSize(), spec.trackLength);
            EXPECT_EQ(t->encoding(), DiskImage::Encoding::MFM);
            for (size_t i = 0; i < 10; i++)
            {
                DiskImage::Sector& sector = t->sectors()[i];
                EXPECT_TRUE(sector.isIDCRCValid());
                EXPECT_TRUE(sector.isDataCRCValid());
                EXPECT_FALSE(sector.dirty);
            }
        }
    }
    delete loaded;
}

/// endregion </Detection / geometry>

/// region <Save>

TEST_F(LoaderMGT_Test, Save_RoundTrip)
{
    std::vector<uint8_t> mgtBytes = readFile(fixture("loaders/mgt/synthetic.mgt"));
    std::vector<uint8_t> imgBytes = readFile(fixture("loaders/mgt/synthetic.img"));
    ASSERT_EQ(mgtBytes.size(), 819200u);
    ASSERT_EQ(imgBytes.size(), 819200u);

    struct Case { const char* source; const char* target; const std::vector<uint8_t>* expected; };
    const Case cases[] = {
        { "loaders/mgt/synthetic.mgt", "roundtrip.mgt", &mgtBytes },   // .mgt -> .mgt
        { "loaders/mgt/synthetic.mgt", "roundtrip.img", &imgBytes },   // .mgt -> .img (reordered on save)
        { "loaders/mgt/synthetic.img", "roundtrip.img", &imgBytes },   // .img -> .img
        { "loaders/mgt/synthetic.img", "roundtrip.mgt", &mgtBytes },   // .img -> .mgt
    };

    for (const Case& c : cases)
    {
        std::string target = scratch(c.target);
        removeFile(target);

        LoaderMGT loader(_context, fixture(c.source));
        ASSERT_TRUE(loader.loadImage()) << c.source;
        DiskImage* image = loader.getImage();

        // Touch the image (write a sector, then write the original back) so that the save has something to clean
        {
            DiskImage::Track* track = image->getTrackForCylinderAndSide(0, 0);
            std::vector<uint8_t> original(track->getSector(0)->data, track->getSector(0)->data + 512);
            std::vector<uint8_t> modified(original);
            modified[100] ^= 0xFF;
            track->writeSectorData(0, modified.data(), modified.size());
            track->writeSectorData(0, original.data(), original.size());
        }
        ASSERT_TRUE(image->isDirty());

        ASSERT_TRUE(loader.writeImage(target)) << c.source << " -> " << c.target << ": " << join(loader.lastWarnings(), "; ");
        EXPECT_TRUE(loader.lastWarnings().empty());
        EXPECT_FALSE(image->isDirty());
        EXPECT_EQ(image->getFilePath(), target);

        std::vector<uint8_t> out = readFile(target);
        ASSERT_EQ(out.size(), c.expected->size()) << c.source << " -> " << c.target;
        EXPECT_EQ(std::memcmp(out.data(), c.expected->data(), out.size()), 0) << c.source << " -> " << c.target << " differs after round trip";

        removeFile(target);
        delete image;
    }

    // In-memory: serialize in both orders straight from one image, and the override wins over the extension
    LoaderMGT loader(_context, fixture("loaders/mgt/synthetic.mgt"));
    ASSERT_TRUE(loader.loadImage());
    DiskImage* image = loader.getImage();

    std::vector<uint8_t> out;
    std::vector<std::string> warnings;
    ASSERT_TRUE(loader.serialize(image, TrackOrder::CylinderMajor, out, warnings));
    EXPECT_EQ(out, mgtBytes);
    ASSERT_TRUE(loader.serialize(image, TrackOrder::SideMajor, out, warnings));
    EXPECT_EQ(out, imgBytes);

    std::string target = scratch("override.mgt");
    removeFile(target);
    loader.setTrackOrder(TrackOrder::SideMajor);
    ASSERT_TRUE(loader.writeImage(target));
    EXPECT_EQ(readFile(target), imgBytes) << "setTrackOrder(SideMajor) must win over the .mgt extension";
    removeFile(target);

    delete image;
}

TEST_F(LoaderMGT_Test, WriteImage_RefusesNonPlusDGeometry)
{
    std::string target = scratch("refused.mgt");

    // Default DiskImage = 16 x 256 TR-DOS tracks
    {
        removeFile(target);
        DiskImage image(80, 2);
        LoaderMGT loader(_context, target);
        loader.setImage(&image);

        std::string reason;
        EXPECT_FALSE(LoaderMGT::isPlusDGeometry(&image, &reason));
        EXPECT_FALSE(reason.empty());

        EXPECT_FALSE(loader.writeImage(target));
        ASSERT_FALSE(loader.lastWarnings().empty());
        EXPECT_NE(loader.lastWarnings().front().find("refused"), std::string::npos) << loader.lastWarnings().front();
        EXPECT_FALSE(FileHelper::FileExists(target)) << "nothing must be written";
    }

    // Right sectors but a single side
    {
        DiskImage image(80, 1, Spec::plusD());
        LoaderMGT loader(_context, target);
        loader.setImage(&image);
        EXPECT_FALSE(loader.writeImage(target));
        EXPECT_FALSE(loader.lastWarnings().empty());
        EXPECT_FALSE(FileHelper::FileExists(target));
    }

    // Right sectors but 41 cylinders
    {
        DiskImage image(41, 2, Spec::plusD());
        LoaderMGT loader(_context, target);
        loader.setImage(&image);
        EXPECT_FALSE(loader.writeImage(target));
        EXPECT_FALSE(FileHelper::FileExists(target));
    }

    // 9 x 512 (+3 layout) on one track of an otherwise valid image
    {
        DiskImage image(80, 2, Spec::plusD());
        EXPECT_TRUE(LoaderMGT::isPlusDGeometry(&image));
        image.getTrackForCylinderAndSide(17, 1)->formatTrack(17, 1, Spec::plus3());

        std::string reason;
        EXPECT_FALSE(LoaderMGT::isPlusDGeometry(&image, &reason));
        EXPECT_NE(reason.find("17"), std::string::npos) << reason;

        LoaderMGT loader(_context, target);
        loader.setImage(&image);
        EXPECT_FALSE(loader.writeImage(target));
        EXPECT_FALSE(FileHelper::FileExists(target));
        EXPECT_FALSE(image.isDirty()) << "a refused save leaves the dirty state alone";
    }

    // No image at all
    {
        LoaderMGT loader(_context, target);
        EXPECT_FALSE(loader.writeImage(target));
        EXPECT_FALSE(loader.lastWarnings().empty());
    }

    // A blank +D image saves fine (all zero) - proves the refusal above is about geometry, not content
    {
        removeFile(target);
        DiskImage image(80, 2, Spec::plusD());
        LoaderMGT loader(_context, target);
        loader.setImage(&image);
        ASSERT_TRUE(loader.writeImage(target)) << join(loader.lastWarnings(), "; ");
        std::vector<uint8_t> out = readFile(target);
        ASSERT_EQ(out.size(), 819200u);
        EXPECT_TRUE(std::all_of(out.begin(), out.end(), [](uint8_t b) { return b == 0; }));
        removeFile(target);
    }
}

/// endregion </Save>

/// region <Controller>

/// READ SECTOR on a +D track through the WD1793 returns the full 512-byte data field
TEST_F(LoaderMGT_Test, Wd1793_ReadSector_512)
{
    LoaderMGT loader(_context, fixture("loaders/mgt/synthetic.mgt"));
    ASSERT_TRUE(loader.loadImage());
    DiskImage* image = loader.getImage();

    auto readSector = [&](uint8_t cyl, uint8_t side, uint8_t number) -> std::vector<uint8_t>
    {
        WD1793CUT fdc(_context);
        fdc.getDrive()->insertDisk(image);
        fdc._beta128Register = WD1793CUT::BETA128_COMMAND_BITS::BETA_CMD_RESET;   // MFM (DENSITY bit clear)
        fdc._drive = 0;
        fdc.wakeUp();
        fdc._time = 1000;
        fdc.prolongFDDMotorRotation();
        fdc._trackRegister = cyl;
        fdc._selectedDrive->setTrack(cyl);
        fdc._sideUp = side != 0;
        fdc._sectorRegister = number;
        fdc._commandRegister = 0x80;
        fdc._lastDecodedCmd = WD1793::WD_CMD_READ_SECTOR;
        fdc.cmdReadSector(0x00);

        std::vector<uint8_t> read;
        for (size_t clk = 1000; clk < 1000 + 3'500'000 * 3 && fdc._state != WD1793::S_IDLE; clk += 100)
        {
            fdc._time = clk;
            fdc.process();
            if (fdc._beta128status & WD1793::DRQ) read.push_back(fdc.readDataRegister());
        }
        EXPECT_EQ(fdc._state, WD1793::S_IDLE) << "READ SECTOR did not finish within 3 seconds";
        EXPECT_FALSE(fdc._statusRegister & WD1793::WDS_NOTFOUND);
        EXPECT_FALSE(fdc._statusRegister & WD1793::WDS_CRCERR);
        fdc.getDrive()->ejectDisk();
        return read;
    };

    // Sector 10 (the last one on the track) on cylinder 3 side 0
    std::vector<uint8_t> data = readSector(3, 0, 10);
    ASSERT_EQ(data.size(), 512u);
    EXPECT_EQ(data, expectedSector(3, 0, 10));

    // Sector 1 on cylinder 79 side 1
    data = readSector(79, 1, 1);
    ASSERT_EQ(data.size(), 512u);
    EXPECT_EQ(data, expectedSector(79, 1, 1));

    // Sector 11 does not exist on a +D track
    {
        WD1793CUT fdc(_context);
        fdc.getDrive()->insertDisk(image);
        fdc._beta128Register = WD1793CUT::BETA128_COMMAND_BITS::BETA_CMD_RESET;
        fdc._drive = 0;
        fdc.wakeUp();
        fdc._time = 1000;
        fdc.prolongFDDMotorRotation();
        fdc._trackRegister = 3;
        fdc._selectedDrive->setTrack(3);
        fdc._sideUp = false;
        fdc._sectorRegister = 11;
        fdc._commandRegister = 0x80;
        fdc._lastDecodedCmd = WD1793::WD_CMD_READ_SECTOR;
        fdc.cmdReadSector(0x00);
        for (size_t clk = 1000; clk < 1000 + 3'500'000 * 3 && fdc._state != WD1793::S_IDLE; clk += 100)
        {
            fdc._time = clk;
            fdc.process();
            if (fdc._beta128status & WD1793::DRQ) fdc.readDataRegister();
        }
        EXPECT_EQ(fdc._state, WD1793::S_IDLE);
        EXPECT_TRUE(fdc._statusRegister & WD1793::WDS_NOTFOUND);
        fdc.getDrive()->ejectDisk();
    }

    delete image;
}

/// endregion </Controller>
