#include "loaders/disk/loader_hobeta.h"

#include <gtest/gtest.h>

#include <cstring>
#include <filesystem>
#include <vector>

#include <common/filehelper.h>
#include <common/stringhelper.h>

#include "_helpers/testpathhelper.h"
#include "emulator/cpu/core.h"
#include "emulator/emulatorcontext.h"
#include "emulator/io/fdc/diskimage.h"
#include "emulator/io/fdc/trdos.h"
#include "emulator/io/fdc/wd1793.h"
#include "loaders/disk/loader_scl.h"
#include "loaders/disk/loader_trd.h"

/// Hobeta ($-file) loader tests (docs/inprogress/2026-09-02-universal-track-model/loader-hobeta.md, section 4)
///
/// Fixtures: testdata/loaders/hobeta/hello.$C (CODE "hello", start 0x8000, length 700, 3 sectors) and
/// bad-checksum.$C (same file, corrupted checksum), generated by core/tests/emulator/io/fdc/tools/mgt_hobeta_generator.py

using Spec = DiskImage::TrackFormatSpec;

class LoaderHobeta_Test : public ::testing::Test
{
protected:
    EmulatorContext* _context = nullptr;
    CoreCUT* _core = nullptr;
    Z80* _z80 = nullptr;

protected:
    void SetUp() override
    {
        _context = new EmulatorContext(LoggerLevel::LogError);
        _context->pModuleLogger->TurnOffLoggingForAll();

        _core = new CoreCUT(_context);
        _z80 = new Z80(_context);
        _core->_z80 = _z80;
        _context->pCore = _core;
    }

    void TearDown() override
    {
        if (_context)
        {
            if (_context->pCore)
            {
                _core->_z80 = nullptr;
                delete _z80;
                _context->pCore = nullptr;
                delete _core;
            }
            delete _context;
        }
    }

    static std::vector<uint8_t> readFile(const std::string& path)
    {
        std::vector<uint8_t> result;
        if (FileHelper::FileExists(path))
        {
            size_t size = FileHelper::GetFileSize(path);
            result.resize(size);
            if (size > 0) FileHelper::ReadFileToBuffer(path, result.data(), size);
        }
        return result;
    }

    static void removeFile(const std::string& path)
    {
        std::error_code ec;
        std::filesystem::remove(path, ec);
    }

    static std::string join(const std::vector<std::string>& items, const char* separator = "; ")
    {
        std::string result;
        for (const std::string& item : items)
        {
            if (!result.empty()) result += separator;
            result += item;
        }
        return result;
    }

    static std::string fixture(const char* name) { return TestPathHelper::GetTestDataPath(name); }
    static std::string scratch(const char* name) { return TestPathHelper::GetTestScratchPath(name); }

    static TRDVolumeInfo* volumeOf(DiskImage* image)
    {
        return reinterpret_cast<TRDVolumeInfo*>(image->getTrackForCylinderAndSide(0, 0)->getSector(TRD_VOLUME_SECTOR)->data);
    }

    /// Raw bytes of every track, for "image untouched" comparisons
    static std::vector<std::vector<uint8_t>> snapshot(DiskImage* image)
    {
        std::vector<std::vector<uint8_t>> result;
        const size_t trackCount = static_cast<size_t>(image->getCylinders()) * image->getSides();
        for (size_t t = 0; t < trackCount; t++)
        {
            DiskImage::Track* track = image->getTrack(static_cast<uint8_t>(t));
            result.emplace_back(track->rawData(), track->rawData() + track->rawSize());
        }
        return result;
    }

    /// Blank DS80 TR-DOS disk, as LoaderSCL / LoaderHobeta build it
    DiskImage* blankTrdos()
    {
        DiskImage* image = new DiskImage(80, 2);
        LoaderTRD trd(_context, "");
        EXPECT_TRUE(trd.format(image));
        image->markClean();
        return image;
    }

    /// Expected sector chain content: the fixture body starting at sector n of the file
    static void expectFileOnDisk(DiskImage* image, const TRDOSDirectoryEntry& entry, const std::vector<uint8_t>& body)
    {
        ASSERT_EQ(body.size(), static_cast<size_t>(entry.SizeInSectors) * TRD_SECTORS_SIZE_BYTES);
        uint16_t locator = static_cast<uint16_t>(entry.StartTrack * TRD_SECTORS_PER_TRACK + entry.StartSector);
        for (size_t n = 0; n < entry.SizeInSectors; n++, locator++)
        {
            DiskImage::Track* track = image->getTrack(static_cast<uint8_t>(locator / TRD_SECTORS_PER_TRACK));
            DiskImage::Sector* sector = track->getSector(static_cast<uint8_t>(locator % TRD_SECTORS_PER_TRACK));
            ASSERT_NE(sector, nullptr) << "locator " << locator;
            ASSERT_EQ(sector->dataSize, TRD_SECTORS_SIZE_BYTES);
            EXPECT_TRUE(sector->isDataCRCValid()) << "locator " << locator;
            EXPECT_EQ(std::memcmp(sector->data, body.data() + n * TRD_SECTORS_SIZE_BYTES, TRD_SECTORS_SIZE_BYTES), 0)
                << "file sector " << n << " at TR-DOS locator " << locator;
        }
    }

    /// READ SECTOR through the WD1793 (MFM, DENSITY bit clear), 3-second T-state budget
    std::vector<uint8_t> readThroughController(DiskImage* image, uint8_t cyl, uint8_t side, uint8_t number)
    {
        WD1793CUT fdc(_context);
        fdc.getDrive()->insertDisk(image);
        fdc._beta128Register = WD1793CUT::BETA128_COMMAND_BITS::BETA_CMD_RESET;
        fdc._drive = 0;
        fdc.wakeUp();
        fdc._time = 1000;
        fdc.prolongFDDMotorRotation();
        fdc._trackRegister = cyl;
        fdc._selectedDrive->setTrack(cyl);
        fdc._sideUp = side != 0;
        fdc._sectorRegister = number;
        fdc._commandRegister = 0x80;
        fdc._lastDecodedCmd = WD1793::WD_CMD_READ_SECTOR;
        fdc.cmdReadSector(0x00);

        std::vector<uint8_t> read;
        for (size_t clk = 1000; clk < 1000 + 3'500'000 * 3 && fdc._state != WD1793::S_IDLE; clk += 100)
        {
            fdc._time = clk;
            fdc.process();
            if (fdc._beta128status & WD1793::DRQ) read.push_back(fdc.readDataRegister());
        }
        EXPECT_EQ(fdc._state, WD1793::S_IDLE) << "READ SECTOR did not finish within 3 seconds";
        EXPECT_FALSE(fdc._statusRegister & WD1793::WDS_NOTFOUND);
        fdc.getDrive()->ejectDisk();
        return read;
    }
};

/// region <Detection>

TEST_F(LoaderHobeta_Test, Detect_Checksum)
{
    std::vector<uint8_t> good = readFile(fixture("loaders/hobeta/hello.$C"));
    std::vector<uint8_t> bad = readFile(fixture("loaders/hobeta/bad-checksum.$C"));
    ASSERT_EQ(good.size(), 17u + 3 * 256);
    ASSERT_EQ(bad.size(), good.size());

    // Checksum formula: sum(header[i] * 257 + i), i = 0..14, 16-bit
    uint16_t expected = 0;
    for (size_t i = 0; i < 15; i++) expected = static_cast<uint16_t>(expected + good[i] * 257 + i);
    EXPECT_EQ(LoaderHobeta::computeChecksum(good.data()), expected);
    EXPECT_EQ(static_cast<uint16_t>(good[15] | (good[16] << 8)), expected);

    EXPECT_TRUE(LoaderHobeta::detect(good.data(), good.size()));
    EXPECT_FALSE(LoaderHobeta::detect(bad.data(), bad.size()));
    EXPECT_FALSE(LoaderHobeta::detect(good.data(), good.size() - 1)) << "size must match 17 + sectors * 256";
    EXPECT_FALSE(LoaderHobeta::detect(good.data(), 16));
    EXPECT_FALSE(LoaderHobeta::detect(nullptr, 0));

    // Decoded header
    LoaderHobeta::Header header;
    std::vector<std::string> warnings;
    ASSERT_TRUE(LoaderHobeta::parseHeader(good.data(), good.size(), header, warnings));
    EXPECT_EQ(header.nameString(), "hello   ");
    EXPECT_EQ(header.type, 'C');
    EXPECT_EQ(header.start, 0x8000);
    EXPECT_EQ(header.length, 700);
    EXPECT_EQ(header.reserved, 0);
    EXPECT_EQ(header.sectors, 3);
    EXPECT_EQ(header.checksum, expected);
    EXPECT_TRUE(warnings.empty());

    // Corrupted checksum is reported as such
    EXPECT_FALSE(LoaderHobeta::parseHeader(bad.data(), bad.size(), header, warnings));
    ASSERT_FALSE(warnings.empty());
    EXPECT_NE(warnings.front().find("checksum"), std::string::npos) << warnings.front();

    // serializeHeader reproduces the file header byte for byte
    uint8_t encoded[17];
    LoaderHobeta::serializeHeader(header, encoded);
    EXPECT_EQ(std::memcmp(encoded, good.data(), 17), 0);

    // Through the loader
    LoaderHobeta goodLoader(_context, fixture("loaders/hobeta/hello.$C"));
    EXPECT_TRUE(goodLoader.loadFile());
    EXPECT_TRUE(goodLoader.isFileLoaded());
    EXPECT_EQ(goodLoader.getFileData().size(), 3u * 256);
    EXPECT_EQ(std::memcmp(goodLoader.getFileData().data(), good.data() + 17, 3 * 256), 0);

    LoaderHobeta badLoader(_context, fixture("loaders/hobeta/bad-checksum.$C"));
    EXPECT_FALSE(badLoader.loadFile());
    EXPECT_FALSE(badLoader.isFileLoaded());
    EXPECT_FALSE(badLoader.lastWarnings().empty());
    EXPECT_FALSE(badLoader.loadImage());
    EXPECT_EQ(badLoader.getImage(), nullptr);

    LoaderHobeta missing(_context, fixture("loaders/hobeta/none.$C"));
    EXPECT_FALSE(missing.loadImage());
    EXPECT_FALSE(missing.lastWarnings().empty());
}

/// endregion </Detection>

/// region <Inject>

TEST_F(LoaderHobeta_Test, Inject_IntoBlankDisk)
{
    std::vector<uint8_t> file = readFile(fixture("loaders/hobeta/hello.$C"));
    std::vector<uint8_t> body(file.begin() + 17, file.end());

    LoaderHobeta loader(_context, fixture("loaders/hobeta/hello.$C"));
    ASSERT_TRUE(loader.loadImage()) << join(loader.lastWarnings(), "; ");
    DiskImage* image = loader.getImage();
    ASSERT_NE(image, nullptr);
    EXPECT_EQ(image->getCylinders(), 80);
    EXPECT_EQ(image->getSides(), 2);
    EXPECT_TRUE(image->getLoaded());
    EXPECT_FALSE(image->isDirty()) << "a freshly built disk has nothing to save back";
    EXPECT_TRUE(LoaderTRD::isTrdosGeometry(image));

    // Catalog entry
    std::vector<LoaderHobeta::CatalogEntry> files = LoaderHobeta::listFiles(image);
    ASSERT_EQ(files.size(), 1u);
    EXPECT_EQ(files[0].index, 0);
    const TRDOSDirectoryEntry& entry = files[0].entry;
    EXPECT_EQ(std::string(entry.Name, 8), "hello   ");
    EXPECT_EQ(entry.Type, 'C');
    EXPECT_EQ(entry.Start, 0x8000);
    EXPECT_EQ(entry.Length, 700);
    EXPECT_EQ(entry.SizeInSectors, 3);
    EXPECT_EQ(entry.StartTrack, 1) << "first free track of a blank disk";
    EXPECT_EQ(entry.StartSector, 0);

    // Same entry as seen in the raw catalog sector 1
    DiskImage::Track* track0 = image->getTrackForCylinderAndSide(0, 0);
    DiskImage::Sector* catalog = track0->getSector(0);
    EXPECT_EQ(std::memcmp(catalog->data, &entry, sizeof(TRDOSDirectoryEntry)), 0);
    EXPECT_EQ(catalog->data[16], 0) << "next catalog slot stays empty";
    EXPECT_TRUE(catalog->isDataCRCValid());

    // Volume sector counters
    TRDVolumeInfo* volume = volumeOf(image);
    EXPECT_EQ(volume->trDOSSignature, TRD_SIGNATURE);
    EXPECT_EQ(volume->fileCount, 1);
    EXPECT_EQ(volume->deletedFileCount, 0);
    EXPECT_EQ(volume->freeSectorCount, TRD_FREE_SECTORS_ON_DS_80_EMPTY_DISK - 3);
    EXPECT_EQ(volume->firstFreeTrack, 1);
    EXPECT_EQ(volume->firstFreeSector, 3);
    EXPECT_TRUE(track0->getSector(TRD_VOLUME_SECTOR)->isDataCRCValid());

    // Data readable via getSector (TR-DOS track 1 = cylinder 0 side 1, sectors 1..3)
    expectFileOnDisk(image, entry, body);
    DiskImage::Track* track1 = image->getTrackForCylinderAndSide(0, 1);
    EXPECT_EQ(track1, image->getTrack(1));
    EXPECT_EQ(std::memcmp(track1->getSector(0)->data, body.data(), 256), 0);
    EXPECT_EQ(std::memcmp(track1->getSector(2)->data, body.data() + 512, 256), 0);

    // Untouched sector after the file is still blank
    bool blank = true;
    for (size_t i = 0; i < 256; i++) blank = blank && track1->getSector(3)->data[i] == 0;
    EXPECT_TRUE(blank);

    // ... and through the WD1793
    for (uint8_t n = 0; n < 3; n++)
    {
        std::vector<uint8_t> read = readThroughController(image, 0, 1, static_cast<uint8_t>(n + 1));
        ASSERT_EQ(read.size(), 256u) << "sector " << (int)(n + 1);
        EXPECT_EQ(std::memcmp(read.data(), body.data() + n * 256, 256), 0) << "sector " << (int)(n + 1);
    }

    // The image validates as a TR-DOS disk
    LoaderTRD trd(_context, "");
    TRDValidationReport report;
    EXPECT_TRUE(trd.validateTRDOSImage(image, report));

    delete image;
}

TEST_F(LoaderHobeta_Test, Inject_IntoExistingDisk_AppendsAfterLastFile)
{
    std::vector<uint8_t> file = readFile(fixture("loaders/hobeta/hello.$C"));
    std::vector<uint8_t> body(file.begin() + 17, file.end());

    // insult.scl: 4 files, 731 sectors
    LoaderSCL scl(_context, fixture("loaders/scl/insult.scl"));
    ASSERT_TRUE(scl.loadImage());
    DiskImage* image = scl.getImage();
    ASSERT_NE(image, nullptr);
    image->markClean();

    TRDVolumeInfo* volume = volumeOf(image);
    const uint8_t prevFileCount = volume->fileCount;
    const uint16_t prevFree = volume->freeSectorCount;
    const uint8_t prevFirstFreeTrack = volume->firstFreeTrack;
    const uint8_t prevFirstFreeSector = volume->firstFreeSector;
    ASSERT_EQ(prevFileCount, 4);
    ASSERT_EQ(prevFree, TRD_FREE_SECTORS_ON_DS_80_EMPTY_DISK - 731);
    ASSERT_EQ(prevFirstFreeTrack * 16 + prevFirstFreeSector, 16 + 731);

    std::vector<LoaderHobeta::CatalogEntry> before = LoaderHobeta::listFiles(image);
    ASSERT_EQ(before.size(), 4u);
    const TRDOSDirectoryEntry last = before.back().entry;
    EXPECT_EQ(std::string(last.Name, 8), "boot    ");
    EXPECT_EQ(last.StartTrack * 16 + last.StartSector + last.SizeInSectors, prevFirstFreeTrack * 16 + prevFirstFreeSector)
        << "the last file ends exactly at the first free sector";

    LoaderHobeta loader(_context, fixture("loaders/hobeta/hello.$C"));
    TRDOSDirectoryEntry placed;
    ASSERT_TRUE(loader.injectInto(image, &placed)) << join(loader.lastWarnings(), "; ");
    EXPECT_TRUE(loader.lastWarnings().empty());
    EXPECT_EQ(loader.getImage(), nullptr) << "injectInto does not adopt the image";

    // Placement: right after the previous last file, as recorded in the volume sector
    EXPECT_EQ(placed.StartTrack, prevFirstFreeTrack);
    EXPECT_EQ(placed.StartSector, prevFirstFreeSector);
    EXPECT_EQ(std::string(placed.Name, 8), "hello   ");
    EXPECT_EQ(placed.SizeInSectors, 3);

    // Catalog: appended as entry 4
    std::vector<LoaderHobeta::CatalogEntry> after = LoaderHobeta::listFiles(image);
    ASSERT_EQ(after.size(), 5u);
    EXPECT_EQ(after[4].index, 4);
    EXPECT_EQ(std::memcmp(&after[4].entry, &placed, sizeof(TRDOSDirectoryEntry)), 0);
    for (size_t i = 0; i < 4; i++)
    {
        EXPECT_EQ(std::memcmp(&after[i].entry, &before[i].entry, sizeof(TRDOSDirectoryEntry)), 0) << "existing entry " << i << " unchanged";
    }

    // Volume sector counters
    volume = volumeOf(image);
    EXPECT_EQ(volume->fileCount, prevFileCount + 1);
    EXPECT_EQ(volume->freeSectorCount, prevFree - 3);
    EXPECT_EQ((volume->firstFreeTrack * 16 + volume->firstFreeSector), prevFirstFreeTrack * 16 + prevFirstFreeSector + 3);

    // Body in the chain, CRCs valid, the disk is now dirty (it has unsaved changes)
    expectFileOnDisk(image, placed, body);
    EXPECT_TRUE(image->isDirty());
    EXPECT_TRUE(image->getTrackForCylinderAndSide(0, 0)->isDirty());
    EXPECT_TRUE(image->getTrack(placed.StartTrack)->isDirty());

    // Still a valid TR-DOS disk that can be written back as TRD
    LoaderTRD trd(_context, "");
    TRDValidationReport report;
    EXPECT_TRUE(trd.validateTRDOSImage(image, report));

    // The first sector of the injected file is readable through the controller
    // (TR-DOS track t = cylinder t / 2, side t % 2)
    std::vector<uint8_t> read = readThroughController(image, static_cast<uint8_t>(placed.StartTrack / 2),
                                                      static_cast<uint8_t>(placed.StartTrack % 2),
                                                      static_cast<uint8_t>(placed.StartSector + 1));
    ASSERT_EQ(read.size(), 256u);
    EXPECT_EQ(std::memcmp(read.data(), body.data(), 256), 0);

    delete image;
}

TEST_F(LoaderHobeta_Test, Inject_NotEnoughSpace)
{
    // Free space below the 3 sectors the file needs
    {
        DiskImage* image = blankTrdos();
        TRDVolumeInfo* volume = volumeOf(image);
        volume->freeSectorCount = 2;
        image->getTrackForCylinderAndSide(0, 0)->getSector(TRD_VOLUME_SECTOR)->recalculateDataCRC();
        image->markClean();

        std::vector<std::vector<uint8_t>> before = snapshot(image);

        LoaderHobeta loader(_context, fixture("loaders/hobeta/hello.$C"));
        TRDOSDirectoryEntry placed;
        EXPECT_FALSE(loader.injectInto(image, &placed));
        ASSERT_FALSE(loader.lastWarnings().empty());
        EXPECT_NE(loader.lastWarnings().front().find("refused"), std::string::npos) << loader.lastWarnings().front();

        EXPECT_FALSE(image->isDirty()) << "dirty flag unchanged";
        EXPECT_EQ(snapshot(image), before) << "image untouched";
        EXPECT_EQ(volumeOf(image)->fileCount, 0);
        EXPECT_EQ(volumeOf(image)->freeSectorCount, 2);
        EXPECT_TRUE(LoaderHobeta::listFiles(image).empty());
        delete image;
    }

    // Exactly enough space is accepted
    {
        DiskImage* image = blankTrdos();
        volumeOf(image)->freeSectorCount = 3;
        image->getTrackForCylinderAndSide(0, 0)->getSector(TRD_VOLUME_SECTOR)->recalculateDataCRC();
        image->markClean();

        LoaderHobeta loader(_context, fixture("loaders/hobeta/hello.$C"));
        EXPECT_TRUE(loader.injectInto(image)) << join(loader.lastWarnings(), "; ");
        EXPECT_EQ(volumeOf(image)->freeSectorCount, 0);
        EXPECT_TRUE(image->isDirty());
        delete image;
    }

    // Catalog full (128 files)
    {
        DiskImage* image = blankTrdos();
        volumeOf(image)->fileCount = TRD_MAX_FILES;
        image->getTrackForCylinderAndSide(0, 0)->getSector(TRD_VOLUME_SECTOR)->recalculateDataCRC();
        image->markClean();
        std::vector<std::vector<uint8_t>> before = snapshot(image);

        LoaderHobeta loader(_context, fixture("loaders/hobeta/hello.$C"));
        EXPECT_FALSE(loader.injectInto(image));
        ASSERT_FALSE(loader.lastWarnings().empty());
        EXPECT_NE(loader.lastWarnings().front().find("full"), std::string::npos) << loader.lastWarnings().front();
        EXPECT_FALSE(image->isDirty());
        EXPECT_EQ(snapshot(image), before);
        delete image;
    }

    // First free sector points past the end of the disk (chain would leave the geometry)
    {
        DiskImage* image = blankTrdos();
        volumeOf(image)->firstFreeTrack = 159;
        volumeOf(image)->firstFreeSector = 14;
        image->getTrackForCylinderAndSide(0, 0)->getSector(TRD_VOLUME_SECTOR)->recalculateDataCRC();
        image->markClean();
        std::vector<std::vector<uint8_t>> before = snapshot(image);

        LoaderHobeta loader(_context, fixture("loaders/hobeta/hello.$C"));
        EXPECT_FALSE(loader.injectInto(image));
        EXPECT_FALSE(loader.lastWarnings().empty());
        EXPECT_FALSE(image->isDirty());
        EXPECT_EQ(snapshot(image), before);
        delete image;
    }

    // Not a TR-DOS disk at all: +D geometry on every track
    {
        DiskImage image(80, 2, Spec::plusD());
        std::vector<std::vector<uint8_t>> before = snapshot(&image);

        LoaderHobeta loader(_context, fixture("loaders/hobeta/hello.$C"));
        EXPECT_FALSE(loader.injectInto(&image));
        ASSERT_FALSE(loader.lastWarnings().empty());
        EXPECT_NE(loader.lastWarnings().front().find("TR-DOS"), std::string::npos) << loader.lastWarnings().front();
        EXPECT_FALSE(image.isDirty());
        EXPECT_EQ(snapshot(&image), before);
        EXPECT_TRUE(LoaderHobeta::listFiles(&image).empty());
    }

    // TR-DOS system track, but the file would land on a track that is not TR-DOS (16 x 256)
    {
        DiskImage* image = blankTrdos();
        image->getTrack(1)->formatTrack(0, 1, Spec::plusD());   // TR-DOS track 1 = cylinder 0 side 1
        image->markClean();
        std::vector<std::vector<uint8_t>> before = snapshot(image);

        LoaderHobeta loader(_context, fixture("loaders/hobeta/hello.$C"));
        EXPECT_FALSE(loader.injectInto(image));
        ASSERT_FALSE(loader.lastWarnings().empty());
        EXPECT_NE(loader.lastWarnings().front().find("track 1"), std::string::npos) << loader.lastWarnings().front();
        EXPECT_FALSE(image->isDirty());
        EXPECT_EQ(snapshot(image), before);
        delete image;
    }
}

/// endregion </Inject>

/// region <Export>

TEST_F(LoaderHobeta_Test, Export_RoundTrip)
{
    std::vector<uint8_t> original = readFile(fixture("loaders/hobeta/hello.$C"));
    ASSERT_EQ(original.size(), 785u);

    // inject (blank disk) -> export by default selection (first file)
    {
        std::string target = scratch("hello-export.$C");
        removeFile(target);

        LoaderHobeta loader(_context, fixture("loaders/hobeta/hello.$C"));
        ASSERT_TRUE(loader.loadImage());
        DiskImage* image = loader.getImage();

        ASSERT_TRUE(loader.writeImage(target)) << join(loader.lastWarnings(), "; ");
        EXPECT_TRUE(loader.lastWarnings().empty());
        EXPECT_EQ(readFile(target), original) << "exported $-file must be byte-identical";
        EXPECT_FALSE(image->isDirty());

        // Selection by name and by catalog slot give the same result
        removeFile(target);
        loader.setExportName("hello");
        ASSERT_TRUE(loader.writeImage(target));
        EXPECT_EQ(readFile(target), original);

        removeFile(target);
        loader.setExportEntry(0);
        ASSERT_TRUE(loader.writeImage(target));
        EXPECT_EQ(readFile(target), original);

        // Unknown selections are refused, nothing is written
        removeFile(target);
        loader.setExportEntry(1);
        EXPECT_FALSE(loader.writeImage(target));
        EXPECT_FALSE(loader.lastWarnings().empty());
        EXPECT_FALSE(FileHelper::FileExists(target));

        loader.setExportEntry(-1);
        loader.setExportName("nothere");
        EXPECT_FALSE(loader.writeImage(target));
        EXPECT_FALSE(FileHelper::FileExists(target));

        removeFile(target);
        delete image;
    }

    // inject into an existing disk -> export the injected file with a *different* loader instance
    // (header rebuilt from the catalog entry alone) and by name from the same instance
    {
        std::string target = scratch("hello-export2.$C");
        removeFile(target);

        LoaderSCL scl(_context, fixture("loaders/scl/insult.scl"));
        ASSERT_TRUE(scl.loadImage());
        DiskImage* image = scl.getImage();

        LoaderHobeta injector(_context, fixture("loaders/hobeta/hello.$C"));
        TRDOSDirectoryEntry placed;
        ASSERT_TRUE(injector.injectInto(image, &placed));

        LoaderHobeta exporter(_context, target);
        exporter.setImage(image);
        exporter.setExportName("hello");
        ASSERT_TRUE(exporter.writeImage()) << join(exporter.lastWarnings(), "; ");
        EXPECT_EQ(readFile(target), original);

        removeFile(target);
        exporter.setExportName("");
        exporter.setExportEntry(4);
        ASSERT_TRUE(exporter.writeImage(target));
        EXPECT_EQ(readFile(target), original);

        // In-memory export of a pre-existing SCL file: header fields come from the catalog, body from the chain
        std::vector<LoaderHobeta::CatalogEntry> files = LoaderHobeta::listFiles(image);
        ASSERT_EQ(files.size(), 5u);
        std::vector<uint8_t> out;
        std::vector<std::string> warnings;
        ASSERT_TRUE(LoaderHobeta::exportFile(image, files[3].entry, 0, out, warnings));
        ASSERT_EQ(out.size(), 17u + files[3].entry.SizeInSectors * 256u);
        EXPECT_TRUE(LoaderHobeta::detect(out.data(), out.size())) << "exported header carries a valid checksum";
        EXPECT_EQ(std::string(reinterpret_cast<const char*>(out.data()), 8), "boot    ");
        EXPECT_EQ(out[8], 'B');
        EXPECT_EQ(out[14], files[3].entry.SizeInSectors);
        uint16_t locator = static_cast<uint16_t>(files[3].entry.StartTrack * 16 + files[3].entry.StartSector);
        EXPECT_EQ(std::memcmp(out.data() + 17, image->getTrack(static_cast<uint8_t>(locator / 16))->getSector(locator % 16)->data, 256), 0);

        removeFile(target);
        delete image;
    }

    // Export with no image / from a non-TR-DOS image is refused
    {
        std::string target = scratch("hello-export3.$C");
        removeFile(target);

        LoaderHobeta empty(_context, target);
        EXPECT_FALSE(empty.writeImage());
        EXPECT_FALSE(empty.lastWarnings().empty());

        DiskImage plusD(80, 2, Spec::plusD());
        empty.setImage(&plusD);
        EXPECT_FALSE(empty.writeImage());
        EXPECT_FALSE(FileHelper::FileExists(target));
    }
}

/// endregion </Export>
