/// @file timetravelmanager_regeneratewrites_test.cpp
/// @brief A recorded frame's memory writes, regenerated by replaying it
/// (TimeTravelController::RegenerateFrameWrites), equal the write journal's
/// records of that frame: time, address, value, PC and physical page, in
/// order. The premise of the write journal as a derived index (TTD v2,
/// Phase 3, Step 7; experiment E7's exactness check).
///
/// Boots a machine and replays every recorded frame: slower than the 50 ms
/// guideline, one check of a session-wide property.

#include <gtest/gtest.h>

#include <filesystem>
#include <fstream>
#include <string>
#include <vector>

#include "_helpers/ttdwriterecords.h"
#include "_helpers/emulatortesthelper.h"
#include "_helpers/gsslot.h"
#include "_helpers/soundcardscope.h"
#include "_helpers/testpathhelper.h"
#include "base/featuremanager.h"
#include "debugger/ttd/timetravelcontroller.h"
#include "debugger/ttd/ttdfileinfo.h"
#include "debugger/ttd/ttdwritejournal.h"
#include "emulator/emulator.h"
#include "emulator/emulatorcontext.h"
#include "emulator/memory/memory.h"

namespace
{
class TimeTravelManager_RegenerateWrites_Test : public ::testing::Test
{
protected:
    SoundCardScope _soundCards;   // the fixtures were recorded on the shipped configs
    Emulator* _emulator = nullptr;
    ttd::TimeTravelController* _ttd = nullptr;

    void StartMachine(const std::string& model)
    {
        _emulator = EmulatorTestHelper::CreateStandardEmulator(model, LoggerLevel::LogError);
        ASSERT_NE(_emulator, nullptr);
        _emulator->GetFeatureManager()->setFeature(Features::kDebugMode, true);
        _emulator->GetFeatureManager()->setFeature(Features::kTimeTravel, true);
        _emulator->GetContext()->pMemory->UpdateFeatureCache();
        _ttd = _emulator->GetContext()->pTimeTravelController;
    }

    void TearDown() override
    {
        if (_emulator)
            EmulatorTestHelper::CleanupEmulator(_emulator);
    }

    /// Every @p step-th frame but the last (it has no recorded end):
    /// regenerated writes equal the journal's memory records between its
    /// checkpoint and the next
    void ExpectFramesRegenerate(size_t step, size_t& writes)
    {
        const std::vector<ttd::TTDWriteRecord> journal = ttdtest::WriteRecords(*_ttd);
        ASSERT_FALSE(journal.empty()) << "the journal holds the session's writes";
        size_t seq = 0;
        std::vector<ttd::TTDSearchResult> hits;
        for (size_t i = 0; i + 1 < _ttd->GetCheckpointCount(); ++i)
        {
            // A frame runs from where its checkpoint's CPU stood (the last
            // instruction of the frame before ends past its end) to where
            // the next one's stands; a write at the last T-state of that
            // instruction belongs to it: (from, to]
            const auto at = [this](size_t index) {
                const ttd::TTDCheckpoint* cp = _ttd->GetCheckpoint(index);
                const uint64_t units = _ttd->FrameSpan() / _emulator->GetContext()->config.frame;
                return _ttd->GlobalT(cp->time) + ttd::GetChipsetCpuTInFrame(cp->chipset) * units;
            };
            const uint64_t from = at(i);
            const uint64_t to = at(i + 1);
            std::vector<ttd::TTDWriteRecord> recorded;
            for (; seq < journal.size() && journal[seq].globalT <= to; ++seq)
                if (!journal[seq].isIo && journal[seq].globalT > from)
                    recorded.push_back(journal[seq]);

            if (i % step)
                continue;
            const uint64_t frame = _ttd->GetCheckpoint(i)->time.frame;
            ASSERT_TRUE(_ttd->RegenerateFrameWrites(frame, hits)) << "frame " << frame;
            ASSERT_EQ(hits.size(), recorded.size()) << "frame " << frame;
            for (size_t k = 0; k < hits.size(); ++k)
            {
                const ttd::TTDWriteRecord& r = recorded[k];
                const ttd::TTDSearchResult& h = hits[k];
                ASSERT_EQ(_ttd->GlobalT(h.time), static_cast<uint64_t>(r.globalT)) << "frame " << frame << " write " << k;
                ASSERT_EQ(h.addr, r.addr) << "frame " << frame << " write " << k;
                ASSERT_EQ(h.value, r.value) << "frame " << frame << " write " << k;
                ASSERT_EQ(h.pc, r.m1pc) << "frame " << frame << " write " << k;
                ASSERT_EQ(static_cast<uint8_t>(h.physPage), r.physPage) << "frame " << frame << " write " << k;
            }
            writes += hits.size();
        }
    }
};
}  // namespace

TEST_F(TimeTravelManager_RegenerateWrites_Test, ALiveRecordingsFramesRegenerateTheirWrites)
{
    ASSERT_NO_FATAL_FAILURE(StartMachine("PENTAGON"));
    _ttd->SetEnableWriteJournal(true);
    ASSERT_TRUE(_ttd->StartRecording());
    _emulator->RunNFrames(40, /*skipBreakpoints=*/true);   // the ROM's boot: RAM test, system variables
    _ttd->StopRecording();
    size_t writes = 0;
    ASSERT_NO_FATAL_FAILURE(ExpectFramesRegenerate(1, writes));
    EXPECT_GT(writes, 10000u) << "the boot writes memory";
}

TEST_F(TimeTravelManager_RegenerateWrites_Test, ARecordedSessionWithKeysRegeneratesItsWrites)
{
    const std::filesystem::path file = TestPathHelper::FindProjectRoot() / "testdata/ttd/port-journals/engine/dizzyx.ttd";
    ttd::TTDFileInfo info;
    std::string err;
    ASSERT_TRUE(ttd::ReadTTDFileInfo(file.string(), info, err)) << err;
    ASSERT_NO_FATAL_FAILURE(StartMachine(info.machine.model));
    ASSERT_TRUE(FitGeneralSoundCard(_emulator->GetContext()->pSoundManager, info.machine.generalSound));
    std::ifstream in(file, std::ios::binary);
    ASSERT_TRUE(_ttd->DeserializeSession(in, err)) << err;
    ASSERT_GT(_ttd->GetInputJournal().Size(), 0u) << "the session has key presses";
    size_t writes = 0;
    ASSERT_NO_FATAL_FAILURE(ExpectFramesRegenerate(8, writes));   // every 8th frame: 0.15 s
    EXPECT_GT(writes, 0u);
}
