// zxtime (testdata/machines/sprinter/zx-timing): the Spectrum mode's timing measured by a Spectrum program,
// run the way a Sprinter owner runs it (tdd-zx-mode.md phases Z1 and Z3, T-ZX-9):
//   - the committed .trd / .tap / .sym are what the source builds (no drift); UNREAL_ZXTIME_EXPORT=1 writes them;
//   - BIOS 3.06's own ZX mode (ESC at the boot prompt, the default Pentagon timing) runs it from a TR-DOS floppy;
//   - on the owner's system disk (UNREAL_SPRINTER_HDD) each launcher mode (SP, P128, P512, SC256, ORIGIN) runs
//     it and the results go into the timing table of tdd-zx-mode.md, next to MAME's.

#include "stdafx.h"
#include "pch.h"

#include "sprinterzxsession.h"

#include <array>
#include <cstdio>
#include <fstream>
#include <map>

#include "_helpers/zxprogramfiles.h"
#include "debugger/assembler/z80textassembler.h"
#include "emulator/io/fdc/wd1793.h"
#include "base/featuremanager.h"
#include "emulator/io/tape/tape.h"
#include "emulator/memory/sprinter/sprinterwaits.h"

namespace
{
constexpr uint16_t kOrg = 32768;

std::string ZxTimePath(const std::string& file)
{
    return (TestPathHelper::FindProjectRoot() / "testdata" / "machines" / "sprinter" / "zx-timing" / file).make_preferred().string();
}

struct ZxTimeProgram
{
    AsmResult asmResult;
    std::vector<uint8_t> bytes;

    uint16_t Sym(const char* name) const
    {
        auto it = asmResult.symbols.find(name);
        EXPECT_NE(it, asmResult.symbols.end()) << name;
        return it == asmResult.symbols.end() ? 0 : static_cast<uint16_t>(it->second);
    }
};

ZxTimeProgram BuildZxTime()
{
    ZxTimeProgram p;
    Z80TextAssembler assembler;
    p.asmResult = assembler.Assemble(ZxProgramFiles::ReadText(ZxTimePath("zxtime.asm")), kOrg);
    if (!p.asmResult.ok)
        ADD_FAILURE() << p.asmResult.error.line << ": " << p.asmResult.error.message << " | " << p.asmResult.error.sourceLine;
    else
        p.bytes = p.asmResult.bytes;
    return p;
}

const char* kHeading = "; zxtime symbols (generated by sprinterzxtiming_test.cpp)";

/// What zxtime leaves in memory (its outputs block)
struct ZxTimeResult
{
    bool done = false;
    uint32_t passes = 0;
    uint32_t frameT = 0;
    bool turbo = false;
    uint8_t ints = 0;
    uint8_t repeats = 0;
    uint16_t rref = 0, r4000 = 0, rc5 = 0, rc1 = 0;

    /// Extra thousandths of a T per read, as the program prints it
    static uint32_t Extra(uint16_t ref, uint16_t x) { return ref > x ? (ref - x) * 3u / 2u : 0u; }
    uint32_t Extra4000() const { return Extra(rref, r4000); }
    uint32_t ExtraC5() const { return Extra(rref, rc5); }
    uint32_t ExtraC1() const { return Extra(rref, rc1); }
};

ZxTimeResult ReadResult(Memory& memory, const ZxTimeProgram& p)
{
    auto peek = [&](uint16_t a) { return memory.DirectReadFromZ80Memory(a); };
    auto peek16 = [&](uint16_t a) { return static_cast<uint16_t>(peek(a) | peek(static_cast<uint16_t>(a + 1)) << 8); };
    ZxTimeResult r;
    r.done = peek(p.Sym("DONE")) == 1;
    const uint16_t passes = p.Sym("PASSES");
    r.passes = peek16(passes) | static_cast<uint32_t>(peek(static_cast<uint16_t>(passes + 2))) << 16;
    const uint16_t frame = p.Sym("FRAMET");
    r.frameT = peek16(frame) | static_cast<uint32_t>(peek16(static_cast<uint16_t>(frame + 2))) << 16;
    r.turbo = peek(p.Sym("TURBO")) != 0;
    r.ints = peek(p.Sym("INTS"));
    r.repeats = peek(p.Sym("REPEATS"));
    r.rref = peek16(p.Sym("RREF"));
    r.r4000 = peek16(p.Sym("R4000"));
    r.rc5 = peek16(p.Sym("RC5"));
    r.rc1 = peek16(p.Sym("RC1"));
    return r;
}

std::string Describe(const ZxTimeResult& r)
{
    char line[300];
    std::snprintf(line, sizeof line,
                  "done=%d passes=%u frameT=%u turbo=%d ints=%u repeats=%u extra x1000: #4000=%u #C000p5=%u #C000p1=%u (counts %u %u %u %u)",
                  r.done, r.passes, r.frameT, r.turbo, r.ints, r.repeats, r.Extra4000(), r.ExtraC5(), r.ExtraC1(), r.rref, r.r4000,
                  r.rc5, r.rc1);
    return line;
}
}  // namespace

/// The committed reference files are what the source builds (no drift)
TEST(SprinterZxTimeFiles_Test, CommittedFilesMatchTheSource)
{
    const ZxTimeProgram p = BuildZxTime();
    ASSERT_FALSE(p.bytes.empty());
    EXPECT_LT(kOrg + p.bytes.size(), 0x9000u) << "the program must end below its interrupt table";
    EXPECT_TRUE(ZxProgramFiles::ReadBinary(ZxTimePath("zxtime.tap")) == ZxProgramFiles::BuildTap("zxtime", kOrg, p.bytes))
        << "rebuild with UNREAL_ZXTIME_EXPORT=1";
    EXPECT_TRUE(ZxProgramFiles::ReadBinary(ZxTimePath("zxtime.trd")) == ZxProgramFiles::BuildTrd("zxtime", kOrg, p.bytes))
        << "rebuild with UNREAL_ZXTIME_EXPORT=1";
    EXPECT_TRUE(ZxProgramFiles::ReadBinary(ZxTimePath("zxtime.sym")) == ZxProgramFiles::BuildSym(kHeading, p.asmResult.symbols))
        << "rebuild with UNREAL_ZXTIME_EXPORT=1";
}

/// UNREAL_ZXTIME_EXPORT=1 writes the reference files
TEST(SprinterZxTimeFiles_Test, Export)
{
    if (!std::getenv("UNREAL_ZXTIME_EXPORT"))
        GTEST_SKIP() << "set UNREAL_ZXTIME_EXPORT=1 to write zxtime.tap / .trd / .sym";
    const ZxTimeProgram p = BuildZxTime();
    ASSERT_FALSE(p.bytes.empty());
    const std::vector<std::pair<std::string, std::vector<uint8_t>>> files = {
        {"zxtime.tap", ZxProgramFiles::BuildTap("zxtime", kOrg, p.bytes)},
        {"zxtime.trd", ZxProgramFiles::BuildTrd("zxtime", kOrg, p.bytes)},
        {"zxtime.sym", ZxProgramFiles::BuildSym(kHeading, p.asmResult.symbols)}};
    for (const auto& [file, data] : files)
    {
        std::ofstream out(ZxTimePath(file), std::ios::binary);
        out.write(reinterpret_cast<const char*>(data.data()), static_cast<std::streamsize>(data.size()));
        ASSERT_TRUE(out.good()) << file;
    }
}

/// region <BIOS 3.06's own ZX mode (no hard disk)>

class SprinterZxTimeEsc_Test : public ::testing::Test
{
protected:
    EmulatorManager* _manager = nullptr;
    std::shared_ptr<Emulator> _emulator;
    EmulatorContext* _context = nullptr;
    PortDecoder_Sprinter* _decoder = nullptr;

    void SetUp() override
    {
        const std::string bios = (TestPathHelper::FindProjectRoot() / "data" / "rom" / "sprinter" / "sp2k-3.06-hf2.rom").string();
        if (!FileHelper::FileExists(bios))
            GTEST_SKIP() << "data/rom/sprinter/sp2k-3.06-hf2.rom not found";
        _manager = EmulatorManager::GetInstance();
        for (const auto& id : _manager->GetEmulatorIds())
            _manager->RemoveEmulator(id);
        _emulator = _manager->CreateEmulatorWithModelAndRAM("sprinter-zxtime", "SPRINTER", 4096, LoggerLevel::LogError);
        ASSERT_NE(_emulator, nullptr);
        _context = _emulator->GetContext();
        _decoder = dynamic_cast<PortDecoder_Sprinter*>(_context->pPortDecoder);
        ASSERT_NE(_decoder, nullptr);
        _decoder->GetRtc().SetFixedTime(1767268830);
        CONFIG& config = _context->config;
        std::memset(config.sprinter_rom_path, 0, sizeof(config.sprinter_rom_path));
        std::strncpy(config.sprinter_rom_path, bios.c_str(), sizeof(config.sprinter_rom_path) - 1);
        ASSERT_TRUE(_context->pCore->GetROM()->LoadROM());
        config.sprinter.fast_start = 1;
        _emulator->Reset();
        _emulator->EnableTurboMode();
    }

    void TearDown() override
    {
        _emulator.reset();
        if (_manager)
        {
            for (const auto& id : _manager->GetEmulatorIds())
                _manager->RemoveEmulator(id);
        }
    }

    bool SpectrumHas(const std::string& text) { return ScreenOCR::containsText(_emulator->GetId(), text); }
    void Zx(const std::string& key, int frames = 6)
    {
        _emulator->GetDebugManager()->GetKeyboardManager()->TapKey(key, 3);
        EmulatorTestHelper::RunFramesFast(_emulator.get(), frames);
    }
};

// ESC at BIOS 3.06's boot prompt: the BIOS's own ZX mode, the default Pentagon timing (320 lines, 71 680 T,
// Pentagon INT), 3.5 MHz unless the CMOS says turbo; TR-DOS from the floppy, RUN: zxtime measures a 71 680-T
// frame, one INT per frame, no original waits (ALL_MODE #FE)
// Boot-bound (BIOS POST, its prompt, the ZX menu, TR-DOS loading zxtime from the floppy, 50 + 34 measured
// frames): ~1 s host time with the turbo mode
TEST_F(SprinterZxTimeEsc_Test, Pentagon_FrameIntAndNoWaits)
{
    const ZxTimeProgram p = BuildZxTime();
    ASSERT_FALSE(p.bytes.empty());
    const std::string trd = TestPathHelper::GetUniqueTestScratchPath("zxtime.trd");
    std::vector<uint8_t> image = ZxProgramFiles::BuildTrd("zxtime", kOrg, p.bytes);
    ASSERT_TRUE(FileHelper::SaveBufferToFile(trd, image.data(), image.size()));
    std::string error;
    ASSERT_TRUE(_emulator->LoadDisk(trd, 0, &error)) << error;

    const char* prompt = "<ESC> TO ZX-MODE";
    auto promptShown = [&]() {
        const SprinterVideoRam& vram = _decoder->GetVideoRam();
        std::string text;
        for (uint8_t page = 0; page < 2; page++)
            for (uint8_t b = 0; b < 32; b++)
                for (uint8_t a = 0; a < 40; a++)
                    for (uint8_t half = 0; half < 2; half++)
                    {
                        const uint8_t c = vram.Read((1u + 2u * a + half + 0x80u * page) * 1024u + 0x301 + 4u * b);
                        text.push_back((c >= 0x20 && c < 0x7F) ? static_cast<char>(c) : ' ');
                    }
        return text.find(prompt) != std::string::npos;
    };
    EmulatorTestHelper::RunUntil(_emulator.get(), promptShown, 1200, 5);
    ASSERT_TRUE(promptShown());
    Zx("pc.esc", 10);
    EmulatorTestHelper::RunUntil(_emulator.get(), [&] { return SpectrumHas("TR-DOS"); }, 600, 10);
    ASSERT_TRUE(SpectrumHas("TR-DOS")) << ScreenOCR::ocrScreen(_emulator->GetId());
    EmulatorTestHelper::RunFramesFast(_emulator.get(), 30);
    Zx("enter", 80);  // the menu's first entry: TR-DOS
    Zx("r", 6);       // RUN (keyword mode): boot loads and starts zxtime
    Zx("enter", 6);
    const uint16_t done = p.Sym("DONE");
    EmulatorTestHelper::RunUntil(_emulator.get(), [&] { return _context->pMemory->DirectReadFromZ80Memory(done) == 1; }, 2000, 10);
    const ZxTimeResult r = ReadResult(*_context->pMemory, p);
    ASSERT_TRUE(r.done) << ScreenOCR::ocrScreen(_emulator->GetId());
    std::printf("[ zxtime ESC ] %s\n%s\n", Describe(r).c_str(), ScreenOCR::ocrScreen(_emulator->GetId()).c_str());
    RecordProperty("zxtime", Describe(r));

    EXPECT_EQ((_decoder->GetPldState().allMode & 0x04), 0x04) << "the default ZX mode keeps the original waits off";
    if (!r.turbo)
    {
        EXPECT_EQ(r.frameT, 71680u) << Describe(r);
        EXPECT_EQ(r.Extra4000(), 0u) << Describe(r);
        EXPECT_EQ(r.ExtraC5(), 0u) << Describe(r);
    }
    EXPECT_EQ(r.ints, 50u) << Describe(r);
    EXPECT_EQ(r.repeats, 0u) << "the acknowledge ends the pulse; " << Describe(r);
    EXPECT_TRUE(SpectrumHas("Done.")) << ScreenOCR::ocrScreen(_emulator->GetId());
}

/// endregion </BIOS 3.06's own ZX mode>

/// region <The launcher's modes on the owner's system disk>

namespace
{
/// The launcher modes of C:\ZX on the MAME-pack disk and how zxtime reaches TR-DOS in each: the Sprinter TR-DOS
/// 7.03 modes read it from the RAM disk (the launcher loads the image), ORIGIN.ZX's TR-DOS 5.04Em and SC256.ZX's
/// Scorpion TR-DOS read the real floppy
struct LauncherMode
{
    const char* zx;
    bool ramDisk;
    const char* options;
};
constexpr LauncherMode kModes[] = {
    {"sp.zx", true, "/sprinter /turbo /7FFD /1FFD /ret-fn"},
    {"p128.zx", true, "/7FFD /ret-fn"},
    {"p512.zx", true, "/turbo /7FFD /mem512 /ret-fn"},
    {"sc256.zx", false, "/turbo /7FFD /1FFD /sc-int /lines312 /ret-fn"},
    {"origin.zx", false, "/7FFD /origin /lines312 /ret-fn"},
};
}  // namespace

class SprinterZxTimeModes_Test : public SprinterZxSession_Test
{
protected:
    /// The base T-state of the frame at every M1 of zxtime's interrupt handler (#9191): where the INT is taken
    struct IntProbe : IMachineM1Hook
    {
        IMachineM1Hook* inner = nullptr;
        PortDecoder_Sprinter* decoder = nullptr;
        EmulatorContext* context = nullptr;
        std::map<uint32_t, uint32_t> positions;  ///< base T in the frame -> how often
        void BeforeMachineM1(uint16_t address) override
        {
            inner->BeforeMachineM1(address);
            if (address == 0x9191)
                positions[decoder->BaseTstate()]++;
        }
        void OnMachineM1(uint16_t address) override { inner->OnMachineM1(address); }
    };
    IntProbe _probe;

    void TearDown() override
    {
        if (_context && _probe.inner)
            _context->pCore->GetZ80()->machineM1Hook = _probe.inner;
        SprinterZxSession_Test::TearDown();
    }
};

// Each launcher mode runs zxtime as a user does (`spectrum <mode>.zx <image>`, ENTER on TR-DOS, RUN); the results
// and the INT positions go to the timing table (tdd-zx-mode.md §4.1). Expected per the PLD and the launcher's
// options: 320 lines / 71 680 T without /lines312, 312 / 69 888 T with it; 3.5 MHz without /turbo; the original
// waits only in ORIGIN.ZX (ALL_MODE #FA); one INT per frame, ended by its acknowledge.
// Boot-bound (BIOS, DSS 1.71, five launcher runs with TR-DOS and 84 measured frames each): ~10 s host time
TEST_F(SprinterZxTimeModes_Test, LauncherModes)
{
    const ZxTimeProgram p = BuildZxTime();
    ASSERT_FALSE(p.bytes.empty());
    std::vector<uint8_t> trd = ZxProgramFiles::BuildTrd("zxtime", kOrg, p.bytes);
    ASSERT_EQ(trd.size(), 655360u);
    // The RAM-disk modes take it from the hard disk: in place of C:\TRD\SHOCK.TRD (same size), in the session
    ASSERT_TRUE(Disk().Overwrite("/TRD/SHOCK.TRD", trd));
    // The floppy modes: drive A
    const std::string floppy = TestPathHelper::GetUniqueTestScratchPath("zxtime-a.trd");
    ASSERT_TRUE(FileHelper::SaveBufferToFile(floppy, trd.data(), trd.size()));
    std::string error;
    ASSERT_TRUE(_emulator->LoadDisk(floppy, 0, &error)) << error;

    ASSERT_NO_FATAL_FAILURE(BootToPrompt());
    Z80* z80 = _context->pCore->GetZ80();
    _probe.inner = z80->machineM1Hook;
    _probe.decoder = _decoder;
    _probe.context = _context;
    z80->machineM1Hook = &_probe;

    const uint16_t done = p.Sym("DONE");
    std::string table;
    for (const LauncherMode& mode : kModes)
    {
        SCOPED_TRACE(mode.zx);
        _context->pMemory->DirectWriteToZ80Memory(done, 0);
        _probe.positions.clear();
        ASSERT_NO_FATAL_FAILURE(Launch(std::string(mode.zx) + " c:\\trd\\shock.trd"));
        const SprinterPldState pld = _decoder->GetPldState();
        // The INT positions the mode table gives (base T of the frame) and, for a comparison with MAME's
        // (tools/machines/sprinter/mame-capture "vram"), the video RAM
        std::string ints;
        for (uint32_t t : _decoder->GetIntSource().Positions())
            ints += std::to_string(t) + " (line " + std::to_string(t / 224) + ", T " + std::to_string(t % 224) + ") ";
        if (const char* dir = std::getenv("UNREAL_SPRINTER_ZX_SHOTS"))
        {
            std::vector<uint8_t> vram(SprinterVideoRam::kSize);
            for (uint32_t i = 0; i < vram.size(); i++)
                vram[i] = _decoder->GetVideoRam().Read(i);
            FileHelper::SaveBufferToFile(std::string(dir) + "/vram-" + mode.zx + ".bin", vram.data(), vram.size());
        }
        if (std::strcmp(mode.zx, "origin.zx") == 0)
        {
            for (int i = 0; i < 4; i++)
                Zx("down", 10);  // the standard 128 menu: Tape Loader, 128 BASIC, Calculator, 48 BASIC, TR-DOS
        }
        Zx("enter", 100);  // TR-DOS
        Zx("r", 6);        // RUN
        Zx("enter", 6);
        EmulatorTestHelper::RunUntil(_emulator.get(), [&] { return _context->pMemory->DirectReadFromZ80Memory(done) == 1; }, 3000, 10);
        const ZxTimeResult r = ReadResult(*_context->pMemory, p);
        SaveScreen(std::string("zxtime-") + mode.zx + ".png");
        EXPECT_TRUE(r.done) << SpectrumText();

        // The most frequent INT position (the handler's first fetch) in base T of the frame
        uint32_t intT = 0, best = 0;
        for (const auto& [t, n] : _probe.positions)
        {
            if (n > best)
            {
                best = n;
                intT = t;
            }
        }
        char row[600];
        std::snprintf(row, sizeof row,
                      "%-10s ALL_MODE=%02X turbo=%u lines=%u RGMOD=%02X | %s | INT at %s| handler M1 at base T %u (line %u, T %u) x%u\n",
                      mode.zx, pld.allMode, pld.turbo, pld.frameLines ? 312u : 320u, pld.rgMod, Describe(r).c_str(), ints.c_str(),
                      intT, intT / 224, intT % 224, best);
        table += row;

        const bool lines312 = std::strstr(mode.options, "/lines312") != nullptr;
        const bool turbo = std::strstr(mode.options, "/turbo") != nullptr;
        const bool origin = std::strstr(mode.options, "/origin") != nullptr;
        EXPECT_EQ(r.turbo, turbo) << Describe(r);
        if (!turbo)
            EXPECT_EQ(r.frameT, lines312 ? 69888u : 71680u) << Describe(r);
        EXPECT_EQ(r.ints, 50u) << Describe(r);
        EXPECT_EQ(r.repeats, 0u) << Describe(r);
        EXPECT_EQ((pld.allMode & 0x04) == 0, origin) << "ALL_MODE bit 2 = 0 only in ORIGIN.ZX";
        if (!turbo && !origin)
        {
            EXPECT_EQ(r.Extra4000(), 0u) << Describe(r);
            EXPECT_EQ(r.ExtraC5(), 0u) << Describe(r);
        }
        if (origin)
        {
            // LD A,(nn) every 13 T: the reads settle on alternating CT5 phases, 0 and 2 T of wait - 1 T each
            EXPECT_NEAR(static_cast<double>(r.Extra4000()), 1000.0, 15.0) << Describe(r);
            EXPECT_NEAR(static_cast<double>(r.ExtraC5()), 1000.0, 15.0) << Describe(r);
            EXPECT_EQ(r.ExtraC1(), 0u) << "page 1 at #C000: #7FFD bit 2 clear; " << Describe(r);
        }

        CtrlAltDel(20);  // /ret-fn: back to DSS
        EmulatorTestHelper::RunUntil(_emulator.get(), [&] { return !InZxMode(); }, 300, 10);
        ASSERT_FALSE(InZxMode()) << "Ctrl+Alt+Del did not bring DSS back";
        EmulatorTestHelper::RunFramesFast(_emulator.get(), 200);  // DSS restores its screen and waits for keys
    }
    std::printf("[ zxtime modes ]\n%s", table.c_str());
    RecordProperty("table", table);
}

/// endregion </The launcher's modes>

/// region <Tape (tdd-zx-mode.md §3.4, T-ZX-7)>

// The Sprinter's tape counts real time (Tape::SetBaseClockTimeBase): a machine of another model keeps the CPU clock
TEST_F(SprinterZxTimeEsc_Test, Tape_BaseClockTimeBaseOnTheSprinter)
{
    ASSERT_NE(_context->pTape, nullptr);
    EXPECT_TRUE(_context->pTape->IsBaseClockTimeBase());
}

// The tape through the ROM loader, in real time (the fast-load trap off): zxtime.tap (a BASIC loader that loads and
// starts the code) from 48 BASIC's LOAD "". P128.ZX runs the ROM at 3.5 MHz: the program loads and runs. SP.ZX runs
// it at 21 MHz: the loader's edge timing is six times too short for the tape, nothing loads - as on the board, whose
// tape input (KMPS) is played in real time (research-zx-mode.md §8)
// Boot-bound (BIOS, DSS 1.71, two launcher runs, ~11 s of tape each): ~6 s host time
TEST_F(SprinterZxTimeModes_Test, Tape_LoadsAt35MhzNotInTurbo)
{
    const ZxTimeProgram p = BuildZxTime();
    ASSERT_FALSE(p.bytes.empty());
    const std::string tap = ZxTimePath("zxtime.tap");
    ASSERT_TRUE(FileHelper::FileExists(tap));
    ASSERT_TRUE(_context->pFeatureManager->setFeature(Features::kFastTape, false));
    ASSERT_NO_FATAL_FAILURE(BootToPrompt());

    const uint16_t done = p.Sym("DONE");
    for (const char* mode : {"p128.zx", "sp.zx"})
    {
        SCOPED_TRACE(mode);
        const bool turbo = std::strcmp(mode, "sp.zx") == 0;
        for (uint16_t i = 0; i < 16; i++)
            _context->pMemory->DirectWriteToZ80Memory(static_cast<uint16_t>(kOrg + i), 0);
        ASSERT_NO_FATAL_FAILURE(Launch(mode));
        for (int i = 0; i < 4; i++)
            Zx("down", 10);  // TR-DOS, Hardware, 128 BASIC, Calculator, 48 BASIC
        Zx("enter", 100);
        SaveScreen(std::string("tape-48basic-") + mode + ".png");
        ASSERT_TRUE(SpectrumHas("Sinclair")) << "48 BASIC; " << SpectrumText();
        std::string error;
        ASSERT_TRUE(_emulator->LoadTape(tap, &error)) << error;
        Zx("j", 6);  // LOAD
        Keys()->TapCombo({"symbol", "p"}, 3);
        EmulatorTestHelper::RunFramesFast(_emulator.get(), 6);
        Keys()->TapCombo({"symbol", "p"}, 3);
        EmulatorTestHelper::RunFramesFast(_emulator.get(), 6);
        Zx("enter", 6);
        EmulatorTestHelper::RunUntil(_emulator.get(), [&] { return _context->pMemory->DirectReadFromZ80Memory(done) == 1; }, 1500, 10);
        SaveScreen(std::string("tape-") + mode + ".png");
        bool loaded = true;
        for (size_t i = 0; i < 16 && i < p.bytes.size(); i++)
            loaded = loaded && _context->pMemory->DirectReadFromZ80Memory(static_cast<uint16_t>(kOrg + i)) == p.bytes[i];
        if (turbo)
        {
            EXPECT_EQ(_decoder->GetPldState().turbo, 1);
            EXPECT_FALSE(loaded) << "21 MHz: the ROM loader cannot read a real-time tape; " << SpectrumText();
            EXPECT_NE(_context->pMemory->DirectReadFromZ80Memory(done), 1);
        }
        else
        {
            EXPECT_EQ(_decoder->GetPldState().turbo, 0);
            EXPECT_TRUE(loaded) << SpectrumText();
            EXPECT_EQ(_context->pMemory->DirectReadFromZ80Memory(done), 1) << SpectrumText();
            EXPECT_TRUE(SpectrumHas("FRAME  71680 T")) << SpectrumText();
        }
        _emulator->GetContext()->pTape->stopPlayback();
        CtrlAltDel(20);
        EmulatorTestHelper::RunUntil(_emulator.get(), [&] { return !InZxMode(); }, 300, 10);
        ASSERT_FALSE(InZxMode());
        EmulatorTestHelper::RunFramesFast(_emulator.get(), 200);
    }
}

/// endregion </Tape>
