"""Symbol dictionary and educational comments for atm2.rom page 3.

The ATM710 CP/M system image: page zero stubs, service monitor core,
cold-boot config shell, DRI CCP, BDOS and the XVR disk-BIOS, plus the
RAM-resident driver/WBOOT tail.  All runtime anchors below were traced on
the emulator during the prince.trd investigation (see ../monitor-rom.md,
../bios-ram.md, ../analysis.md).
"""

# ---------------------------------------------------------------------------
# Symbols fed to z80dasm --sym-input.  Image-relative addresses; the runtime
# mappings are documented in the HEADER and at each anchor.
# ---------------------------------------------------------------------------
SYMBOLS = [
    # --- page zero -------------------------------------------------------
    (0x0000, 'WbootStub'),
    (0x0005, 'BdosEntry'),
    (0x0008, 'Rst08Vector'),
    (0x0010, 'Rst10Vector'),
    (0x0018, 'Rst18Vector'),
    (0x0020, 'Rst20Vector'),
    (0x0028, 'Rst28Vector'),
    (0x0030, 'Rst30Vector'),
    (0x0038, 'IntVector'),
    (0x0066, 'NmiVector'),
    (0x004E, 'Rst18Handler'),
    (0x0155, 'IntHandler'),
    (0x110B, 'Rst08Handler'),
    (0x0B9D, 'Rst20Handler'),
    # --- service monitor / config core -----------------------------------
    (0x02CA, 'BiosJumpTable'),
    (0x03DC, 'VideoSaveRestore'),
    (0x0965, 'ServiceLdirCopy'),
    (0x11FF, 'MonitorPrintNumber'),
    (0x1206, 'MonitorPrint'),
    (0x1400, 'ColdShellEntry'),
    # --- CCP --------------------------------------------------------------
    (0x1BC6, 'CcpBase'),
    # --- BDOS --------------------------------------------------------------
    (0x2A00, 'BdosRecordMath'),
    (0x31C6, 'BdosDispatch'),
    (0x3265, 'BdosOpenCore'),
    # --- driver / WBOOT tail -----------------------------------------------
    (0x3800, 'RamSizeMenu'),
    (0x3866, 'WbootReloadImage'),
    (0x387E, 'Wboot'),
    (0x38FA, 'WbootContinue'),
    (0x3E08, 'DriverDispatch'),
]

# ---------------------------------------------------------------------------
# Listing header (Logan & O'Hara style).
# ---------------------------------------------------------------------------
HEADER = [
    '; ============================================================================',
    ';  ATM TURBO 710 - CP/M SYSTEM PAGE  (page 3 of atm2.rom)',
    '; ============================================================================',
    ';',
    ';  Source   : data/rom/atm2.rom, bytes $C000-$FFFF (page 3), 16 KiB',
    ';  Content  : page-zero stubs, service monitor core, cold-boot config',
    ';             shell, DRI CCP 2.2, BDOS 2.2, XVR BIOS V1.07.13 and the',
    ';             driver/WBOOT tail (all addresses below are image-relative).',
    ';  Method   : z80dasm 1.2.0, code/data block map from a dedicated',
    ';             Z80 length-decoder + reachability analysis (scripts/);',
    ';             labels and comments added after studying the ROM bytes,',
    ';             the atmturbo BIOS notes and live emulator traces.',
    ';  Style    : educational, after Logan & O\'Hara, "The Complete Spectrum',
    ';             ROM Disassembly".',
    ';',
    '; ----------------------------------------------------------------------------',
    ';  THE ROM BUNDLE',
    '; ----------------------------------------------------------------------------',
    ';  atm2.rom is a 64 KiB bundle of four 16 KiB pages.  core/src/emulator/',
    ';  memory/rom.cpp maps the MM_ATM710 slots as:',
    ';',
    ';    sos  = page 0 ($0000-)  boot monitor / 128K start-up',
    ';    dos  = page 1 ($4000-)  TR-DOS',
    ';    128  = page 2 ($8000-)  128K BASIC',
    ';    sys  = page 3 ($C000-)  THIS CP/M system image',
    ';',
    ';  Memory::SetROMSystem() maps the sys page at $0000-$3FFF whenever the',
    ';  machine enters a service session (#7FFD bit 4 set) - the mapping the',
    ';  page is primarily assembled for.',
    ';',
    '; ----------------------------------------------------------------------------',
    ';  THE ADDRESS MAPPINGS (read this first)',
    '; ----------------------------------------------------------------------------',
    ';  The same 16 KiB image is visible under FOUR bases at runtime; which',
    ';  one a branch target means depends on the target window:',
    ';',
    ';  1. $0000-$3FFF -> 1:1.  The service session (ROM at $0000, #7FFD bit 4).',
    ';     Page-zero stubs, monitor core and the WBOOT code\'s own local jumps',
    ';     (e.g. JP WbootContinue $38FA inside Wboot) use this view.',
    ';',
    ';  2. $C000-$D3FF -> +$C000.  Alias window onto the service code: the ROM',
    ';     page banked high.  Branches here from this page land back on image',
    ';     $0000-$13FF monitor code.',
    ';',
    ';  3. $D400-$EFFF -> DUAL, two copies at different times:',
    ';       a) cold start: the config shell (image $1400-$1BC5) copied to',
    ';          $D400 - its internal absolute targets use +$C000;',
    ';       b) after warm boot: WbootReloadImage ($3866) LDIRs the CCP+BDOS',
    ';          image $1BC6-$36E3 to $D400-$EF1E - internal targets use',
    ';          image = runtime - $B83A.',
    ';     Proofs for (b): the CCP trampolines at CcpBase JP $D75C/$D758 =',
    ';     +$35C/+$358 inside the copy; the 20-entry BdosDispatch at $31C6',
    ';     lands exactly on the traced BDOS entry $EA00; the traced BDOS',
    ';     bodies $E9DD/$EA9F map to image $31A3/$3265.',
    ';',
    ';  4. $F000-$FFFF -> +$C000.  The driver/WBOOT tail: BiosJumpTable at',
    ';     image $02CA dispatches JP $F8xx into image $38xx; the traced',
    ';     WBOOT entry $F87E = image $387E.',
    ';',
    '; ----------------------------------------------------------------------------',
    ';  REGION MAP (image-relative)',
    '; ----------------------------------------------------------------------------',
    ';    $0000-$00FF  page zero: WbootStub, BDOS marker (ED 59), RST stubs',
    ';    $0100-$13FF  service monitor/menu core, FDC helpers, config code',
    ';    $1400-$1BC5  cold-boot config shell (runs from the $D400 copy)',
    ';    $1BC6-$23FF  DRI CCP (serial banner, command keywords, messages)',
    ';    $2400-$2BFF  BDOS data: error strings, FCB/record utilities',
    ';    $2C00-$36E3  BDOS dispatch ($31C6) + function bodies + XVR BIOS',
    ';    $36E4-$37FF  BIOS tail (fault messages)',
    ';    $3800-$3FFF  driver/WBOOT: RAM-size menu, Wboot ($387E), keyboard',
    ';                 and charset tables, driver sub-dispatch ($3E08)',
    ';',
    '; ----------------------------------------------------------------------------',
    ';  RUNTIME ANCHORS (traced on the emulator)',
    '; ----------------------------------------------------------------------------',
    ';    image $0965 = service LDIR copy   (repeated-M1 "wait loop" signature)',
    ';    image $1BC6 = $D400 CCP warm entry (end of every transient)',
    ';    image $31C6 = $EA00 BDOS function entry (CALL $0005 lands here)',
    ';    image $3265 = $EA9F BDOS open/directory-search core',
    ';    image $387E = $F87E WBOOT (+$C000 driver window)',
    ';',
    ';  Open question: BiosJumpTable entries $F833/$F835/$F857 fall inside',
    ';  the \'Memory \'/\'size is \' string bytes of THIS page\'s driver mirror;',
    ';  on the monitor page the same addresses are real handlers (see',
    ';  ../fdc-driver.md - the two pages carry sibling builds of one driver).',
    ';',
    ';  Companion documents: ../README.md (index), ../monitor-rom.md,',
    ';  ../bios-ram.md, ../analysis.md, ../disk-monitor.md, ../pr2-loader.md.',
]

# ---------------------------------------------------------------------------
# Educational comments, inserted above the code at each address.
# ---------------------------------------------------------------------------
COMMENTS = [
    (0x0000, [
        'Page zero, service view - WBOOT stub.',
        'DI then JP Wboot ($387E, image 1:1).  In the CP/M RAM view the same',
        'cell is the standard warm-boot vector installed at boot; the byte',
        'pair at $0004/$0005 (ED 59 = "OUT (C),E") doubles as the ATM BDOS',
        'entry marker - see BdosEntry below.',
    ]),
    (0x0004, [
        'BDOS entry marker (ATM-specific).',
        'The RAM page zero carries the BDOS entry at $0005: callers do',
        'CALL $0005 with the function in C, parameters in DE, and read the',
        'result from A.  These two bytes (ED 59 = "OUT (C),E)") sit at',
        '$0004/$0005 and double as the ATM BDOS marker - the service BDOS',
        'recognises entry here and dispatches into the $EAxx bodies.',
        'Traced protocol notes: the pushed return address observed at (SP)',
        'is one less than the instruction after the CALL - match',
        'pc == retPc || pc == retPc+1 when sampling the result code',
        '(../bios-ram.md).',
    ]),
    (0x0008, [
        'RST 08h vector - JP Rst08Handler ($110B).',
        'The config shell calls this (RST 08 at ColdShellEntry) for its',
        'menu/dialog service layer.',
    ]),
    (0x0018, [
        'RST 18h vector - JP Rst18Handler ($004E).',
        'RST 10h (slot above) is unused: its NOP padding falls through to',
        'this stub, so both vectors share $004E.',
    ]),
    (0x0020, [
        'RST 20h vector - JP Rst20Handler ($0B9D).',
    ]),
    (0x0038, [
        'INT vector - JP IntHandler ($0155).',
        'The launch traces saw ~160 INT hits during a PR2 load with the',
        'game running IM2 (../bios-ram.md, "Interrupts During a Launch").',
    ]),
    (0x02CA, [
        'THE CP/M BIOS JUMP TABLE - 17 entries, JP $F8xx each.',
        'Executed 1:1 in the service view; every target translates +$C000',
        'into this page\'s driver mirror at image $38xx:',
        '  $02CA JP $F835  boot entry        $02DC JP $F8B5',
        '  $02CD JP $F8A9  console input     $02DF JP $F8C5',
        '  $02D0 JP $F833  (nop/ret)         $02E2 JP $F8C0',
        '  $02D3 JP $F89A  console output    $02E5 JP $F857  home disk',
        '  $02D6 JP $F833  (nop/ret)         $02E8 JP $F833  (nop/ret)',
        '  $02D9 JP $F84A  list output       $02EB JP $F83B  system reset',
        '  $02EE JP $F88F  read sector       $02F1 JP $F872  write sector',
        '  $02F4 JP $F87E  WBOOT (traced)    $02F7 JP $F882',
        '  $02FA JP $F83F',
        'Same target set as the monitor page\'s $F800 table (../monitor-rom.md).',
        'NOTE: $F833/$F835/$F857 land inside the \'Memory \'/\'size is \' string',
        'bytes here - this page\'s driver mirror is a sibling build, not the',
        'byte-identical monitor driver (open question, HEADER above).',
    ]),
    (0x03DC, [
        'Video-mode save/restore through port $FD.',
        'LD (F975),SP / LD SP,$8000 / IM 1 ... writes attribute bytes \'R\'',
        'and \'B\' (52h/42h) to port $FD, restores SP from $F975, IM 2, EI.',
        'Reached from the video-mode switch paths of the monitor core.',
    ]),
    (0x0965, [
        'ServiceLdirCopy - the "service session wait loop".',
        'LDIR + RET.  The emulator M1 trace shows long runs (389+) of',
        'consecutive fetches at this address during disk operations: that is',
        'not a poll loop but LDIR re-executing itself once per copied byte.',
        'Refines the note in ../monitor-rom.md ("0x0965 - Service Session',
        'Wait Loop").',
    ]),
    (0x11FF, [
        'MonitorPrintNumber - decimal print used by the RAM-size report',
        '(CALL $11FF right before the "k." suffix at MsgKib).',
    ]),
    (0x1206, [
        'MonitorPrint - string print used by the RAM-size report',
        '(prints "Memory " at MsgMemory and "size is " at MsgSizeIs).',
    ]),
    (0x1400, [
        'ColdShellEntry - cold-boot configuration shell.',
        'LD DE,(5FB2) / LD HL,(5FAD) / RST 08 ... JP (HL): menu-driven',
        'memory/disk configuration.  Runs from the $D400 RAM copy at cold',
        'start (the +$C000 view of this range); after configuration WBOOT',
        'replaces the copy with the CCP+BDOS image.  The RAM-size options it',
        'presents live in RamSizeTable ($3815): 128 / 512 / 1024 KiB - the',
        '512/1024 modes the prince.trd investigation booted (../analysis.md).',
    ]),
    (0x1BC6, [
        'CcpBase - DRI Console Command Processor, cold entry.',
        'JP $D75C / JP $D758: trampolines to +$35C/+$358 inside the $D400',
        'copy (the t-$B83A view).  The DRI serial $7F 00 sits at +3, the',
        '"COPYRIGHT (C) 1979, DIGITAL RESEARCH" banner at +8; keywords',
        'DIR ERA TYPE SAVE REN USER at $1ED6.  Runtime $D400 is the warm',
        'entry every transient returns to.',
        'Drive mapping that decided the PR2 launch: A: = electronic (RAM)',
        'disk, B: = floppy; the CCP re-selects the CURRENT drive before',
        'entering a transient, so FCB-drive-0 programs need "B:" typed',
        'first (../bios-ram.md, ../pr2-loader.md).',
    ]),
    (0x247E, [
        'Classic CP/M 2.2 BDOS error strings:',
        '"Bdos Err On : $" then "Bad Sector$", "Select$", "File R/O$".',
    ]),
    (0x2A00, [
        'BdosRecordMath - FCB record/block arithmetic.',
        'LD D,A / LD A,C / RRCA x3 / AND $1F: sector-within-block split;',
        'LD A,B / ADD A,A x5 / OR C: block number assembly.  Feeds the',
        'sequential-read path that loads transients record by record',
        '(~176 reads for PR2.COM, ../bios-ram.md).',
    ]),
    (0x31C6, [
        'BdosDispatch - 20 x JP $EAxx, the BDOS function dispatch.',
        'Lands exactly on the traced BDOS entry $EA00 in the $D400 copy',
        '(image = runtime - $B83A): the entries target image $3202-$33B5,',
        'the real BDOS function bodies.  Function 0 (system reset) enters at',
        '$3202 right behind the table.',
    ]),
    (0x3265, [
        'BdosOpenCore - open/directory-search core.',
        'Traced at runtime $EA9F-$EAB6 during FCB OPEN processing; the',
        'return-path pieces $EB0D-$EB12 marshal the result back to the',
        'caller\'s TPA (../monitor-rom.md, "BDOS Implementation").',
    ]),
    (0x34F2, [
        'BIOS banner block (four embedded messages, all NUL-terminated):',
        '  $34F2 "CP/M  V2.2     COPYRIGHT(C)  BY  DIGITAL RESEARCH."',
        '  $3525 "BIOS  V1.07.13 COPYRIGHT(C)  BY  XVR - PRODUCT."',
        '  $3556 "BIOS ERROR "  $3569 " SELECT ((R)ETRY, (I)GNORE, (A)BORT,',
        '        (F)AIL) :"',
    ]),
    (0x3800, [
        'RamSizeMenu - memory configuration scan and report.',
        'Scans RamSizeTable ($3815: attr+string records "128"/"512"/"1024"),',
        'prints "Memory " (MsgMemory), the size via MonitorPrintNumber,',
        '"size is " (MsgSizeIs), the value and the "k." KiB suffix (MsgKib),',
        'then stores the selection into the $FA4D/$FA55 cells.',
    ]),
    (0x3866, [
        'WbootReloadImage - THE warm-boot reload.',
        'LD BC,$1B1E / LD DE,$D400 / LD HL,$1BC6 / LDIR / RET:',
        'copies the CCP+BDOS image $1BC6-$36E3 to RAM $D400-$EF1E.  This',
        'LDIR is the proof of the t-$B83A mapping (the $D400-$EFFF window',
        'in dual use, HEADER above).',
    ]),
    (0x387E, [
        'Wboot - warm boot entry (traced at runtime $F87E).',
        'LD BC,$0077 / LD A,$02 / OUT (C),A: the ATM manager port $77 with',
        'the CPM control line; IM 1, DI, LD SP,$388E, JP WbootContinue',
        '($38FA).  The cell just above ($3872) latches port $FD77 from RAM',
        'variable $5F5D on the way in.',
    ]),
    (0x38FA, [
        'WbootContinue - disk re-read and page-zero rebuild, then the hand',
        'off to WbootReloadImage and the CCP at $D400.',
    ]),
    (0x3E08, [
        'DriverDispatch - 7 x JP local, the driver sub-dispatch:',
        'JP $3D54 / $392E / $3C36 / $3D0A / $3DBF / $39F4 / $392F (all 1:1).',
    ]),
]

# ---------------------------------------------------------------------------
# One-line naming comments for every data block (auditblocks.py coverage).
# ---------------------------------------------------------------------------
DATA_COMMENTS = [
    (0x000B, ['ZeroPageRst10Pad - NOP padding after the RST 08 stub; RST 10h is',
              'unused and falls through to the RST 18h stub.']),
    (0x001B, ['ZeroPageRst20Pad - NOP padding inside the RST 20h vector slot.']),
    (0x0023, ['ZeroPageRst30Pad - NOP padding inside the RST 30h vector slot.']),
    (0x003B, ['PageZeroReserved - reserved page-zero cells $003B-$004A.']),
    (0x0436, ['MonitorTable0436 - service monitor lookup table (70 bytes).']),
    (0x0609, ['MonitorTable0609 - service monitor lookup table.']),
    (0x0644, ['Data0644 - three stray bytes between monitor code streams.']),
    (0x06D1, ['MonitorTable06D1 - service monitor lookup table.']),
    (0x0715, ['MonitorTable0715 - service monitor lookup table.']),
    (0x073F, ['MonitorTable073F - service monitor lookup table.']),
    (0x0908, ['MonitorTable0908 - "1IRBFTO" eight-byte table fragment.']),
    (0x0A86, ['MonitorTable0A86 - monitor code/data mix island (RET, JP $0528,',
              'CALL $10A5, JR pair, LD (5F95),A ...).']),
    (0x0B63, ['FdcTable0B63 - FDC parameter table (see ../fdc-driver.md).']),
    (0x0B94, ['FdcTable0B94 - FDC parameter table (see ../fdc-driver.md).']),
    (0x0E32, ['MenuKbdRows - menu keyboard half-rows "AQ10P", "ZSW29OL",',
              '"XDE38IKM", "CFRT47UJ", "VGT56YHB" (ZX matrix layout).']),
    (0x0E5C, ['KbdSymMap0E5C - shifted-symbol key map, tailing into a small',
              'JP island (JP $0C13/$0D0B/$0D50/$0D61/$0D79, RET).']),
    (0x1306, ['ConfigTable1306 - cold-shell configuration table.']),
    (0x15E9, ['ColdShellTab15E9 - unreachable cold-shell fragment',
              '(CALL $1550, EXX, port $1F writes; orphaned CALL byte at end).']),
    (0x1A64, ['CcpTable1A64 - CCP lookup island.']),
    (0x1AC6, ['CcpMsgConfigError - "\\r\\nConfig error " message.']),
    (0x1ADC, ['CcpMsgStartupAborted - "startup aborted!\\r\\n" message.']),
    (0x1BC9, ['CcpSerialBanner - DRI serial $7F $00 at CcpBase+3, then',
              '"COPYRIGHT (C) 1979, DIGITAL RESEARCH" and padding.']),
    (0x1ED6, ['CcpCommandKeywords - "DIR ERA TYPE SAVE REN USER" keyword',
              'table (high-bit terminated entries).']),
    (0x1F91, ['CcpTable1F91 - CCP lookup island.']),
    (0x1FA5, ['CcpMsgReadError - "READ ERROR" message.']),
    (0x2118, ['CcpMsgAllYn - "ALL (Y/N)?" confirmation prompt.']),
    (0x21CD, ['CcpMsgNoSpace - "NO SPAC" message fragment.']),
    (0x2248, ['CcpMsgFileExists - "FILE EXISTS" plus trailing bytes.']),
    (0x2340, ['CcpMsgBadLoad - "BAD LOAD" and the "COM" default extension.']),
    (0x2361, ['BdosPad2361 - zero padding ahead of the BDOS error strings.']),
    (0x247E, ['BdosErrMessages - "Bdos Err On : $", "Bad Sector$", "Select$",',
              '"File R/O$" (classic CP/M 2.2).']),
    (0x34F2, ['BiosBanners - CP/M V2.2 / XVR BIOS V1.07.13 sign-ons,',
              '"BIOS ERROR" and the RETRY/IGNORE/ABORT/FAIL select prompt.']),
    (0x37DD, ['BiosFaultMsg - "fault. (" disk-fault message tail.']),
    (0x3815, ['RamSizeTable - attr+string records "128" / "512" / "1024".']),
    (0x382F, ['MsgMemory - "Memory " prefix of the RAM-size report.']),
    (0x3851, ['MsgSizeIs - "size is " of the RAM-size report.']),
    (0x3860, ['MsgKib - "k.\\r\\n" KiB suffix of the RAM-size report.']),
    (0x389D, ['DriverTable389D - driver lookup table.']),
    (0x38E0, ['DriverTable38E0 - driver lookup table.']),
    (0x3916, ['DriverTable3916 - driver lookup table.']),
    (0x3932, ['DriverTable3932 - driver lookup table.']),
    (0x3938, ['DriverTable3938 - driver lookup table.']),
    (0x395F, ['MsgM1Ve31 - "M1VE31 not installed" add-on board message.']),
    (0x39DE, ['DriverTable39DE - driver lookup table.']),
    (0x39F9, ['KbdMap39F9 - scan-code to charset class map (":" classes with',
              'high-bit codes 8E/91/9C/9F/AA).']),
    (0x3A3A, ['CharsetTables - 144 bytes of charset/codepage tables.']),
    (0x3BF6, ['KbdTables3BF6 - keyboard decode tables.']),
    (0x3C1F, ['KbdCtrlMap3C1F - control-key mapping pairs.']),
    (0x3CB3, ['KbdTables3CB3 - keyboard decode tables.']),
    (0x3D66, ['ZxKeyboardRows - ZX keyboard half-row matrix.']),
    (0x3F51, ['RomTailPad - trailing zero padding to the 16 KiB boundary.']),
]

COMMENTS += DATA_COMMENTS
