// poc_codec_latency.cpp — C++ codec comparison for the TTD workload.
//
// This PoC measures candidate codecs (zstd, lz4, brotli, snappy, FastLZ,
// zlib) against TWO classes of input:
//
//   1. REAL buffers extracted from an actual .ttd recording
//      (tools/poc/01-ttd-compression/cpp/real_buffers.bin — produced by
//      extract_real_buffers.py from testdata/ttd/active_demo.ttd, which is a
//      real recording made through the emulator API).
//      These are the exact 4 KB buffers the TTD codec hands to the
//      compressor in production: raw page snapshots (REAL_full) and
//      XOR-delta buffers (REAL_xor, the dominant workload).
//
//   2. SYNTHETIC workloads for shape-comparison purposes: random 4 KB,
//      synthetic 5% XOR-delta, all-zero. These are kept only as reference
//      points to demonstrate why conclusions drawn from synthetic data
//      alone are unreliable.
//
// Methodology:
//   - Each codec x workload pair is registered as a Google Benchmark
//     BENCHMARK_CAPTURE.
//   - Per iteration, the benchmark encodes every buffer in the workload
//     once and decodes it once, timing each encode/decode call with
//     std::chrono::steady_clock.
//   - p50/p95/p99 latency, throughput (MB/s), ratio (encoded/raw),
//     and distance to the Shannon entropy floor are reported as
//     UserCounters.

#include <benchmark/benchmark.h>

#include <algorithm>
#include <array>
#include <chrono>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <functional>
#include <random>
#include <string>
#include <vector>

#include "codec_config.h"  // auto-generated by CMake

#include <zstd.h>
#include <fastlz.h>

#ifdef LZ4_FOUND
#  include <lz4.h>
#  include <lz4hc.h>
#endif

#ifdef SNAPPY_FOUND
#  include <snappy.h>
#endif

#ifdef BROTLI_FOUND
#  include <brotli/encode.h>
#  include <brotli/decode.h>
#endif

#ifdef ZLIB_FOUND
#  include <zlib.h>
#endif

namespace {

constexpr size_t kSubPageSize = 4096;
constexpr size_t kWorkloadBuffers = 1000;

// Path to the real-buffer blob generated by extract_real_buffers.py.
// Overridable at runtime via the TTD_REAL_BUFFERS env var so the same
// binary can be pointed at different .ttd extractions without rebuilding.
// NOTE: this said "tools/poc/cpp/..." until the PoC moved into
// 01-ttd-compression. A stale path here is silent: load_real_buffers() prints
// one line and every REAL_ workload is skipped, so the run still "succeeds"
// while measuring synthetic data only.
constexpr const char* kDefaultRealBuffersPath =
    "tools/poc/01-ttd-compression/cpp/real_buffers.bin";

// Shannon entropy of a byte buffer in bits-per-byte (0..8).
// The theoretical minimum size any lossless codec can achieve for the
// buffer is `entropy * size / 8` bytes.
double shannon_entropy_bits_per_byte(const uint8_t* p, size_t n) {
    if (n == 0) return 0.0;
    size_t hist[256] = {};
    for (size_t i = 0; i < n; ++i) ++hist[p[i]];
    double H = 0.0;
    for (size_t v : hist) {
        if (v == 0) continue;
        double p_v = static_cast<double>(v) / static_cast<double>(n);
        H -= p_v * std::log2(p_v);
    }
    return H;
}

// ---------------------------------------------------------------------------
// Codec adapter
// ---------------------------------------------------------------------------
struct Codec {
    std::string name;
    std::function<size_t(const uint8_t*, size_t, uint8_t*, size_t)> encode;
    std::function<size_t(const uint8_t*, size_t, uint8_t*, size_t)> decode;
    std::function<size_t(size_t)> bound;
};

// ---------------------------------------------------------------------------
// Codec factories
// ---------------------------------------------------------------------------
Codec make_zstd(int level) {
    ZSTD_CCtx* cctx = ZSTD_createCCtx();
    ZSTD_DCtx* dctx = ZSTD_createDCtx();
    ZSTD_CCtx_setParameter(cctx, ZSTD_c_compressionLevel, level);

    Codec c;
    c.name = "zstd" + (level < 0 ? "n" + std::to_string(-level) : std::to_string(level));
    c.encode = [cctx](const uint8_t* s, size_t n, uint8_t* d, size_t cap) -> size_t {
        size_t r = ZSTD_compressCCtx(cctx, d, cap, s, n, 0);
        return ZSTD_isError(r) ? 0 : r;
    };
    c.decode = [dctx](const uint8_t* s, size_t n, uint8_t* d, size_t cap) -> size_t {
        size_t r = ZSTD_decompressDCtx(dctx, d, cap, s, n);
        return ZSTD_isError(r) ? 0 : r;
    };
    c.bound = [](size_t n) { return ZSTD_compressBound(n); };
    return c;
}

#ifdef LZ4_FOUND
Codec make_lz4_fast() {
    Codec c;
    c.name = "lz4-fast";
    c.encode = [](const uint8_t* s, size_t n, uint8_t* d, size_t cap) -> size_t {
        int r = LZ4_compress_default(reinterpret_cast<const char*>(s),
                                      reinterpret_cast<char*>(d),
                                      static_cast<int>(n), static_cast<int>(cap));
        return r > 0 ? static_cast<size_t>(r) : 0;
    };
    c.decode = [](const uint8_t* s, size_t n, uint8_t* d, size_t cap) -> size_t {
        int r = LZ4_decompress_safe(reinterpret_cast<const char*>(s),
                                     reinterpret_cast<char*>(d),
                                     static_cast<int>(n), static_cast<int>(cap));
        return r > 0 ? static_cast<size_t>(r) : 0;
    };
    c.bound = [](size_t n) { return static_cast<size_t>(LZ4_compressBound(static_cast<int>(n))); };
    return c;
}

Codec make_lz4_hc(int level) {
    Codec c;
    c.name = "lz4hc-" + std::to_string(level);
    c.encode = [level](const uint8_t* s, size_t n, uint8_t* d, size_t cap) -> size_t {
        int r = LZ4_compress_HC(reinterpret_cast<const char*>(s),
                                 reinterpret_cast<char*>(d),
                                 static_cast<int>(n), static_cast<int>(cap), level);
        return r > 0 ? static_cast<size_t>(r) : 0;
    };
    c.decode = [](const uint8_t* s, size_t n, uint8_t* d, size_t cap) -> size_t {
        int r = LZ4_decompress_safe(reinterpret_cast<const char*>(s),
                                     reinterpret_cast<char*>(d),
                                     static_cast<int>(n), static_cast<int>(cap));
        return r > 0 ? static_cast<size_t>(r) : 0;
    };
    c.bound = [](size_t n) { return static_cast<size_t>(LZ4_compressBound(static_cast<int>(n))); };
    return c;
}
#endif

#ifdef SNAPPY_FOUND
Codec make_snappy() {
    Codec c;
    c.name = "snappy";
    c.encode = [](const uint8_t* s, size_t n, uint8_t* d, size_t /*cap*/) -> size_t {
        size_t out_n = 0;
        snappy::RawCompress(reinterpret_cast<const char*>(s), n,
                            reinterpret_cast<char*>(d), &out_n);
        return out_n;
    };
    c.decode = [](const uint8_t* s, size_t n, uint8_t* d, size_t /*cap*/) -> size_t {
        size_t out_n = 0;
        if (!snappy::GetUncompressedLength(reinterpret_cast<const char*>(s), n, &out_n)) return 0;
        if (!snappy::RawUncompress(reinterpret_cast<const char*>(s), n,
                                    reinterpret_cast<char*>(d))) return 0;
        return out_n;
    };
    c.bound = [](size_t n) { return snappy::MaxCompressedLength(n); };
    return c;
}
#endif

#ifdef BROTLI_FOUND
Codec make_brotli(int level) {
    Codec c;
    c.name = "brotli-" + std::to_string(level);
    c.encode = [level](const uint8_t* s, size_t n, uint8_t* d, size_t cap) -> size_t {
        size_t out_n = cap;
        if (BROTLI_TRUE != BrotliEncoderCompress(
                level, BROTLI_DEFAULT_WINDOW, BROTLI_DEFAULT_MODE,
                n, s, &out_n, d)) return 0;
        return out_n;
    };
    c.decode = [](const uint8_t* s, size_t n, uint8_t* d, size_t cap) -> size_t {
        size_t out_n = cap;
        if (BROTLI_DECODER_RESULT_SUCCESS != BrotliDecoderDecompress(
                n, s, &out_n, d)) return 0;
        return out_n;
    };
    c.bound = [](size_t n) { return n + (n >> 1) + 64; };
    return c;
}
#endif

Codec make_fastlz(int level) {
    Codec c;
    c.name = "fastlz-" + std::to_string(level);
    c.encode = [level](const uint8_t* s, size_t n, uint8_t* d, size_t cap) -> size_t {
        int r = fastlz_compress_level(level, s, static_cast<int>(n), d);
        return (r > 0 && static_cast<size_t>(r) <= cap) ? static_cast<size_t>(r) : 0;
    };
    c.decode = [](const uint8_t* s, size_t n, uint8_t* d, size_t cap) -> size_t {
        int r = fastlz_decompress(s, static_cast<int>(n), d, static_cast<int>(cap));
        return r > 0 ? static_cast<size_t>(r) : 0;
    };
    c.bound = [](size_t n) { return n + n / 100 + 8; };
    return c;
}

#ifdef ZLIB_FOUND
Codec make_zlib(int level) {
    Codec c;
    c.name = "zlib-" + std::to_string(level);
    c.encode = [level](const uint8_t* s, size_t n, uint8_t* d, size_t cap) -> size_t {
        uLongf out_n = cap;
        if (Z_OK != compress2(d, &out_n, s, static_cast<uLong>(n), level)) return 0;
        return out_n;
    };
    c.decode = [](const uint8_t* s, size_t n, uint8_t* d, size_t cap) -> size_t {
        uLongf out_n = cap;
        if (Z_OK != uncompress(d, &out_n, s, static_cast<uLong>(n))) return 0;
        return out_n;
    };
    c.bound = [](size_t n) { return compressBound(static_cast<uLong>(n)); };
    return c;
}
#endif

// ---------------------------------------------------------------------------
// Codec list (built once)
// ---------------------------------------------------------------------------
std::vector<Codec> build_codec_list() {
    std::vector<Codec> codecs;
    // zstd: negative levels (ultra-fast), 0, 1 (production), 3, 9, 19 (max).
    codecs.push_back(make_zstd(-5));
    codecs.push_back(make_zstd(-3));
    codecs.push_back(make_zstd(-1));
    codecs.push_back(make_zstd(0));
    codecs.push_back(make_zstd(1));
    codecs.push_back(make_zstd(3));
    codecs.push_back(make_zstd(9));
    codecs.push_back(make_zstd(19));
#ifdef LZ4_FOUND
    codecs.push_back(make_lz4_fast());
    codecs.push_back(make_lz4_hc(9));
    codecs.push_back(make_lz4_hc(12));
#endif
#ifdef SNAPPY_FOUND
    codecs.push_back(make_snappy());
#endif
#ifdef BROTLI_FOUND
    codecs.push_back(make_brotli(0));
    codecs.push_back(make_brotli(1));
    codecs.push_back(make_brotli(6));
    codecs.push_back(make_brotli(11));
#endif
    codecs.push_back(make_fastlz(1));
    codecs.push_back(make_fastlz(2));
#ifdef ZLIB_FOUND
    codecs.push_back(make_zlib(1));
    codecs.push_back(make_zlib(6));
    codecs.push_back(make_zlib(9));
#endif
    return codecs;
}

// ---------------------------------------------------------------------------
// Workload generators
// ---------------------------------------------------------------------------
struct Workload {
    std::string name;
    std::string description;
    std::vector<std::vector<uint8_t>> buffers;
    // Workload-intrinsic entropy stats (computed once at construction).
    // These represent the theoretical floor that NO lossless codec can
    // beat, regardless of speed or sophistication.
    double entropy_bits_per_byte_mean = 0.0;  // Shannon H, averaged over buffers
    double entropy_floor_bytes_mean    = 0.0;  // H * 4096 / 8, averaged
    double entropy_floor_bytes_p50     = 0.0;  // median per-buffer floor
    double nonzero_pct_p50             = 0.0;  // median % of non-zero bytes
};

// Populate the entropy fields on a freshly-built Workload.
// Call once after `buffers` is fully populated.
void compute_entropy_stats(Workload& wl) {
    if (wl.buffers.empty()) return;
    std::vector<double> H_per_buf;
    std::vector<double> nz_per_buf;
    H_per_buf.reserve(wl.buffers.size());
    nz_per_buf.reserve(wl.buffers.size());
    double H_sum = 0.0, floor_sum = 0.0;
    for (const auto& b : wl.buffers) {
        double H = shannon_entropy_bits_per_byte(b.data(), b.size());
        H_per_buf.push_back(H);
        H_sum += H;
        floor_sum += H * static_cast<double>(b.size()) / 8.0;
        size_t nz = 0;
        for (uint8_t x : b) if (x != 0) ++nz;
        nz_per_buf.push_back(100.0 * static_cast<double>(nz) /
                              static_cast<double>(b.size()));
    }
    std::sort(H_per_buf.begin(), H_per_buf.end());
    std::sort(nz_per_buf.begin(), nz_per_buf.end());
    size_t mid = H_per_buf.size() / 2;
    wl.entropy_bits_per_byte_mean = H_sum / wl.buffers.size();
    wl.entropy_floor_bytes_mean    = floor_sum / wl.buffers.size();
    wl.entropy_floor_bytes_p50     = H_per_buf[mid] * kSubPageSize / 8.0;
    wl.nonzero_pct_p50             = nz_per_buf[mid];
}

// Load REAL codec-input buffers extracted from a .ttd file.
// Returns true on success. On failure, logs to stderr and returns false
// (the caller can then skip registering the real-data workloads).
//
// The blob format is documented in extract_real_buffers.py.
bool load_real_buffers(std::vector<std::vector<uint8_t>>& full_out,
                       std::vector<std::vector<uint8_t>>& xor_out) {
    const char* path = std::getenv("TTD_REAL_BUFFERS");
    if (!path || !*path) path = kDefaultRealBuffersPath;
    std::ifstream f(path, std::ios::binary);
    if (!f) {
        std::fprintf(stderr,
                     "poc_codec_latency: could not open '%s' — "
                     "run tools/poc/01-ttd-compression/cpp/extract_real_buffers.py first.\n",
                     path);
        return false;
    }
    uint32_t hdr[6] = {};
    f.read(reinterpret_cast<char*>(hdr), sizeof(hdr));
    if (!f) {
        std::fprintf(stderr, "poc_codec_latency: short header read on '%s'\n", path);
        return false;
    }
    constexpr uint32_t kMagic = 0x54544442u;
    if (hdr[0] != kMagic) {
        std::fprintf(stderr,
                     "poc_codec_latency: bad magic 0x%08x on '%s' (expected 0x%08x)\n",
                     hdr[0], path, kMagic);
        return false;
    }
    if (hdr[1] != 1) {
        std::fprintf(stderr, "poc_codec_latency: unknown blob version %u\n", hdr[1]);
        return false;
    }
    if (hdr[2] != kSubPageSize) {
        std::fprintf(stderr,
                     "poc_codec_latency: blob sub_page_size=%u, expected %zu\n",
                     hdr[2], kSubPageSize);
        return false;
    }
    uint32_t n_full = hdr[3];
    uint32_t n_xor  = hdr[4];
    full_out.clear(); full_out.reserve(n_full);
    xor_out.clear();  xor_out.reserve(n_xor);
    for (uint32_t i = 0; i < n_full; ++i) {
        std::vector<uint8_t> b(kSubPageSize);
        f.read(reinterpret_cast<char*>(b.data()), kSubPageSize);
        if (!f) { std::fprintf(stderr, "short read on full[%u]\n", i); return false; }
        full_out.push_back(std::move(b));
    }
    for (uint32_t i = 0; i < n_xor; ++i) {
        std::vector<uint8_t> b(kSubPageSize);
        f.read(reinterpret_cast<char*>(b.data()), kSubPageSize);
        if (!f) { std::fprintf(stderr, "short read on xor[%u]\n", i); return false; }
        xor_out.push_back(std::move(b));
    }
    std::fprintf(stderr,
                 "poc_codec_latency: loaded %u full + %u xor real buffers from '%s'\n",
                 n_full, n_xor, path);
    return true;
}

static std::mt19937_64 g_rng(0xC0DEC0DEULL);

std::vector<uint8_t> make_random_4k() {
    std::vector<uint8_t> b(kSubPageSize);
    std::uniform_int_distribution<int> d(0, 255);
    for (size_t i = 0; i < kSubPageSize; ++i) b[i] = static_cast<uint8_t>(d(g_rng));
    return b;
}

std::vector<uint8_t> make_zero_4k() {
    return std::vector<uint8_t>(kSubPageSize, 0);
}

// A "XOR-delta" buffer represents what TTD's InternXor() actually hands
// to the compressor: it's `new_page XOR prev_page`, where prev_page and
// new_page are 95% identical. The XOR result is therefore 95% ZEROS
// (where the two pages matched) with 5% non-zero bytes at the dirty
// positions. THIS is the buffer the compressor sees.
//
// The baseline parameter is unused — kept in the signature only so the
// function can sit next to the other generators in the file.
std::vector<uint8_t> make_xor_sparse_5pct(const std::vector<uint8_t>& /*baseline*/) {
    std::vector<uint8_t> b(kSubPageSize, 0);  // start all-zero
    std::uniform_int_distribution<size_t> idx(0, kSubPageSize - 1);
    std::uniform_int_distribution<int> val(1, 255);  // avoid 0 (would be "no change")
    size_t dirty = kSubPageSize / 20;  // 5%
    for (size_t i = 0; i < dirty; ++i) b[idx(g_rng)] = static_cast<uint8_t>(val(g_rng));
    return b;
}

std::vector<uint8_t> make_xor_clustered_5pct(const std::vector<uint8_t>& /*baseline*/) {
    std::vector<uint8_t> b(kSubPageSize, 0);  // start all-zero
    std::uniform_int_distribution<size_t> idx(0, kSubPageSize - 16);
    std::uniform_int_distribution<int> val(1, 255);
    size_t runs = (kSubPageSize / 20) / 16;  // ~13 runs of 16 bytes
    for (size_t r = 0; r < runs; ++r) {
        size_t off = idx(g_rng);
        for (size_t i = 0; i < 16; ++i) b[off + i] = static_cast<uint8_t>(val(g_rng));
    }
    return b;
}

std::vector<Workload> build_workload_list() {
    std::vector<Workload> wls;

    // === REAL-DATA workloads (the actual TTD codec inputs) ===
    // These come first because they are the basis for the codec decision.
    // Synthetic workloads below serve only as reference shapes.
    std::vector<std::vector<uint8_t>> real_full, real_xor;
    if (load_real_buffers(real_full, real_xor)) {
        if (!real_full.empty()) {
            Workload wl; wl.name = "REAL_full";
            wl.description = "raw 4 KB page snapshots from active_demo.ttd";
            wl.buffers = std::move(real_full);
            compute_entropy_stats(wl);
            wls.push_back(std::move(wl));
        }
        if (!real_xor.empty()) {
            Workload wl; wl.name = "REAL_xor";
            wl.description = "real XOR-delta buffers from active_demo.ttd";
            wl.buffers = std::move(real_xor);
            compute_entropy_stats(wl);
            wls.push_back(std::move(wl));
        }
    }

    // === SYNTHETIC workloads (reference shapes only) ===
    {
        Workload wl; wl.name = "SYN_random_4k"; wl.description = "uniform random 4 KB";
        wl.buffers.reserve(kWorkloadBuffers);
        for (size_t i = 0; i < kWorkloadBuffers; ++i) wl.buffers.push_back(make_random_4k());
        compute_entropy_stats(wl);
        wls.push_back(std::move(wl));
    }
    {
        Workload wl; wl.name = "SYN_xor_sparse_5pct"; wl.description = "5% scattered XOR-delta";
        wl.buffers.reserve(kWorkloadBuffers);
        std::vector<uint8_t> base = make_random_4k();
        for (size_t i = 0; i < kWorkloadBuffers; ++i) wl.buffers.push_back(make_xor_sparse_5pct(base));
        compute_entropy_stats(wl);
        wls.push_back(std::move(wl));
    }
    {
        Workload wl; wl.name = "SYN_xor_clustered_5pct"; wl.description = "5% clustered XOR-delta";
        wl.buffers.reserve(kWorkloadBuffers);
        std::vector<uint8_t> base = make_random_4k();
        for (size_t i = 0; i < kWorkloadBuffers; ++i) wl.buffers.push_back(make_xor_clustered_5pct(base));
        compute_entropy_stats(wl);
        wls.push_back(std::move(wl));
    }
    {
        Workload wl; wl.name = "SYN_zero_4k"; wl.description = "all-zero 4 KB";
        wl.buffers.reserve(kWorkloadBuffers);
        for (size_t i = 0; i < kWorkloadBuffers; ++i) wl.buffers.push_back(make_zero_4k());
        compute_entropy_stats(wl);
        wls.push_back(std::move(wl));
    }

    // Print workload entropy summary on stderr so it lands above the
    // Google Benchmark tabular output. This is the workload-intrinsic
    // lower bound; any codec claiming a smaller compressed size than this
    // is either buggy or exploiting codec-specific framing tricks.
    std::fprintf(stderr, "\n");
    std::fprintf(stderr, "=== Workload Shannon entropy (theoretical compression floor) ===\n");
    std::fprintf(stderr, "%-22s %8s %10s %10s %10s %10s\n",
                 "workload",   "n_bufs", "H_mean",   "floor_mean", "floor_p50", "nz%_p50");
    std::fprintf(stderr, "%-22s %8s %10s %10s %10s %10s\n",
                 "-------",   "------", "------",   "----------", "----------", "-------");
    for (const auto& wl : wls) {
        std::fprintf(stderr, "%-22s %8zu %10.4f %10.1f %10.1f %10.3f\n",
                     wl.name.c_str(),
                     wl.buffers.size(),
                     wl.entropy_bits_per_byte_mean,
                     wl.entropy_floor_bytes_mean,
                     wl.entropy_floor_bytes_p50,
                     wl.nonzero_pct_p50);
    }
    std::fprintf(stderr, "\n");

    return wls;
}

// ---------------------------------------------------------------------------
// Benchmark
// ---------------------------------------------------------------------------
static void BM_CodecWorkload(benchmark::State& state,
                              const Codec& codec,
                              const Workload& wl) {
    size_t max_bound = 0;
    for (const auto& b : wl.buffers) max_bound = std::max(max_bound, codec.bound(b.size()));
    std::vector<uint8_t> comp(max_bound);
    std::vector<uint8_t> decomp(kSubPageSize);

    std::vector<double> enc_lat, dec_lat;
    uint64_t total_in_bytes = 0, total_enc_bytes = 0, total_dec_bytes = 0;
    uint64_t enc_failures = 0, dec_failures = 0;

    for (auto _ : state) {
        enc_lat.clear(); dec_lat.clear();
        total_in_bytes = total_enc_bytes = total_dec_bytes = 0;
        enc_failures = dec_failures = 0;
        enc_lat.reserve(wl.buffers.size());
        dec_lat.reserve(wl.buffers.size());

        for (const auto& b : wl.buffers) {
            auto t0 = std::chrono::steady_clock::now();
            size_t cn = codec.encode(b.data(), b.size(), comp.data(), comp.size());
            auto t1 = std::chrono::steady_clock::now();
            enc_lat.push_back(std::chrono::duration<double, std::nano>(t1 - t0).count());

            if (cn == 0) { ++enc_failures; continue; }
            total_in_bytes  += b.size();
            total_enc_bytes += cn;

            auto t2 = std::chrono::steady_clock::now();
            size_t dn = codec.decode(comp.data(), cn, decomp.data(), decomp.size());
            auto t3 = std::chrono::steady_clock::now();
            dec_lat.push_back(std::chrono::duration<double, std::nano>(t3 - t2).count());

            if (dn == 0) ++dec_failures;
            else total_dec_bytes += dn;
        }
    }

    auto stats = [](std::vector<double>& v) -> std::array<double, 4> {
        if (v.empty()) return {0, 0, 0, 0};
        std::sort(v.begin(), v.end());
        auto pct = [&](double p) {
            size_t idx = static_cast<size_t>(p * (v.size() - 1));
            return v[idx];
        };
        double sum = 0;
        for (double x : v) sum += x;
        return { sum / v.size(), pct(0.50), pct(0.95), pct(0.99) };
    };
    auto es = stats(enc_lat);
    auto ds = stats(dec_lat);

    state.counters["enc_us_mean"] = es[0] / 1000.0;
    state.counters["enc_us_p50"]  = es[1] / 1000.0;
    state.counters["enc_us_p95"]  = es[2] / 1000.0;
    state.counters["enc_us_p99"]  = es[3] / 1000.0;
    state.counters["dec_us_mean"] = ds[0] / 1000.0;
    state.counters["dec_us_p50"]  = ds[1] / 1000.0;
    state.counters["dec_us_p95"]  = ds[2] / 1000.0;
    state.counters["dec_us_p99"]  = ds[3] / 1000.0;

    double total_enc_s = es[0] * enc_lat.size() / 1e9;
    double total_dec_s = ds[0] * dec_lat.size() / 1e9;
    if (total_enc_s > 0)
        state.counters["enc_MBps"] = (total_in_bytes / (1024.0 * 1024.0)) / total_enc_s;
    if (total_dec_s > 0)
        state.counters["dec_MBps"] = (total_dec_bytes / (1024.0 * 1024.0)) / total_dec_s;

    if (total_in_bytes > 0)
        state.counters["BLI"] = static_cast<double>(total_enc_bytes) / total_in_bytes;

    // Distance to the Shannon entropy floor (lower = closer to perfect).
    // BLI is bytes-out / bytes-in. The floor is bytes-out-min / bytes-in.
    // Ratio = BLI / (floor_min / in) = enc_bytes / floor_min_bytes.
    // A ratio of 1.0 means the codec matches the theoretical floor.
    // Ratios below 1.0 indicate codec framing overhead (header bytes
    // the floor doesn't account for); they should be tiny on 4 KB buffers.
    if (wl.entropy_floor_bytes_mean > 0.0) {
        // Per-iteration floor across all buffers that actually encoded.
        double floor_total = wl.entropy_floor_bytes_mean * wl.buffers.size();
        if (floor_total > 0.0) {
            state.counters["floor_B"]   = floor_total / wl.buffers.size();
            state.counters["BLI/floor"] = static_cast<double>(total_enc_bytes) / floor_total;
        }
    }

    if (enc_failures > 0) state.counters["enc_fail"] = enc_failures;
    if (dec_failures > 0) state.counters["dec_fail"] = dec_failures;
}

// ---------------------------------------------------------------------------
// Register all (codec x workload) combinations.
// ---------------------------------------------------------------------------
void register_benchmarks() {
    static auto codecs = build_codec_list();
    static auto workloads = build_workload_list();

    for (const auto& wl : workloads) {
        for (const auto& c : codecs) {
            std::string name = "BM_" + wl.name + "/" + c.name;
            benchmark::RegisterBenchmark(name.c_str(), BM_CodecWorkload, c, wl)
                ->Unit(benchmark::kMicrosecond)
                ->MinTime(1.0)
                ->UseRealTime();
        }
    }
}

}  // namespace

int main(int argc, char** argv) {
    register_benchmarks();
    benchmark::Initialize(&argc, argv);
    if (benchmark::ReportUnrecognizedArguments(argc, argv)) return 1;
    benchmark::RunSpecifiedBenchmarks();
    benchmark::Shutdown();
    return 0;
}
