#!/usr/bin/env python3
"""
Runs the independent Python Z80 reference model against all 163 z80test
vectors (loaded from z80test_vectors.h, the same source the C++ gtest
runner uses) and checks CRC + iteration count.

Usage:
    python3 run_verification.py                  # full ordered run (default)
    python3 run_verification.py --diff           # on failure, diff first
                                                   # mismatching iteration
                                                   # against the C++ ground-
                                                   # truth CSV (see below)
    python3 run_verification.py --test "LDI"      # run a single test in
                                                   # isolation (fresh memory
                                                   # — see the note below)

A full run (no --test) replays every vector through *one* persistent
SharedMemory image, in the same fixed order z80test_vectors.h lists them,
exactly like z80test_runner.cpp's RunAllVectors drives one shared emulator
instance across all 163 vectors. That matters: a few tests (POP+PUSH AF,
and indexed tests hit by a displacement-shift iteration) read memory that
was never explicitly initialized for *that* test — its content is whatever
an earlier test in the sequence left behind. Running such a test with
--test alone uses a fresh, empty memory instead, so it will disagree with
the full-run CRC; that's expected, not a bug.

The --diff CSVs are ground truth generated by the *verified* C++ emulator
(already proven against real Zilog hardware CRCs), via:

    ./cmake-build-agent-release/bin/core-tests --gtest_also_run_disabled_tests \\
        --gtest_filter="Z80TestVerification.DISABLED_GenerateReferenceCSVs"

which writes tools/verification/z80/reference/<index>_<name>.csv (gitignored
scratch, regenerate on demand).
"""

import argparse
import csv
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from vectors_loader import load_vectors
from iterator import Z80TestIterator, crc32_update
import z80_reference as ref

REPO_ROOT = Path(__file__).resolve().parents[5]
REFERENCE_CSV_DIR = REPO_ROOT / "tools/verification/z80/reference"

# Non-Zilog CPU flavors — the only vectors this model can never reproduce,
# matches z80test_runner.cpp's blacklist exactly.
BLACKLIST = ref.OUT_OF_SCOPE


def csv_filename(index, name):
    filename = name
    for ch in " ,()[]+'":
        filename = filename.replace(ch, "_")
    filename = filename.replace("/", "-")
    return f"{index}_{filename}.csv"


def find_first_mismatch(vec, index, memory):
    path = REFERENCE_CSV_DIR / csv_filename(index, vec["name"])
    if not path.exists():
        return None, f"(no CSV at {path})"

    it = Z80TestIterator(vec["base"], vec["counter"], vec["shifter"])
    with open(path, newline="") as f:
        reader = csv.reader(f)
        next(reader, None)  # header
        for iter_num, (combined, row) in enumerate(zip(it, reader)):
            expected_f = int(row[1], 16)
            ref.setup_iteration_memory(memory, combined, vec["base"])
            s = ref.Z80.from_vec(combined, memory)
            ref.EXEC[vec["name"]](s, combined)
            actual_f = s.f & 0xFF
            if actual_f != expected_f:
                opcode = combined[0]
                detail = f"opcode=0x{opcode:02X}"
                if opcode in (0xDD, 0xFD, 0xED, 0xCB):
                    detail += f" 0x{combined[1]:02X}"
                return iter_num, (
                    f"iter {iter_num}: actual=0x{actual_f:02X} "
                    f"expected=0x{expected_f:02X} "
                    f"(diff=0x{actual_f ^ expected_f:02X}) {detail}"
                )
    return None, "no per-iteration mismatch found (CRC computation issue?)"


def run_vector(vec, memory):
    if not ref.has_executor(vec["name"]):
        return "NO_EXECUTOR", None, None

    it = Z80TestIterator(vec["base"], vec["counter"], vec["shifter"])
    crc = 0xFFFFFFFF
    iterations = 0
    for combined in it:
        f_out = ref.execute_test(vec["name"], combined, vec["base"], memory=memory)
        crc = crc32_update(crc, f_out & 0xFF)
        iterations += 1

    crc_match = crc == vec["expected_crc"]
    iter_match = iterations == vec["expected_iterations"]
    if crc_match and iter_match:
        return "PASS", None, None

    detail = (
        f"CRC: 0x{crc:08X} (expected 0x{vec['expected_crc']:08X}), "
        f"iterations: {iterations} (expected {vec['expected_iterations']})"
    )
    return "FAIL", detail, None


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--diff", action="store_true")
    parser.add_argument("--test", default=None)
    args = parser.parse_args()

    vectors = load_vectors()
    passed = failed = skipped = no_exec = 0

    # One shared memory image for the whole run — see module docstring.
    # A --test run gets a private, fresh one (isolation is the point there).
    memory = ref.SharedMemory()

    for index, vec in enumerate(vectors):
        if args.test and vec["name"] != args.test:
            continue
        if vec["name"] in BLACKLIST:
            skipped += 1
            continue

        run_memory = ref.SharedMemory() if args.test else memory
        status, detail, _ = run_vector(vec, run_memory)
        if status == "PASS":
            passed += 1
        elif status == "NO_EXECUTOR":
            no_exec += 1
            print(f"NO EXECUTOR: {vec['name']}")
        else:
            failed += 1
            msg = f"FAIL: {vec['name']}\n    {detail}"
            if args.diff:
                _, mismatch_detail = find_first_mismatch(vec, index, run_memory)
                msg += f"\n    {mismatch_detail}"
            print(msg)

    total = passed + failed + no_exec
    print()
    print(f"Passed: {passed}/{total}")
    print(f"Failed: {failed}/{total}")
    print(f"No executor: {no_exec}/{total}")
    print(f"Skipped: {skipped} (non-Zilog CPU flavor tests)")

    sys.exit(0 if failed == 0 and no_exec == 0 else 1)


if __name__ == "__main__":
    main()
