"""Symbol dictionary and educational comments for scorpion.rom page 2.

Service monitor v2.x (base).  Sisters: scorp295.rom p2 (v2.95) and
scorp_prof401.rom p2 (v4.01) share this code base with relocations.
"""

# ---------------------------------------------------------------------------
# Symbols fed to z80dasm --sym-input.  ROM code labels first, RAM workspace
# equates last (z80dasm happily substitutes RAM addresses into operands).
# ---------------------------------------------------------------------------
SYMBOLS = [
    # --- RST / hardware vector stub -------------------------------------
    (0x0000, 'WriteAnyBankByte'),
    (0x0008, 'Rst08Vector'),
    (0x0010, 'Rst10Vector'),
    (0x0018, 'Rst18Vector'),
    (0x0020, 'Rst20Vector'),
    (0x0028, 'ReadAnyBankByte'),
    (0x0030, 'Rst30Vector'),
    (0x0038, 'Rst38Vector'),
    (0x003B, 'ColdStart'),
    (0x0066, 'NmiVector'),
    (0x0069, 'SoftEntry'),
    (0x006C, 'ProbeTail'),
    (0x0092, 'IntHandler'),
    (0x009C, 'WarmEntry'),
    (0x00B6, 'MonitorEntry'),
    (0x00FC, 'XorDecodeKeys'),
    # --- low core: AY, context, cross-bank access -----------------------
    (0x02DC, 'RamExtCall'),
    (0x02F0, 'AyReadRegister'),
    (0x030E, 'AyReadData'),
    (0x031A, 'AyWriteData'),
    (0x0326, 'SaveContext'),
    (0x0411, 'ReadPort7FFD'),
    (0x0415, 'ReadPort1FFD'),
    (0x04A6, 'SwapScreenBanks'),
    (0x04D9, 'PeekPokeAnyBank'),
    (0x054E, 'FatalHalt'),
    (0x0553, 'ShortDelay'),
    (0x0564, 'InventoryHardware'),
    (0x05A2, 'DecodeTables'),
    (0x0646, 'CopyAcrossBanks'),
    (0x07BA, 'KeyJumpTable'),
    (0x084D, 'FeedTapeOutput'),
    (0x08A6, 'MouseDriver'),
    # --- command interpreter --------------------------------------------
    (0x0A54, 'ExitToError'),
    (0x0A8A, 'ParseCommand'),
    (0x0B59, 'DispatchMode'),
    (0x0E36, 'FindKeyword'),
    (0x0F7B, 'ReportError'),
    (0x0FC1, 'BootContinue'),
    (0x101E, 'EnterTrdos'),
    (0x116A, 'SetErrorTables'),
    # --- debugger core ---------------------------------------------------
    (0x136F, 'EvalOperand'),
    (0x139E, 'CheckRangeInclusive'),
    (0x13A3, 'SetDefaultWorkspace'),
    (0x13A6, 'SetWorkspace'),
    (0x13B5, 'ScanTokens'),
    (0x13E2, 'CommandLoop'),
    (0x14AB, 'ShowRegisters'),
    (0x1531, 'RegisterNameTable'),
    (0x1578, 'MemoryDumpWindow'),
    (0x1604, 'HexDumpRow'),
    (0x15C8, 'PositionCursor'),
    (0x15E7, 'ScrollWindow'),
    (0x1668, 'DisasmWindow'),
    (0x169B, 'DisasmLine'),
    (0x16B1, 'FetchPrefixBytes'),
    (0x1708, 'PadColumns'),
    (0x1716, 'AutoRepeatKey'),
    (0x177C, 'CharClasses'),
    (0x1798, 'Disassemble'),
    (0x185F, 'ScanQuotedString'),
    (0x1893, 'PrintBit7Chars'),
    (0x189C, 'PrintJustifiedHeader'),
    (0x18D2, 'PrintMarkerChar'),
    (0x18E6, 'PickNumberBase'),
    (0x1918, 'PrintDecimal'),
    (0x196A, 'Divide16'),
    (0x1990, 'Rst20Handler'),
    (0x199E, 'PrintHexWord'),
    (0x19A3, 'PrintHexByte'),
    (0x19BF, 'PrintExtMenu'),
    (0x19DB, 'PrepareStep'),
    (0x1A65, 'SwapAltRegs'),
    (0x1AA0, 'ToggleAltDisplay'),
    (0x1AB3, 'BuildStepStub'),
    (0x1B1F, 'StepDispatch'),
    (0x1BCE, 'SetTempBreakpoint'),
    (0x1BE9, 'CheckTrace'),
    (0x1C0E, 'AnalyzeInstruction'),
    (0x1D56, 'CollectAsmText'),
    (0x1D7A, 'EditorKeyLoop'),
    (0x1E6A, 'EditorRegKeys'),
    (0x1FCA, 'WordToHexBuf'),
    (0x1FF5, 'FindBreakpoint'),
    # --- tables (data) ---------------------------------------------------
    (0x2012, 'MnemonicTable'),
    (0x21D7, 'OpcodeClassTable'),
    (0x23BB, 'EditorKeyTable'),
    (0x23EB, 'RegisterKeyTable'),
    # --- window engine ----------------------------------------------------
    (0x2422, 'GlyphAddr'),
    (0x24B1, 'SaveCursorCell'),
    (0x24E1, 'RestartCursorBlink'),
    (0x24EF, 'BlinkCursor'),
    (0x2528, 'WindowAddr'),
    (0x2566, 'AttrAddr'),
    (0x2579, 'BitmapAddr'),
    (0x258B, 'ScrollUp'),
    (0x25CD, 'CopyCharRow'),
    (0x25F8, 'CopyAttrRow'),
    (0x2618, 'ScrollDown'),
    (0x2658, 'FillWindow'),
    (0x2677, 'FillWholeRow'),
    (0x2682, 'FillRowToEnd'),
    (0x26AA, 'PrinterPutChar'),
    (0x26B3, 'PopAllRet'),
    (0x26B7, 'PrintCharBit7'),
    (0x26BC, 'PrintSpace'),
    (0x26BE, 'PrintChar'),
    (0x26C4, 'DispatchOutput'),
    (0x270F, 'InstallPrintHook'),
    (0x2717, 'WindowNewline'),
    (0x2746, 'WindowHome'),
    (0x2751, 'KeyClick'),
    # --- commands and helpers ---------------------------------------------
    (0x2846, 'FillMemoryRange'),
    (0x2859, 'ChecksumLoop'),
    (0x295E, 'PrintOkError'),
    (0x296D, 'LookupCommand'),
    (0x297F, 'CheckWatchpoints'),
    (0x29C9, 'InitWatchTable'),
    (0x29E8, 'FindWatchpoint'),
    (0x2B5F, 'OpenPopup'),
    (0x2B6B, 'TapeMenu'),
    (0x2C6C, 'SearchPattern'),
    (0x2D80, 'SavePagingShadow'),
    (0x2D8C, 'RestorePagingShadow'),
    (0x2E23, 'CmdInterruptState'),
    (0x2E7E, 'ScreenBankCheck'),
    (0x2E91, 'CalcPagingPorts'),
    (0x2ED0, 'CheckAddressRange'),
    (0x2F99, 'DecodeXorTable'),
    (0x2FBF, 'RunCommand'),
    (0x2FFD, 'BreakpointSlot'),
    (0x3025, 'AddBreakpoint'),
    (0x3055, 'ListBreakpoints'),
    (0x3105, 'ArmWatchpoint'),
    (0x3474, 'ReadNmiPort'),
    (0x347D, 'PrintFrameCount'),
    (0x34A8, 'LookupToken'),
    (0x3557, 'CallTrdos'),
    (0x3584, 'RestorePaging'),
    (0x358D, 'SaveToTape'),
    (0x35CB, 'InitErrorWindow'),
    (0x35F4, 'ErrorWindowHook'),
    (0xF5E0, 'BootConfigTable'),
    (0xFCA0, 'Font6x8'),
    # --- RAM workspace equates (bank 0 at $C000 while monitor runs) -------
    (0xC001, 'RamMagic1'),
    (0xC002, 'RamMagic2'),
    (0xC064, 'BootCounter'),
    (0xC069, 'MonitorScreen'),
    (0xDD6B, 'UserPc'),
    (0xDD6D, 'UserSp'),
    (0xDD73, 'RegisterFile'),
    (0xDD83, 'UserIff'),
    (0xDD85, 'UserI'),
    (0xDD86, 'UserIm'),
    (0xDD99, 'RegisterBackup'),
    (0xDDD0, 'StepPc'),
    (0xDDD4, 'BreakCount'),
    (0xDDD6, 'BreakTable'),
    (0xDDD8, 'ErrorTextTable'),
    (0xDDDA, 'ErrorTextTable2'),
    (0xDFD7, 'AyShadowReg'),
    (0xDFD8, 'LastKeyCode'),
    (0xDFDD, 'PagingState'),
    (0xDFDB, 'PagingBackup'),
    (0xDFDF, 'IyWorkBase'),
    (0xDFF1, 'StepFlags'),
    (0xE000, 'KeyState'),
    (0xE035, 'PromptWindowDef'),
    (0xE051, 'DisasmWindowDef'),
    (0xE05F, 'WorkBuffer'),
    (0xE06D, 'PopupWindowDef'),
    (0xE089, 'RegWindowDef'),
    (0xE0AA, 'StepContext'),
    (0xE2B5, 'MonitorStack'),
    (0xE2B7, 'StepStub'),
    (0xE2C1, 'CursorCellSave'),
    (0xE2D4, 'WorkBufferPtr'),
    (0xE358, 'RamExtDispatcher'),
    (0xE373, 'RamExtTarget'),
    (0xE394, 'WatchTable'),
    (0xE7F7, 'ExtMenuTable'),
    (0xE80B, 'CommandTable'),
    (0xE82D, 'DecodedTables'),
    (0xE928, 'HwConfigTable'),
]

# ---------------------------------------------------------------------------
# File banner prepended verbatim by gen.py (lines already carry their own ';').
# ---------------------------------------------------------------------------
HEADER = [
    '; ============================================================================',
    ';  Scorpion ZS-256 Turbo - SERVICE MONITOR  (page 2 of scorpion.rom)',
    '; ============================================================================',
    ';',
    ';  Source   : data/rom/scorpion.rom, bytes $8000-$BFFF (page 2), 16 KiB',
    ';  Family   : Scorpion service monitor, v2.x ("base")',
    ';  Sisters  : scorp295.rom      p2 = v2.95  (boot ROM checksum, code moved),',
    ';             scorp_prof401.rom p2 = v4.01 (ProfRAM layout, RAM hooks).',
    ';  Method   : z80dasm 1.2.0, code/data block map from a dedicated',
    ';             Z80 length-decoder + reachability analysis; labels and',
    ';             comments added by hand after studying the three listings.',
    ';  Style    : educational, after Logan & O\'Hara, "The Complete Spectrum',
    ';             ROM Disassembly" (see docs/rom for the inspiration).',
    ';',
    '; ----------------------------------------------------------------------------',
    ';  THE ROM BUNDLE',
    '; ----------------------------------------------------------------------------',
    ';  scorpion.rom is a 64 KiB bundle of four 16 KiB pages.  Hash comparison',
    ';  against data/rom/*.rom shows the real contents (page numbers here are',
    ';  offsets inside the bundle file, NOT the emulator\'s slot numbering):',
    ';',
    ';    page 0 ($0000-)  patched standard 128K ROM0 (~290 bytes differ from',
    ';                     128.rom - TR-DOS autorun patches)',
    ';    page 1 ($4000-)  patched 48K BASIC ROM (~115 bytes differ from',
    ';                     sos.rom - same autorun patch family)',
    ';    page 2 ($8000-)  THIS service monitor (machine-code debugger)',
    ';    page 3 ($C000-)  TR-DOS 5.03 variant (strings identical to dos.rom,',
    ';                     ~4.7K of bytes differ - Scorpion adaptations)',
    ';',
    ';  NOTE: core/src/emulator/memory/rom.cpp maps MM_SCORP slots as',
    ';  sys=p0/dos=p1/128=p2/sos=p3 - inverted with respect to this bundle.',
    ';',
    '; ----------------------------------------------------------------------------',
    ';  PAGING AS THE MONITOR USES IT',
    '; ----------------------------------------------------------------------------',
    ';  #7FFD  bit 4 = 0 selects RAM bank 0 at $C000; bank bits select the',
    ';         RAM bank.  The monitor keeps $10 here while it runs, so its',
    ';         workspace in bank 0 ($C000-$FFFF) stays visible.',
    ';  #1FFD  Scorpion extension port.  The monitor writes $12 to map itself',
    ';         (service page visible in the low 16K), $02 around TR-DOS',
    ';         sessions, and $10/$12 pairs to restore.  Exact hardware',
    ';         priority of the bits is not fully modelled here - wording',
    ';         below sticks to the values actually written.',
    ';',
    '; ----------------------------------------------------------------------------',
    ';  MONITOR RST API  (stub at $0000-$0038, identical in all versions)',
    '; ----------------------------------------------------------------------------',
    ';    RST 00h  write one byte through the banked window (carry = 1)',
    ';    RST 08h  report error, code in B',
    ';    RST 10h  print character in A',
    ';    RST 18h  RAM-extension call: inline 16-bit target -> (RamExtTarget),',
    ';             then JP through the RAM dispatcher at (RamExtDispatcher)',
    ';    RST 20h  print inline bit-7-terminated message (EX (SP),HL trick)',
    ';    RST 28h  read one byte through the banked window (carry = 0)',
    ';    RST 30h  set IX work buffer from HL (default $E05F via $13A3)',
    ';    RST 38h  INT: short timed loop, then EI: RET',
    ';    NMI      magic-button entry -> context save -> monitor',
    ';',
    '; ----------------------------------------------------------------------------',
    ';  RAM WORKSPACE (bank 0, visible at $C000 while the monitor runs)',
    '; ----------------------------------------------------------------------------',
    ';    $C001/$C002  power-on magic bytes ($55/$AA) - warm/cold boot test',
    ';    $C064        boot pass counter (non-zero = warm boot)',
    ';    $C069-$DB09  monitor own screen buffer (64 column, 6x8 font)',
    ';    $DD6B/$DD6D  user PC / user SP mirrors (context block)',
    ';    $DD73-$DD81  register file: HL,DE,BC,AF,IX,IY,SP (see SaveContext)',
    ';    $DD83/$DD85/$DD86   user IFF2 / I / IM state',
    ';    $DD99+       register backup used by single-step',
    ';    $DDD0        step PC,  $DDD4/$DDD6 breakpoint count/table',
    ';    $DDD8/$DDDA  error message table pointers',
    ';    $DFD7/$DFD8  AY mirror / last key code',
    ';    $DFDD        paging mirror (E = last #7FFD, D = last #1FFD value)',
    ';    $DFDB        paging shadow for TR-DOS trips',
    ';    $DFDF        IY base for the monitor\'s flags (IY+$00..$16)',
    ';    $E000-$E00C  keyboard state for auto-repeat',
    ';    $E035/$E051/$E06D/$E089  window descriptors (prompt, disasm, popup,',
    ';                              registers) - IX-relative blocks',
    ';    $E05F        default IX work buffer (RST 30h target)',
    ';    $E0AA        step context copy, $E2B7 step trampoline buffer',
    ';    $E2B5        monitor SP,  $E2C1 cursor cell save (16 bytes)',
    ';    $E358/$E373  RAM-extension dispatcher / pending target',
    ';    $E394        watchpoint table: 8 entries x 11 bytes',
    ';    $E7F7        extension menu table (calls RAM code at $EB06)',
    ';    $E80B        command table (2-byte entries, see RunCommand)',
    ';    $E82D        tables decoded at boot from ROM by DecodeXorTable',
    ';    $E928        hardware configuration table (filled by inventory)',
    ';',
    ';  All page-2 addresses in the comments below are offsets in this 16 KiB',
    ';  block (z80dasm origin $0000).  Labels are PascalCase per project rules.',
    ';',
    ';  Trailing data at the end of the page: the boot configuration table',
    ';  (BootConfigTable, $F5E0 - a RAM-side copy is built by DecodeTables)',
    ';  and the monitor\'s own 6x8 font (Font6x8, $FCA0, 8 bytes per glyph)',
    ';  run up to $3FFF.',
    ';',
]

# ---------------------------------------------------------------------------
# Educational comment blocks, keyed by ROM address.  gen.py inserts each
# block above the first instruction at that address.
# ---------------------------------------------------------------------------
COMMENTS = [
    (0x0000, [
        'RST 00h - WRITE one byte through the banked window.',
        'SCF presets carry=1; the shared engine at PeekPokeAnyBank ($04D9)',
        'treats carry as "write".  Twin: RST 28h below enters with carry',
        'clear = READ.  H bits 6/7 select the window (see $04D9).',
    ]),
    (0x0008, [
        'RST 08h - report the error whose code is in B (ReportError $0F7B).',
    ]),
    (0x0010, [
        'RST 10h - print the character in A (PrintChar $26BE).',
    ]),
    (0x0018, [
        'RST 18h - RAM-extension call (RamExtCall $02DC): the 16-bit target',
        'sits inline after the RST at the call site; dispatch goes through',
        'the RAM vector at (RamExtDispatcher).',
    ]),
    (0x0020, [
        'RST 20h - print inline message (Rst20Handler $1990): characters',
        'follow the call site, the last one carries bit 7 set.',
    ]),
    (0x0028, [
        'RST 28h - READ one byte through the banked window (OR A clears',
        'carry).  Same engine as RST 00h, opposite direction.',
    ]),
    (0x0030, [
        'RST 30h - set the IX work buffer from HL (SetWorkspace $13A6);',
        'callers wanting the default buffer enter at $13A3 instead.',
    ]),
    (0x0038, [
        'INT vector - timed spin then EI:RET (IntHandler $0092).',
    ]),
    (0x003B, [
        'Cold start - entered with the service page mapped (C=$FD assumed',
        'from the CPU reset state).  Zeroes #7FFD, sets scratch SP=$5BFF,',
        'then validates the RAM hardware table at HwConfigTable: each',
        'successive byte must equal the descending counter in B.  A',
        'mismatch (cold RAM, garbage tables) drops to $007B - inventory,',
        'window setup, interrupt-mode probe - after which BootContinue',
        'and the $006C tail re-validate with B=$1F until the boot state',
        'settles (warm/cold arbitration also lives at MonitorEntry).',
    ]),
    (0x006C, [
        'Probe tail / re-validation: B=$1F, the IM0 acknowledge pattern',
        '($C7 = RST 00h opcode, or $ED) is pushed and #1FFD cleared before',
        'the table walk is restarted at $0047 (inference from code shape).',
    ]),
    (0x0092, [
        'INT handler: A=0 then a DJNZ spin (timing), D bumped, EI, RET.',
        'Serves the $0038 vector and releases every HALT of the IM probe.',
    ]),
    (0x009C, [
        'Warm entry (NMI / magic button).  Builds the interrupted context',
        'frame: return address bookkeeping pushed, subtype byte $08, BC',
        'and HL stacked, magic bytes $55/$AA stamped at RamMagic1/2.',
        'Then DI, #1FFD=$12 + #7FFD=$10 (monitor mapping), user SP parked',
        'at UserSp, monitor SP=$E2B5 installed; the boot counter at',
        'BootCounter decides between the full save below ($00D4) and a',
        'quick re-entry.',
    ]),
    (0x00B6, [
        'Monitor main entry: DI; #1FFD=$12 pages the service monitor;',
        '#7FFD=$10 puts RAM bank 0 at $C000 (monitor workspace).  User',
        'SP -> UserSp, monitor stack $E2B5 installed.  BootCounter==0',
        '-> full SaveContext + register/IM analysis chain; otherwise the',
        'dispatch is entered directly.',
    ]),
    (0x00FC, [
        'XorKeys: private key bytes for DecodeXorTable ($2F99); several',
        'ROM tables are stored XOR-masked and are unmasked into RAM at boot.',
    ]),
    (0x02DC, [
        'RamExtCall - RST 18h backend.  EX (SP),HL lifts the inline',
        '16-bit address that follows the RST, parks it at RamExtTarget,',
        'restores the caller HL and dispatches through the RAM vector at',
        '(RamExtDispatcher).  RAM extensions may re-point either cell.',
    ]),
    (0x02F0, [
        'AY-3-8910 helpers: register select on #FFFD, data on #BFFD.',
        'AyReadRegister keeps the last value mirrored at AyShadowReg;',
        'AyWriteData ($031A) restores from that mirror.  Register 7',
        'doubles as input port (mouse buttons, hardware probes).',
    ]),
    (0x0326, [
        'SaveContext - snapshot the interrupted CPU.  AF, AF\' (ex af',
        'twice), then BC/DE/HL of both sets, IY, IX are pushed onto the',
        'context stack below $DD83; IY <- IyWorkBase (monitor flags).',
        'The user PC is recovered from the stack, user SP derived (+11',
        'stacked words), registers copied to RegisterFile and the backup',
        'at RegisterBackup, I and IM captured (IM decoded from the',
        'stacked I byte), paging mirror updated, monitor mapping',
        '($12/$10) re-asserted.  v2.95/prof additionally beep here.',
    ]),
    (0x0411, [
        'Read the paging ports back: Scorpion #7FFD / #1FFD return their',
        'latched value (B=$7F / B=$1F with C=$FD).  Used by NMI/magic',
        'detection and by the step engine.',
    ]),
    (0x04A6, [
        'SwapScreenBanks - exchange the user screen at $4000 with the',
        'private monitor screen at MonitorScreen ($C069, $1B00 bytes) via',
        'LDIR under #7FFD bit-4 toggling; direction chosen by carry and',
        'the shadow-screen flag (IY+12 bit 3).',
    ]),
    (0x04D9, [
        'PeekPokeAnyBank - universal byte access; the engine behind RST 00h',
        '(carry=1, write) and RST 28h (carry=0, read).  H selects the',
        'window: bit 6 set -> banked RAM window (paging taken from the',
        'PagingState mirror, restored to $12/$10 afterwards); bit 7 set ->',
        'extended window (bank bits from mirror E, #1FFD <- (D&$10)|$02);',
        'neither -> plain (HL) access.  Shadow-screen flag routes $5B00+',
        'addresses through the monitor screen buffer.',
    ]),
    (0x054E, [
        'FatalHalt: border flash and HALT forever - end of a failed',
        'hardware inventory (bad RAM under the monitor).',
    ]),
    (0x0553, [
        'ShortDelay: calibrated A/E delay loops (tape and AY timing).',
    ]),
    (0x0564, [
        'InventoryHardware: probe the machine - read #1FFD, walk #7FFD',
        'bank values, verify RAM with a fill/compare, clear the monitor',
        'screen buffer - and leave the signature the cold-start walk at',
        '$0049 expects in HwConfigTable.  Any RAM failure -> FatalHalt.',
    ]),
    (0x05A2, [
        'DecodeTables: copy + XOR-unmask the coded ROM tables into RAM',
        '(DecodedTables at $E82D) using the keys at XorDecodeKeys;',
        'IX is then pointed at the boot configuration table copy.',
    ]),
    (0x0646, [
        'CopyAcrossBanks - LDIR with either side in a foreign bank:',
        'bytes travel one at a time through the bank window (PeekPoke-',
        'AnyBank style access); $4000-area sides go via the monitor',
        'screen buffer when the shadow-screen flag is set.  Used by all',
        'windows that display foreign memory (dumps, disassembly, sums).',
    ]),
    (0x07BA, [
        'KeyJumpTable - 16-bit handler addresses indexed by raw key code;',
        'the NMI-side scan (cf. $0205) computes HL=table+2*key and jumps',
        '(HL).  Unhandled keys share a common ignore entry.',
    ]),
    (0x084D, [
        'Tape output feeder: serialises bits to the tape port (OUT $FE',
        'border bit) with loop-timed pulses; drives SaveToTape.',
    ]),
    (0x08A6, [
        'MouseDriver: AY-port mouse - buttons sampled via AY register 7',
        'inputs, motion from the PSG counters; state kept in RAM.',
    ]),
    (0x0A54, [
        'ExitToError: unwind to the command loop through the error',
        'window path (cf. InitErrorWindow $35CB).',
    ]),
    (0x0A8A, [
        'ParseCommand: the command/expression reader.  Accepts a typed',
        'line into the IX work buffer, evaluates operands (bank extension',
        'syntax handled by EvalOperand at $136F) and reduces the input',
        'to tokens for DispatchMode.',
    ]),
    (0x0B59, [
        'DispatchMode: routes between line editor, disassembler and',
        'register views according to the monitor flags (IY+12/IY+16',
        'bits), then falls into CommandLoop for the next command.',
    ]),
    (0x0E36, [
        'FindKeyword: match (possibly abbreviated) input against the',
        'command/mnemonic token tables.',
    ]),
    (0x0F7B, [
        'ReportError - RST 08h backend, error code in B.  Walks the',
        'message table at (ErrorTextTable) with C as a rotating bit mask',
        '($80, sla per entry); bit 7 chain-loads sub-strings.  Codes',
        'without a table entry fall back to printing the number.',
    ]),
    (0x0FC1, [
        'BootContinue - boot bookkeeping at $C000..$C006: the signature',
        'must read byte i = i (walked down from $C006).  Broken -> RAM',
        're-initialised and control loops back to the cold path; intact',
        '-> pass counter bumped.  v2.95 adds a ROM checksum check here.',
    ]),
    (0x101E, [
        'EnterTrdos - boot into TR-DOS: prepares state through the',
        '$1177 helper, selects service 2 and issues a RST 18h RAM-',
        'extension call that hands control to the DOS page of this',
        'bundle (page 3).',
    ]),
    (0x116A, [
        'SetErrorTables: ErrorTextTable <- $3B7F (messages),',
        'ErrorTextTable2 <- $3818 (bit map).  RAM extensions can point',
        'these at custom error sets.',
    ]),
    (0x136F, [
        'EvalOperand: evaluate one command/assembler operand, including',
        'the bank-extended indirect syntax (addresses may carry a bank',
        'qualifier routed through PeekPokeAnyBank).',
    ]),
    (0x139E, [
        'CheckRangeInclusive: carry set when A lies within C..B',
        '(cp c / ret c, then cp b / ccf).  Validating addresses and',
        'command indices.',
    ]),
    (0x13A3, [
        'SetDefaultWorkspace: HL <- $E05F (WorkBuffer), then falls into',
        'SetWorkspace.  Convenience entry before window operations.',
    ]),
    (0x13A6, [
        'SetWorkspace - RST 30h backend: (WorkBufferPtr) <- HL and',
        'IX <- HL.  Window routines address their descriptors',
        'IX-relative, so this is how the monitor switches windows.',
    ]),
    (0x13B5, [
        'ScanTokens: compressed table walk - each entry matches one',
        'character and holds a 2-byte skip to the next node; the',
        'terminator entry yields an action address executed via',
        'jp (HL).  The command tokenizer of the monitor.',
    ]),
    (0x13E2, [
        'CommandLoop - the heart of the monitor: print the prompt in',
        'the E035 window, read a line through the editor, parse and',
        'execute it via the command table (RunCommand $2FBF), repeat.',
        'Errors funnel back here through ExitToError.',
    ]),
    (0x14AB, [
        'ShowRegisters: dump the saved context - register names are',
        'inline RST 20h strings at RegisterNameTable ($1531), values',
        'printed in the current number base; the flag byte comes out',
        'as eight binary digits.',
    ]),
    (0x1531, [
        'RegisterNameTable: inline register-name strings (bit-7',
        'terminated, printed by RST 20h) for the dump above.',
    ]),
    (0x1578, [
        'MemoryDumpWindow - the D-command view: default work buffer,',
        'scroll check, prompt-window cursor placement, then eight rows',
        'of HexDumpRow; the ASCII half re-fetches every byte across',
        'banks.',
    ]),
    (0x1604, [
        'HexDumpRow: one dump row - address word, 8 bytes in hex',
        '(fetched through the bank window), then the same 8 as ASCII.',
    ]),
    (0x15C8, [
        'PositionCursor: translate the dump address (DD87/DD89) into',
        'window cursor coordinates (IX+0/IX+1).',
    ]),
    (0x15E7, [
        'ScrollWindow: scroll the current window when the cursor is',
        'about to leave the bottom edge.',
    ]),
    (0x1668, [
        'DisasmWindow: the disassembly view.  Attributes through the',
        '$5831 copy, workspace E051; renders 5 lines (1 while',
        'stepping) from DD87/DD89, advancing by each decoded length.',
    ]),
    (0x169B, [
        'DisasmLine: disassemble one instruction and print it',
        '(address, opcode bytes, mnemonic via Disassemble).',
    ]),
    (0x16B1, [
        'FetchPrefixBytes: pull up to 4 opcode bytes for the',
        'disassembler across the bank window (DD/DDCB/FD/FDCB',
        'prefixes included).',
    ]),
    (0x1708, [
        'PadColumns: pad the listing to its fixed column layout.',
    ]),
    (0x1716, [
        'AutoRepeatKey: keys held down (state at KeyState, E000-E004)',
        'repeat with a ramp-up delay; feeds editor and dump windows.',
    ]),
    (0x177C, [
        'CharClasses: character-class predicates (hex digit,',
        'separator, ...) used by parsers and the disassembler.',
    ]),
    (0x1798, [
        'Disassemble - the mnemonic printer core.  Mnemonic strings',
        'sit in MnemonicTable ($2012) with high-bit placeholder',
        'characters marking where operands splice in; this walk',
        'decodes operands (16-bit, 8-bit, indexed, condition codes)',
        'and emits the line via RST 10h.',
    ]),
    (0x185F, [
        'ScanQuotedString: assembler string literals - backslash',
        'escapes and quotes handled while copying to the work buffer.',
    ]),
    (0x1893, [
        'PrintBit7Chars: print a string whose last character carries',
        'bit 7 (the RST 20h message convention).',
    ]),
    (0x189C, [
        'PrintJustifiedHeader: window headers padded to window width.',
    ]),
    (0x18D2, [
        'PrintMarkerChar: the listing marker column - "#" or a',
        'character derived from the address value (IY+05 bit 0',
        'selects the mode).',
    ]),
    (0x18E6, [
        'PickNumberBase: choose hex/decimal/binary presentation from',
        'the monitor flags before printing numbers.',
    ]),
    (0x1918, [
        'PrintDecimal: recursive divider method - DE=$000A, divide,',
        'print remainders (recursion state at IY+07).',
    ]),
    (0x196A, [
        'Divide16: 16-bit division helper behind all number output.',
    ]),
    (0x1990, [
        'Rst20Handler - print inline message: EX (SP),HL swaps the',
        'return address into HL (pointing at the inline text), prints',
        'until a bit-7 character, then stacks the corrected resume',
        'address - the classic ZX-ROM inline-print trick, on RST 20h.',
    ]),
    (0x199E, [
        'PrintHexWord / PrintHexByte ($19A3): nibble conversion via',
        'the DAA trick (add $90, daa, adc $40, daa per nibble).',
    ]),
    (0x19BF, [
        'PrintExtMenu: walk the extension menu table at ExtMenuTable',
        '($E7F7) calling the RAM hook at $EB06 per entry - the',
        'documented way for RAM extensions to add monitor commands.',
    ]),
    (0x19DB, [
        'PrepareStep: swap the register file with the step context at',
        'StepContext (E0AA), park the monitor SP at $E2B5, arm the',
        'trace enable (StepFlags bit 5), then let the class patchers',
        'below adjust the step context for the next instruction.',
    ]),
    (0x1AB3, [
        'BuildStepStub: build the one-instruction trampoline at',
        'StepStub (E2B7) - DI (or EI, per the saved user IFF, DD83',
        'bit 2), the instruction bytes fetched across banks, then $CF',
        '(RST 08) as the trap.  Running the stub executes exactly one',
        'user instruction with interrupts in their saved state.',
    ]),
    (0x1B1F, [
        'StepDispatch: after the trap - classify the executed',
        'instruction from the AnalyzeInstruction results (DDB4 area):',
        'HALT-like, jump taken, CALL entered, RET - and fix the saved',
        'user PC accordingly.  SetTempBreakpoint below makes CALLs',
        'stop at their callee.',
    ]),
    (0x1BCE, [
        'SetTempBreakpoint: plant CALL nnnn + RST 08 into the shadow',
        'context so stepping over a CALL breaks at the target.',
    ]),
    (0x1BE9, [
        'CheckTrace: trace-mode gate evaluated after every step.',
    ]),
    (0x1C0E, [
        'AnalyzeInstruction - the static analyser: opcode class (EB/',
        'DD/FD/76/CB handled), length and control-flow effect from',
        'OpcodeClassTable ($21D7); results returned through the stack',
        'frame (SP=$DDCB on return).  Feeds StepDispatch and the',
        'step-over/breakpoint logic.',
    ]),
    (0x1D56, [
        'CollectAsmText: capture assembler source from the editor',
        'into the work buffer.',
    ]),
    (0x1D7A, [
        'EditorKeyLoop: the line editor dispatcher - EditorKeyTable',
        '($23BB, CPIR-searched, 0x24 entries) maps keys to cursor',
        'moves, insert/delete and history actions.',
    ]),
    (0x1E6A, [
        'EditorRegKeys: register-edit keys (RegisterKeyTable $23EB)',
        '- hex entry into the highlighted register of the dump.',
    ]),
    (0x1FCA, [
        'WordToHexBuf: format HL as 4 hex characters (bit-7',
        'terminated) in the work buffer.',
    ]),
    (0x1FF5, [
        'FindBreakpoint: search BreakTable (DDD6, count at',
        'BreakCount DDD4) for an address.',
    ]),
    (0x2012, [
        'MnemonicTable: packed mnemonic strings; placeholder',
        'characters carry bit 7 and mark operand splice points.',
    ]),
    (0x21D7, [
        'OpcodeClassTable: class/length/control-flow bytes for every',
        'opcode (including the xxCB pages) - input to',
        'AnalyzeInstruction.',
    ]),
    (0x23BB, [
        'EditorKeyTable: key code -> editor action (see',
        'EditorKeyLoop $1D7A).',
    ]),
    (0x23EB, [
        'RegisterKeyTable: register-edit keys (see EditorRegKeys',
        '$1E6A).',
    ]),
    (0x2422, [
        'GlyphAddr: address of the 6x8 glyph for A in Font6x8 ($FCA0),',
        '8 bytes per character.',
    ]),
    (0x24B1, [
        'SaveCursorCell (+restore): the cursor spans 2 glyphs of a',
        '6-pixel cell; the 16 covered bytes are buffered at',
        'CursorCellSave (E2C1) and restored when the cursor moves.',
    ]),
    (0x24EF, [
        'BlinkCursor: toggle cursor visibility every $7D frames',
        '(counter at E2D3); draw/erase goes through the cell buffer.',
    ]),
    (0x2528, [
        'WindowAddr: window cursor (IX+0 row, IX+1 column) ->',
        'absolute screen address.  The 6-pixel font packs two glyphs',
        'per 8-pixel byte cell, so columns address 6-pixel units.',
    ]),
    (0x2566, [
        'AttrAddr: attribute address for the cursor position.',
    ]),
    (0x2579, [
        'BitmapAddr: bitmap address for the cursor position.',
    ]),
    (0x258B, [
        'ScrollUp: shift the window bitmap (and attributes, when the',
        'descriptor flag bit 1 is set) one row toward row 0, then blank',
        'the vacated bottom row via FillWholeRow.  Called by WindowNewline',
        'when the cursor sits on the last row - the classic text-scroll.',
    ]),
    (0x25CD, [
        'CopyCharRow: copy one 8-line character row between adjacent',
        'window rows (LDIR per line, H/D advanced within the third);',
        'carry selects the source row: +1 (into ScrollDown) or -1.',
    ]),
    (0x25F8, [
        'CopyAttrRow: the attribute-row twin of CopyCharRow - one LDIR',
        'of the window width, source row selected by carry.',
    ]),
    (0x2618, [
        'ScrollDown: reverse scroll - rows shift away from row 0 (the',
        'helpers are called with carry set), the vacated top row is',
        'blanked from column 0.  Used by the disassembly scroll-back',
        '(the caller sits just before ArmWatchpoint).',
    ]),
    (0x2658, [
        'FillWindow: blank every row of the window (FillRowToEnd per',
        'row, attributes from the descriptor), home the cursor to row 0',
        'and restart the blink timer ($24E1).',
    ]),
    (0x2677, [
        'FillWholeRow: save the cursor cell, park X at 0 and fall into',
        'FillRowToEnd - i.e. blank the entire current row.  The scroll',
        'routines enter at $267E (one instruction further) to keep the',
        'cursor flag untouched.',
    ]),
    (0x26AA, [
        'PrinterPutChar: buffer a character for the printer/parallel',
        'port (buffer pointer at E2D9).',
    ]),
    (0x26B3, [
        'PopAllRet: pop every register and return - the standard exit',
        'of window handlers.',
    ]),
    (0x26B7, [
        'PrintCharBit7: print A with bit 7 stripped (terminator-safe).',
    ]),
    (0x26BC, [
        'PrintSpace.',
    ]),
    (0x26BE, [
        'PrintChar - the RST 10h backend and the single character',
        'sink of the monitor; everything funnels into',
        'DispatchOutput next.',
    ]),
    (0x26C4, [
        'DispatchOutput: the output switchboard - DFE8 bits 4/5/6',
        'route each character to tape ($084D), printer or the screen',
        'window; installed print hooks watch the stream as well.',
    ]),
    (0x270F, [
        'InstallPrintHook: park a user routine at the E2D6 vector;',
        'every printed character passes through it.',
    ]),
    (0x2717, [
        'WindowNewline: advance to the next row (scroll at the bottom',
        'edge).',
    ]),
    (0x2746, [
        'WindowHome: cursor to row/column 0 of the current window.',
    ]),
    (0x2751, [
        'KeyClick: brief speaker toggle (OUT $FE, bit 4 XOR) per',
        'keypress.',
    ]),
    (0x2846, [
        'FillMemoryRange: fill through the E600 pointer with a',
        'pattern.',
    ]),
    (0x2859, [
        'ChecksumLoop: running sum over a range - also used to',
        'calibrate AY timing.',
    ]),
    (0x295E, [
        'PrintOkError: "Ok" or the pending error after a command.',
    ]),
    (0x296D, [
        'LookupCommand: walk CommandTable (E80B, 2-byte entries)',
        'matching the entered verb.',
    ]),
    (0x297F, [
        'CheckWatchpoints: after every step compare the 8 entries of',
        'WatchTable (E394, 11 bytes each: address, length, value...)',
        'against the visible banks; a hit re-enters the monitor.',
    ]),
    (0x29C9, [
        'InitWatchTable: clear the watchpoint table.',
    ]),
    (0x29E8, [
        'FindWatchpoint: locate a free/owning slot in WatchTable.',
    ]),
    (0x2B5F, [
        'OpenPopup: pop up a window from the descriptor at',
        'PopupWindowDef (E06D).',
    ]),
    (0x2B6B, [
        'TapeMenu: the tape command cluster - save/verify/leader',
        'state machine; control flow is dense here (cf. SaveToTape',
        '$358D and the key waits at $2F3E+).',
    ]),
    (0x2C6C, [
        'SearchPattern: wildcard search across banks through the',
        'bank window.',
    ]),
    (0x2D80, [
        'SavePagingShadow / RestorePagingShadow ($2D8C): stash the',
        'real paging (DFDD) into the DFD9/DFDB shadows while the',
        'monitor reprograms banks.',
    ]),
    (0x2E23, [
        'CmdInterruptState: the EI/DI command - toggles the saved',
        'user IFF (DD83 bit 2) that the step trampoline applies as',
        'its DI/EI prefix.',
    ]),
    (0x2E7E, [
        'ScreenBankCheck: is the visible screen the bank being',
        'edited? (shadow-screen test).',
    ]),
    (0x2E91, [
        'CalcPagingPorts: bank number in HL -> the #7FFD/#1FFD byte',
        'pair (bank bits, RAM-at-$C000 bit, TR-DOS session bits),',
        'respecting the paging mirror.',
    ]),
    (0x2ED0, [
        'CheckAddressRange: validate a command address range (carry',
        'on error, message via ReportError).',
    ]),
    (0x2F99, [
        'DecodeXorTable: XOR-unmask a ROM table into RAM using the',
        'keys at XorDecodeKeys ($00FC).',
    ]),
    (0x2FBF, [
        'RunCommand: walk the command table, execute the matching',
        'entry (jp (HL) per entry), wait for a key, return to the',
        'main loop.',
    ]),
    (0x2FFD, [
        'BreakpointSlot: address of breakpoint slot A (DD8D-based',
        'table).',
    ]),
    (0x3025, [
        'AddBreakpoint: program a slot - address plus the original',
        'bytes saved for clean removal.',
    ]),
    (0x3055, [
        'ListBreakpoints: the breakpoint list window.',
    ]),
    (0x3105, [
        'ArmWatchpoint: activate a watch entry (address / length /',
        'value).',
    ]),
    (0x3474, [
        'ReadNmiPort: read the Scorpion NMI status port #FFDD (magic',
        'button state; v4.01 relocates it to #FFDC).',
    ]),
    (0x347D, [
        'PrintFrameCount: display the frame counters at DFD2/DFD4.',
    ]),
    (0x34A8, [
        'LookupToken: resolve a token against the RAM table at',
        '$FFC8.',
    ]),
    (0x3557, [
        'CallTrdos - enter a TR-DOS session: #1FFD=$02, #7FFD=$17,',
        'LDIR 6912 bytes $C000 -> $4000 (DOS screen into place),',
        'then restore #7FFD=$10 / #1FFD=$12 on return.',
    ]),
    (0x3584, [
        'RestorePaging: DFDB shadow -> DFDD paging mirror, ports',
        'refreshed.',
    ]),
    (0x358D, [
        'SaveToTape: header + data bytes to tape through',
        'FeedTapeOutput; leader and parity via the $2F3E+ waits.',
    ]),
    (0x35CB, [
        'InitErrorWindow: open the service window stack and install',
        'the error hook below so RST 08 lands in a visible window.',
    ]),
    (0x35F4, [
        'ErrorWindowHook: the (DE12)-vectored handler printing',
        'errors into the popup window.',
    ]),
]

# --- data-block documentation (see also the .blocks file) ---
# These live at addresses specific to the base ROM layout; the 2.95 and
# 4.01 dicts document their own data blocks instead of relocating these
# (DATA_ADDRS below lets the child dicts skip them during inheritance).
DATA_COMMENTS = [
    (0x0013, [
        'Filler0013: unused padding between the RST',
        'vector stubs of the vector page ($0008-$0056).',
        'The bytes read nop nop jp $00B6 but no path',
        'enters them.',
    ]),
    (0x001B, [
        'Filler001B: three nop bytes of vector-page',
        'padding between the RST 18 and RST 20 stubs.',
    ]),
    (0x0023, [
        'Filler0023: vector-page padding (nop nop nop',
        'jr $0066); never executed.',
    ]),
    (0x002D, [
        'Filler002D: dead jp $00B6 left between the',
        'RST 20 and RST 30 stubs.',
    ]),
    (0x0033, [
        'Filler0033: padding after the RST 30 stub',
        '(nop nop jp $00B6), unreachable.',
    ]),
    (0x0053, [
        'Filler0053: stray instruction bytes (a',
        'ld hl,(dFF3h)) closing the vector page;',
        'nothing references them.',
    ]),
    (0x00F1, [
        'Filler00F1: unreferenced junk immediately',
        'before the XOR key table at $00FC.',
    ]),
    (0x0E8D, [
        'KeyScanTableA: first key-translate table of',
        'the editor - internal key codes in scan',
        'order, consumed by the loop that ends at',
        '$0E8B; continues in KeyScanTableB ($0EA5).',
    ]),
    (0x0EA5, [
        'KeyScanTableB: second key-translate table,',
        'loaded as BC by the command editor ($0AAD);',
        'the final $22 byte acts as a sentinel.',
    ]),
    (0x0ED4, [
        'RegisterNameStrings: pool of short register-name',
        'strings, the last character of each carrying',
        "bit 7 ('I','I','H','D','B','AF','A','IX','IX',",
        "'IY','IY','P','S','HL','DE','BC' plus single",
        'letters); indexed by the register display and',
        'editor. See also the inline-string printer at',
        'RegisterNameTable ($1531).',
    ]),
    (0x13F3, [
        'RegHeaderLine: header row of the register window',
        "('IR  SZ-H-PNC  INT RAM ROM SCR  ZX' with",
        'embedded control bytes for the column gaps);',
        'printed above the dump by ShowRegisters ($14AB).',
    ]),
    (0x1C4A, [
        'AnalyzeDataPool: four scratch bytes followed by',
        "the 'BAD' text ($F0-terminated) shown for invalid",
        'opcodes; HL is aimed here by AnalyzeInstruction',
        '($1C30) and the walker at $1C52 is called from',
        '$16BE.',
    ]),
    (0x2962, [
        'MsgOff: inline RST 20h string OF+$C6 which prints',
        'OFF - the terminating byte is emitted with bit 7',
        'stripped; used by the watch/breakpoint listing',
        'routine above ($295E).',
    ]),
    (0x2968, [
        'MsgOn: ON+$A0, printing ON - companion of MsgOff',
        '($2962).',
    ]),
    (0x2B5A, [
        'PopupTabStops: four tab columns (0,2,4,6) closed',
        'by the $81 sentinel; the loop at $2B4A feeds each',
        'value to the print helper at $18E9 to lay out the',
        'popup menu line right before OpenPopup ($2B5F).',
    ]),
    (0x2B86, [
        'MsgBase: popup-menu item base led by a carriage',
        'return byte; the $A0 terminator prints as a',
        'trailing space.',
    ]),
    (0x2BA3, [
        'MsgOption: popup-menu item option (CR-prefixed,',
        '$A0-terminated).',
    ]),
    (0x2BB2, [
        'MsgIntMode: popup-menu item Int mode (CR-prefixed);',
        'the choice drives the im0/im1/im2 dispatcher at',
        '$3671.',
    ]),
    (0x2BCF, [
        'MsgTapeTurbo: (t+$A9, printing (t) - appended to',
        'the tape line when turbo mode is selected.',
    ]),
    (0x3489, [
        'MsgTotal: Total label of the frame-counter',
        'readout (PrintFrameCount).',
    ]),
    (0x3498, [
        'MsgGold: / Gold - second frame-counter label.',
    ]),
    (0x35FC, [
        'MenuBuilder: popup-menu code of the ROM tail. It',
        'calls OpenPopup ($2B5F), then prints the five',
        'entries of KeywordTable ($3746) with helper',
        'strings indexed at ErrorShortStrings+3*i+2',
        '($3CEC). The option loop ends in the interrupt-',
        'mode dispatcher: a 3-bytes-per-entry jump table',
        'at $3671 (im 0 / im 1 / im 2 / invalid) entered',
        'through jp (hl) at $3670. The final routine',
        '($367D) copies ten (dest,word) pairs from',
        'RamInitTable ($3F69) into the workspace.',
    ]),
    (0x3690, [
        'EncodedTable3690: XOR-masked ROM table, unmasked',
        'at boot into $E2DB by the second DecodeXorTable',
        'call ($05BB); keys at XorDecodeKeys ($00FC).',
    ]),
    (0x3746, [
        'KeywordTable: menu/command keyword strings',
        "('PC','BAS','BREa','BR','CAL','CATalog',...); the",
        'final character of each entry carries bit 7,',
        'and the menu loop at $3606 stops at a $00 byte.',
    ]),
    (0x3818, [
        'ErrorBitMap: error-class bit map (the',
        'ErrorTextTable2 pointer installed by',
        'SetErrorTables, $116A); one flag per report',
        'number.',
    ]),
    (0x3820, [
        'WordLists: packed word lists for the token',
        "recogniser - menu words ('main','menu',",
        "'previous',...), interface words ('speed',",
        "'RS232','9600',...) and the long error words",
        "('abandoned','breakpoint',...).",
    ]),
    (0x3B7F, [
        'ErrorShortStrings: dense pool of 2-4 character',
        'strings (the ErrorTextTable base) - error',
        'fragments, month names and menu decorations,',
        'reached by the menu builder via $3CEC+3*i+2.',
    ]),
    (0x3E45, [
        'EncodedTable3E45: second XOR-masked region,',
        'unmasked at boot into DecodedTables ($E82D) by',
        'DecodeTables ($05A2) using the keys at $00FC.',
    ]),
    (0x3F69, [
        'RamInitTable: ten (dest,word) pairs written into',
        'workspace/screen RAM by the walker at $367D -',
        'window defaults at $DFFA-$DFFE, further cells',
        'at $E0AC-$E0B4 and two tags at $C063/$C064.',
    ]),
    (0x3F91, [
        "ZeroPad3F91: two orphan one-character strings",
        "('c'+$80, 'd'+$80) and zero padding up to the",
        'end of the 16 KiB page.',
    ]),
    (0x10B6, [
        'Msg10B6: separator line of nine < characters',
        '(bit-7 terminator).',
    ]),
    (0x31B9, [
        'Msg31B9: disk-catalog message File.',
    ]),
    (0x31CC, [
        'Msg31CC: disk-catalog message , free.',
    ]),
    (0x3254, [
        'Msg3254: message More... (listing pager).',
    ]),
    (0x3307, [
        'Msg3307: message Formating. (disk format).',
    ]),
    (0x3386, [
        'Msg3386: message Checking.  (disk verify).',
    ]),
    (0x3455, [
        'Msg3455: message Complete.',
    ]),
    (0x34F3, [
        'Msg34F3: message Insert disk, press Y key.',
    ]),
]

COMMENTS += DATA_COMMENTS
DATA_ADDRS = frozenset(a for a, _ in DATA_COMMENTS)
