#!/usr/bin/env python3
"""Generate core/src/emulator/io/z80n/nextregtable.inc from the distribution's registers.txt
(documents/nextzxos-distribution-docs/extra-hw/io-port-system/registers.txt, "The Next Registers" v2.4).

Usage: gen-nextreg-table.py <registers.txt> <out.inc>

One row per register number: {number, "name", readable, writable, hasReset, reset}. A reset value is taken when the
register's text gives one for the whole byte ("(hard reset = 0)", "(soft reset = 0xe3)" on the access line or on a
"bits 7:0" line); registers whose reset is per bit stay without one (the device behind them sets it). Registers listed
twice (the 0x75-0x79 aliases) keep the first row. Multi-register headers ("0x85,0x84,0x83,0x82 (133-130)") expand.
"""
import re
import sys

HEADER = re.compile(r'^(0x[0-9A-Fa-f]{2}(?:,0x[0-9A-Fa-f]{2})*)\s*(?:\([^)]*\))?\s*=>\s*(.*)$')
RESET = re.compile(r'(?:hard |soft )?reset\s*=\s*(0x[0-9A-Fa-f]+|\d+|[01]{4,8}(?:\s[01]{4})?b?)', re.I)


def value(text):
    text = text.strip().rstrip('b')
    if text.startswith('0x'):
        return int(text, 16)
    if re.fullmatch(r'[01 ]{4,9}', text) and len(text.replace(' ', '')) >= 4 and set(text) <= set('01 '):
        return int(text.replace(' ', ''), 2)
    return int(text)


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    lines = open(sys.argv[1], encoding='latin-1').read().splitlines()
    blocks = []
    for i, line in enumerate(lines):
        m = HEADER.match(line)
        if m:
            blocks.append((i, m.group(1), m.group(2).strip()))
    rows = {}
    for n, (start, regs, name) in enumerate(blocks):
        end = blocks[n + 1][0] if n + 1 < len(blocks) else len(lines)
        body = lines[start + 1:end]
        access = ''.join(re.match(r'^\((R|W|R/W)\)', l.strip()).group(0) for l in body if re.match(r'^\((R|W|R/W)\)', l.strip())).upper()
        readable = 'R' in access
        writable = 'W' in access
        reset = None
        mentions = []
        for l in body:
            s = l.strip()
            m = RESET.search(s)
            if m:
                mentions.append((s, m.group(1)))
        # the whole byte: on the access line, a "bits N:0" field reaching bit 0 from the top, or the only mention
        for s, v in mentions:
            if re.match(r'^\((R|W|R/W)\)', s) or re.match(r'^bits 7[:-]0\b', s):
                try:
                    reset = value(v)
                except ValueError:
                    pass
                break
        if reset is None and len(mentions) == 1 and re.match(r'^bits [0-7][:-]0\b', mentions[0][0]):
            try:
                reset = value(mentions[0][1])
            except ValueError:
                pass
        for r in regs.split(','):
            number = int(r, 16)
            rows.setdefault(number, (number, name, readable, writable, reset))
    for number, row in list(rows.items()):
        if row[4] is not None and row[4] > 0xFF:
            rows[number] = row[:4] + (None,)
    # the port decoding enable words (0x82-0x89): all ones after reset, readable and writable
    for number in range(0x82, 0x8A):
        rows[number] = (number, 'Port Decoding Enables ' + ('internal' if number < 0x86 else 'expansion bus'), True, True, 0xFF)
    out = ['// Generated by tools/machines/next/fpga-extract/gen-nextreg-table.py from registers.txt; do not edit.\n']
    for number in sorted(rows):
        _, name, r, w, reset = rows[number]
        name = name.replace('\\', '\\\\').replace('"', '\\"')
        out.append('{0x%02X, "%s", %s, %s, %s, 0x%02X},\n' % (number, name, 'true' if r else 'false', 'true' if w else 'false',
                                                          'true' if reset is not None else 'false', reset or 0))
    open(sys.argv[2], 'w').write(''.join(out))
    print(len(rows), 'registers')


main()
