"""Markdown report generator for a parsed .ttd dump.

Produces a self-contained summary of the recording: header metadata,
integrity findings, anomaly findings, and a per-checkpoint table with the
fields that matter most for triaging "Play → reset" and "no seek refresh"
bugs.

The output is plain markdown — renderable by GitHub, any editor, or
``glow``/``mdcat`` in a terminal.
"""

from __future__ import annotations

import datetime as _dt
from dataclasses import dataclass, field
from typing import List, Optional

from .anomaly_detector import AnomalyReport, detect_anomalies
from .integrity_check import IntegrityReport, check_integrity
from .ttd_format import NEVER_TOUCHED_PAGE_REF, TtdDump

# Spectrum model ID table — must mirror eModelIds in the engine.
# Unknown IDs render as a generic label so the report stays useful when
# new models land without an analyzer update.
_MODEL_NAMES = {
    0: "Spectrum 48K",
    1: "Spectrum 128K",
    2: "Pentagon 128K",
    3: "Pentagon 512K",
    4: "Pentagon 1024",
    5: "Scorpion 256",
    6: "Scorpion 1024",
    7: "Profiman 7.1 (Profi)",
    8: "Kay 1024",
    9: "ATM 1",
    10: "ATM 2",
    11: "ATM 3",
    12: "TS-Conf",
    13: "Spectrum +2",
    14: "Spectrum +2A",
    15: "Spectrum +3",
    16: "Quorum 512",
    17: "GMX",
    18: "LSY 256",
}


def _model_name(model_id: int) -> str:
    return _MODEL_NAMES.get(model_id, f"Unknown model id {model_id}")


def _format_unix_ms(ms: int) -> str:
    if ms == 0:
        return "—"
    try:
        return _dt.datetime.fromtimestamp(ms / 1000.0, tz=_dt.timezone.utc).isoformat()
    except (OverflowError, OSError, ValueError):
        return f"<invalid timestamp {ms}>"


def _format_t_states(t: int) -> str:
    """Pretty-print a T-states counter with K/M suffixes."""
    if t < 1000:
        return str(t)
    if t < 1_000_000:
        return f"{t / 1000:.2f}K"
    return f"{t / 1_000_000:.2f}M"


@dataclass
class ReportOptions:
    """Knobs that control report content (for batch automation)."""

    include_checkpoint_table: bool = True
    checkpoint_table_limit: int = 50  # truncate table for huge sessions
    include_anomaly_details: bool = True
    include_integrity_details: bool = True


def generate_markdown_report(
    dump: TtdDump,
    integrity: Optional[IntegrityReport] = None,
    anomalies: Optional[AnomalyReport] = None,
    opts: Optional[ReportOptions] = None,
) -> str:
    """Build the markdown report. ``integrity`` and ``anomalies`` are
    computed from ``dump`` if not provided, so callers can pass cached
    results when batch-processing many files."""
    if opts is None:
        opts = ReportOptions()
    if integrity is None:
        integrity = check_integrity(dump)
    if anomalies is None:
        anomalies = detect_anomalies(dump)

    h = dump.header
    lines: List[str] = []

    # ---- Title ----
    lines.append(f"# TTD recording report")
    lines.append("")
    lines.append(
        f"_Generated by `ttd-analyzer` for {_model_name(h.model_id)} "
        f"({h.model_ram_pages} RAM pages × 16 KB)._"
    )
    lines.append("")

    # ---- Header summary ----
    lines.append("## Header")
    lines.append("")
    lines.append("| Field | Value |")
    lines.append("|---|---|")
    lines.append(f"| Schema version | {h.schema_version} |")
    lines.append(f"| Flags | `0x{h.flags:04X}` "
                 f"({'little-endian' if h.flags & 0x0001 else 'big-endian'}) |")
    lines.append(f"| Model | {_model_name(h.model_id)} (id={h.model_id}) |")
    lines.append(f"| RAM pages | {h.model_ram_pages} "
                 f"({h.model_ram_pages * 16} KB) |")
    lines.append(f"| CPU state size | {h.cpu_state_size} bytes |")
    lines.append(f"| Chipset state size | {h.chipset_state_size} bytes |")
    lines.append(f"| Captured at | {_format_unix_ms(h.captured_at_unix_ms)} |")
    lines.append(f"| Emulator id | `{h.emulator_id or '—'}` |")
    lines.append(f"| Session state | {h.session_state} "
                 f"(0=idle, 1=recording, 2=playing) |")
    lines.append(f"| Session frame range | "
                 f"{h.session_start_frame} … {h.session_end_frame} |")
    lines.append(f"| Page store slots | {h.page_store_count} "
                 f"({h.page_store_count * 16 / 1024:.1f} MB unique RAM content) |")
    lines.append(f"| Checkpoints | {h.checkpoint_count} |")
    lines.append("")

    # ---- Integrity findings ----
    lines.append("## Integrity")
    lines.append("")
    if integrity.ok and not integrity.warnings:
        lines.append("✅ **Pass** — no structural issues found.")
        lines.append("")
    else:
        status = "✅ Pass with warnings" if integrity.ok else "❌ **Fail**"
        lines.append(f"{status} — {len(integrity.errors)} error(s), "
                     f"{len(integrity.warnings)} warning(s).")
        lines.append("")
        if opts.include_integrity_details and integrity.issues:
            lines.append("| Severity | Code | Scope | Message |")
            lines.append("|---|---|---|---|")
            for issue in integrity.issues:
                scope = (f"cp{issue.checkpoint_index}"
                         if issue.checkpoint_index >= 0 else "file-level")
                msg = issue.message.replace("|", "\\|")
                lines.append(f"| {issue.severity} | `{issue.code}` | "
                             f"{scope} | {msg} |")
            lines.append("")

    # ---- Anomaly findings ----
    lines.append("## Anomalies")
    lines.append("")
    if not anomalies.findings:
        lines.append("✅ **None** — no suspicious patterns detected.")
        lines.append("")
    else:
        n_crit = len(anomalies.critical)
        n_warn = len(anomalies.warnings)
        n_info = len(anomalies.findings) - n_crit - n_warn
        lines.append(f"Found **{n_crit} critical**, {n_warn} warning(s), "
                     f"{n_info} info.")
        lines.append("")
        if opts.include_anomaly_details:
            lines.append("| Severity | Category | Code | Checkpoint | Detail |")
            lines.append("|---|---|---|---|---|")
            for f in anomalies.findings:
                cp = f"cp{f.checkpoint_index}" if f.checkpoint_index >= 0 else "—"
                msg = f.message.replace("|", "\\|")
                # Trim very long messages for readability; full detail goes
                # to stdout when running interactively via main.py.
                if len(msg) > 200:
                    msg = msg[:200] + " …"
                lines.append(f"| {f.severity} | {f.category} | `{f.code}` | "
                             f"{cp} | {msg} |")
            lines.append("")

    # ---- Per-checkpoint table ----
    if opts.include_checkpoint_table and dump.checkpoints:
        lines.append("## Timeline")
        lines.append("")
        limit = opts.checkpoint_table_limit
        cps_to_show = dump.checkpoints if len(dump.checkpoints) <= limit \
            else dump.checkpoints[:limit // 2] + [None] + dump.checkpoints[-limit // 2:]
        lines.append("| idx | frame | T-states | PC | SP | halt | iff1 | "
                     "p7FFD | border | screen bank | dirty pages |")
        lines.append("|---|---|---|---|---|---|---|---|---|---|---|")
        for cp in cps_to_show:
            if cp is None:
                lines.append(f"| _… {len(dump.checkpoints) - limit} more …_ |"
                             "||||||||||")
                continue
            dirty = sum(1 for r in cp.ram_page_refs if r != NEVER_TOUCHED_PAGE_REF)
            unique = len(set(r for r in cp.ram_page_refs
                             if r != NEVER_TOUCHED_PAGE_REF))
            screen_bank = 7 if (cp.chipset.p7ffd & 0b0000_1000) else 5
            lines.append(
                f"| {cp.index} | {cp.frame} | {_format_t_states(cp.global_t)} | "
                f"`0x{cp.cpu.pc:04X}` | `0x{cp.cpu.sp:04X}` | "
                f"{cp.cpu.halted} | {cp.cpu.iff1} | "
                f"`0x{cp.chipset.p7ffd:02X}` | {cp.chipset.border_attr} | "
                f"{screen_bank} | {dirty}/{h.model_ram_pages} ({unique} unique) |"
            )
        lines.append("")

    # ---- Triaging hints ----
    lines.append("## Triaging hints")
    lines.append("")
    hints: List[str] = []
    if any(f.code == "sp_at_zero" for f in anomalies.findings):
        hints.append("- **Reset on Play**: at least one checkpoint has SP=0x0000. "
                     "The CPU hit the reset vector mid-session; this is the "
                     "classic 'Play → reset' cause. Inspect the nearest prior "
                     "checkpoint for a bad RST fetch or a stack underflow.")
    if any(f.code == "large_pc_jump" for f in anomalies.findings):
        hints.append("- **Large PC jumps between frames**: the timeline shows "
                     "PC deltas > 32 KB. Either the program is jumping into "
                     "ROM/different bank (expected when entering the editor), "
                     "or capture missed an interrupt return.")
    if any(f.code == "screen_bank_flipped" for f in anomalies.findings):
        hints.append("- **Screen bank flip detected**: p7FFD bit 3 flipped. "
                     "If you see 'no seek refresh' after this point, the "
                     "restore path likely didn't re-latch the ULA bank — "
                     "verify `Screen::SetActiveScreen` was called on restore.")
    if any(f.code == "border_attr_drift" for f in anomalies.findings):
        hints.append("- **Border attr drift**: the cached `border_attr` doesn't "
                     "match the source `pFE` bits. Restore is painting the "
                     "wrong border colour after a seek.")
    if any(i.code == "timeline_not_monotonic" for i in integrity.issues):
        hints.append("- **Non-monotonic timeline**: the timeline is corrupted. "
                     "The engine's binary-search SeekTo would return wrong "
                     "results — this is a writer-side bug, not a restore bug.")
    if not hints:
        hints.append("- No triage hints — no critical/warning patterns matched.")
    lines.extend(hints)
    lines.append("")

    # ---- Format reference ----
    lines.append("## Format reference")
    lines.append("")
    lines.append("This report was produced by the hand-written Python parser in "
                 "`src/ttd_format.py`, which mirrors the canonical Kaitai Struct "
                 "schema at `core/src/debugger/ttd/ttd.ksy` (schema version "
                 f"{h.schema_version}). See the README for the full format spec.")
    lines.append("")

    return "\n".join(lines)
