// poc_codec_latency.cpp — C++ codec comparison for the TTD workload.
//
// This PoC measures candidate codecs (zstd, lz4, brotli, snappy, FastLZ,
// zlib) against the workload shapes that the TTD codec actually hands to
// the compressor: 4 KB sub-pages of XOR-delta bytes (sparse or clustered),
// plus all-zero pages (the ZeroPayload short-circuit case), plus baseline
// random 4 KB pages for reference.
//
// Methodology:
//   - Each codec x workload pair is registered as a Google Benchmark
//     BENCHMARK_CAPTURE.
//   - Per iteration, the benchmark encodes every buffer in the workload
//     once and decodes it once, timing each encode/decode call with
//     std::chrono::steady_clock.
//   - p50/p95/p99 latency, throughput (MB/s), and ratio (encoded/raw)
//     are reported as UserCounters.

#include <benchmark/benchmark.h>

#include <algorithm>
#include <array>
#include <chrono>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <functional>
#include <random>
#include <string>
#include <vector>

#include "codec_config.h"  // auto-generated by CMake

#include <zstd.h>
#include <fastlz.h>

#ifdef LZ4_FOUND
#  include <lz4.h>
#  include <lz4hc.h>
#endif

#ifdef SNAPPY_FOUND
#  include <snappy.h>
#endif

#ifdef BROTLI_FOUND
#  include <brotli/encode.h>
#  include <brotli/decode.h>
#endif

#ifdef ZLIB_FOUND
#  include <zlib.h>
#endif

namespace {

constexpr size_t kSubPageSize = 4096;
constexpr size_t kWorkloadBuffers = 1000;

// ---------------------------------------------------------------------------
// Codec adapter
// ---------------------------------------------------------------------------
struct Codec {
    std::string name;
    std::function<size_t(const uint8_t*, size_t, uint8_t*, size_t)> encode;
    std::function<size_t(const uint8_t*, size_t, uint8_t*, size_t)> decode;
    std::function<size_t(size_t)> bound;
};

// ---------------------------------------------------------------------------
// Codec factories
// ---------------------------------------------------------------------------
Codec make_zstd(int level) {
    ZSTD_CCtx* cctx = ZSTD_createCCtx();
    ZSTD_DCtx* dctx = ZSTD_createDCtx();
    ZSTD_CCtx_setParameter(cctx, ZSTD_c_compressionLevel, level);

    Codec c;
    c.name = "zstd" + (level < 0 ? "n" + std::to_string(-level) : std::to_string(level));
    c.encode = [cctx](const uint8_t* s, size_t n, uint8_t* d, size_t cap) -> size_t {
        size_t r = ZSTD_compressCCtx(cctx, d, cap, s, n, 0);
        return ZSTD_isError(r) ? 0 : r;
    };
    c.decode = [dctx](const uint8_t* s, size_t n, uint8_t* d, size_t cap) -> size_t {
        size_t r = ZSTD_decompressDCtx(dctx, d, cap, s, n);
        return ZSTD_isError(r) ? 0 : r;
    };
    c.bound = [](size_t n) { return ZSTD_compressBound(n); };
    return c;
}

#ifdef LZ4_FOUND
Codec make_lz4_fast() {
    Codec c;
    c.name = "lz4-fast";
    c.encode = [](const uint8_t* s, size_t n, uint8_t* d, size_t cap) -> size_t {
        int r = LZ4_compress_default(reinterpret_cast<const char*>(s),
                                      reinterpret_cast<char*>(d),
                                      static_cast<int>(n), static_cast<int>(cap));
        return r > 0 ? static_cast<size_t>(r) : 0;
    };
    c.decode = [](const uint8_t* s, size_t n, uint8_t* d, size_t cap) -> size_t {
        int r = LZ4_decompress_safe(reinterpret_cast<const char*>(s),
                                     reinterpret_cast<char*>(d),
                                     static_cast<int>(n), static_cast<int>(cap));
        return r > 0 ? static_cast<size_t>(r) : 0;
    };
    c.bound = [](size_t n) { return static_cast<size_t>(LZ4_compressBound(static_cast<int>(n))); };
    return c;
}

Codec make_lz4_hc(int level) {
    Codec c;
    c.name = "lz4hc-" + std::to_string(level);
    c.encode = [level](const uint8_t* s, size_t n, uint8_t* d, size_t cap) -> size_t {
        int r = LZ4_compress_HC(reinterpret_cast<const char*>(s),
                                 reinterpret_cast<char*>(d),
                                 static_cast<int>(n), static_cast<int>(cap), level);
        return r > 0 ? static_cast<size_t>(r) : 0;
    };
    c.decode = [](const uint8_t* s, size_t n, uint8_t* d, size_t cap) -> size_t {
        int r = LZ4_decompress_safe(reinterpret_cast<const char*>(s),
                                     reinterpret_cast<char*>(d),
                                     static_cast<int>(n), static_cast<int>(cap));
        return r > 0 ? static_cast<size_t>(r) : 0;
    };
    c.bound = [](size_t n) { return static_cast<size_t>(LZ4_compressBound(static_cast<int>(n))); };
    return c;
}
#endif

#ifdef SNAPPY_FOUND
Codec make_snappy() {
    Codec c;
    c.name = "snappy";
    c.encode = [](const uint8_t* s, size_t n, uint8_t* d, size_t /*cap*/) -> size_t {
        size_t out_n = 0;
        snappy::RawCompress(reinterpret_cast<const char*>(s), n,
                            reinterpret_cast<char*>(d), &out_n);
        return out_n;
    };
    c.decode = [](const uint8_t* s, size_t n, uint8_t* d, size_t /*cap*/) -> size_t {
        size_t out_n = 0;
        if (!snappy::GetUncompressedLength(reinterpret_cast<const char*>(s), n, &out_n)) return 0;
        if (!snappy::RawUncompress(reinterpret_cast<const char*>(s), n,
                                    reinterpret_cast<char*>(d))) return 0;
        return out_n;
    };
    c.bound = [](size_t n) { return snappy::MaxCompressedLength(n); };
    return c;
}
#endif

#ifdef BROTLI_FOUND
Codec make_brotli(int level) {
    Codec c;
    c.name = "brotli-" + std::to_string(level);
    c.encode = [level](const uint8_t* s, size_t n, uint8_t* d, size_t cap) -> size_t {
        size_t out_n = cap;
        if (BROTLI_TRUE != BrotliEncoderCompress(
                level, BROTLI_DEFAULT_WINDOW, BROTLI_DEFAULT_MODE,
                n, s, &out_n, d)) return 0;
        return out_n;
    };
    c.decode = [](const uint8_t* s, size_t n, uint8_t* d, size_t cap) -> size_t {
        size_t out_n = cap;
        if (BROTLI_DECODER_RESULT_SUCCESS != BrotliDecoderDecompress(
                n, s, &out_n, d)) return 0;
        return out_n;
    };
    c.bound = [](size_t n) { return n + (n >> 1) + 64; };
    return c;
}
#endif

Codec make_fastlz(int level) {
    Codec c;
    c.name = "fastlz-" + std::to_string(level);
    c.encode = [level](const uint8_t* s, size_t n, uint8_t* d, size_t cap) -> size_t {
        int r = fastlz_compress_level(level, s, static_cast<int>(n), d);
        return (r > 0 && static_cast<size_t>(r) <= cap) ? static_cast<size_t>(r) : 0;
    };
    c.decode = [](const uint8_t* s, size_t n, uint8_t* d, size_t cap) -> size_t {
        int r = fastlz_decompress(s, static_cast<int>(n), d, static_cast<int>(cap));
        return r > 0 ? static_cast<size_t>(r) : 0;
    };
    c.bound = [](size_t n) { return n + n / 100 + 8; };
    return c;
}

#ifdef ZLIB_FOUND
Codec make_zlib(int level) {
    Codec c;
    c.name = "zlib-" + std::to_string(level);
    c.encode = [level](const uint8_t* s, size_t n, uint8_t* d, size_t cap) -> size_t {
        uLongf out_n = cap;
        if (Z_OK != compress2(d, &out_n, s, static_cast<uLong>(n), level)) return 0;
        return out_n;
    };
    c.decode = [](const uint8_t* s, size_t n, uint8_t* d, size_t cap) -> size_t {
        uLongf out_n = cap;
        if (Z_OK != uncompress(d, &out_n, s, static_cast<uLong>(n))) return 0;
        return out_n;
    };
    c.bound = [](size_t n) { return compressBound(static_cast<uLong>(n)); };
    return c;
}
#endif

// ---------------------------------------------------------------------------
// Codec list (built once)
// ---------------------------------------------------------------------------
std::vector<Codec> build_codec_list() {
    std::vector<Codec> codecs;
    // zstd: negative levels (ultra-fast), 0, 1 (production), 3, 9, 19 (max).
    codecs.push_back(make_zstd(-5));
    codecs.push_back(make_zstd(-3));
    codecs.push_back(make_zstd(-1));
    codecs.push_back(make_zstd(0));
    codecs.push_back(make_zstd(1));
    codecs.push_back(make_zstd(3));
    codecs.push_back(make_zstd(9));
    codecs.push_back(make_zstd(19));
#ifdef LZ4_FOUND
    codecs.push_back(make_lz4_fast());
    codecs.push_back(make_lz4_hc(9));
    codecs.push_back(make_lz4_hc(12));
#endif
#ifdef SNAPPY_FOUND
    codecs.push_back(make_snappy());
#endif
#ifdef BROTLI_FOUND
    codecs.push_back(make_brotli(0));
    codecs.push_back(make_brotli(1));
    codecs.push_back(make_brotli(6));
    codecs.push_back(make_brotli(11));
#endif
    codecs.push_back(make_fastlz(1));
    codecs.push_back(make_fastlz(2));
#ifdef ZLIB_FOUND
    codecs.push_back(make_zlib(1));
    codecs.push_back(make_zlib(6));
    codecs.push_back(make_zlib(9));
#endif
    return codecs;
}

// ---------------------------------------------------------------------------
// Workload generators
// ---------------------------------------------------------------------------
struct Workload {
    std::string name;
    std::string description;
    std::vector<std::vector<uint8_t>> buffers;
};

static std::mt19937_64 g_rng(0xC0DEC0DEULL);

std::vector<uint8_t> make_random_4k() {
    std::vector<uint8_t> b(kSubPageSize);
    std::uniform_int_distribution<int> d(0, 255);
    for (size_t i = 0; i < kSubPageSize; ++i) b[i] = static_cast<uint8_t>(d(g_rng));
    return b;
}

std::vector<uint8_t> make_zero_4k() {
    return std::vector<uint8_t>(kSubPageSize, 0);
}

// A "XOR-delta" buffer represents what TTD's InternXor() actually hands
// to the compressor: it's `new_page XOR prev_page`, where prev_page and
// new_page are 95% identical. The XOR result is therefore 95% ZEROS
// (where the two pages matched) with 5% non-zero bytes at the dirty
// positions. THIS is the buffer the compressor sees.
//
// The baseline parameter is unused — kept in the signature only so the
// function can sit next to the other generators in the file.
std::vector<uint8_t> make_xor_sparse_5pct(const std::vector<uint8_t>& /*baseline*/) {
    std::vector<uint8_t> b(kSubPageSize, 0);  // start all-zero
    std::uniform_int_distribution<size_t> idx(0, kSubPageSize - 1);
    std::uniform_int_distribution<int> val(1, 255);  // avoid 0 (would be "no change")
    size_t dirty = kSubPageSize / 20;  // 5%
    for (size_t i = 0; i < dirty; ++i) b[idx(g_rng)] = static_cast<uint8_t>(val(g_rng));
    return b;
}

std::vector<uint8_t> make_xor_clustered_5pct(const std::vector<uint8_t>& /*baseline*/) {
    std::vector<uint8_t> b(kSubPageSize, 0);  // start all-zero
    std::uniform_int_distribution<size_t> idx(0, kSubPageSize - 16);
    std::uniform_int_distribution<int> val(1, 255);
    size_t runs = (kSubPageSize / 20) / 16;  // ~13 runs of 16 bytes
    for (size_t r = 0; r < runs; ++r) {
        size_t off = idx(g_rng);
        for (size_t i = 0; i < 16; ++i) b[off + i] = static_cast<uint8_t>(val(g_rng));
    }
    return b;
}

std::vector<Workload> build_workload_list() {
    std::vector<Workload> wls;

    {
        Workload wl; wl.name = "A_4k_full"; wl.description = "random 4 KB";
        wl.buffers.reserve(kWorkloadBuffers);
        for (size_t i = 0; i < kWorkloadBuffers; ++i) wl.buffers.push_back(make_random_4k());
        wls.push_back(std::move(wl));
    }
    {
        Workload wl; wl.name = "C_4k_xor_sparse_5pct"; wl.description = "5% scattered XOR-delta";
        wl.buffers.reserve(kWorkloadBuffers);
        std::vector<uint8_t> base = make_random_4k();
        for (size_t i = 0; i < kWorkloadBuffers; ++i) wl.buffers.push_back(make_xor_sparse_5pct(base));
        wls.push_back(std::move(wl));
    }
    {
        Workload wl; wl.name = "E_4k_xor_clustered_5pct"; wl.description = "5% clustered XOR-delta";
        wl.buffers.reserve(kWorkloadBuffers);
        std::vector<uint8_t> base = make_random_4k();
        for (size_t i = 0; i < kWorkloadBuffers; ++i) wl.buffers.push_back(make_xor_clustered_5pct(base));
        wls.push_back(std::move(wl));
    }
    {
        Workload wl; wl.name = "F_4k_zero"; wl.description = "all-zero 4 KB";
        wl.buffers.reserve(kWorkloadBuffers);
        for (size_t i = 0; i < kWorkloadBuffers; ++i) wl.buffers.push_back(make_zero_4k());
        wls.push_back(std::move(wl));
    }

    return wls;
}

// ---------------------------------------------------------------------------
// Benchmark
// ---------------------------------------------------------------------------
static void BM_CodecWorkload(benchmark::State& state,
                              const Codec& codec,
                              const Workload& wl) {
    size_t max_bound = 0;
    for (const auto& b : wl.buffers) max_bound = std::max(max_bound, codec.bound(b.size()));
    std::vector<uint8_t> comp(max_bound);
    std::vector<uint8_t> decomp(kSubPageSize);

    std::vector<double> enc_lat, dec_lat;
    uint64_t total_in_bytes = 0, total_enc_bytes = 0, total_dec_bytes = 0;
    uint64_t enc_failures = 0, dec_failures = 0;

    for (auto _ : state) {
        enc_lat.clear(); dec_lat.clear();
        total_in_bytes = total_enc_bytes = total_dec_bytes = 0;
        enc_failures = dec_failures = 0;
        enc_lat.reserve(wl.buffers.size());
        dec_lat.reserve(wl.buffers.size());

        for (const auto& b : wl.buffers) {
            auto t0 = std::chrono::steady_clock::now();
            size_t cn = codec.encode(b.data(), b.size(), comp.data(), comp.size());
            auto t1 = std::chrono::steady_clock::now();
            enc_lat.push_back(std::chrono::duration<double, std::nano>(t1 - t0).count());

            if (cn == 0) { ++enc_failures; continue; }
            total_in_bytes  += b.size();
            total_enc_bytes += cn;

            auto t2 = std::chrono::steady_clock::now();
            size_t dn = codec.decode(comp.data(), cn, decomp.data(), decomp.size());
            auto t3 = std::chrono::steady_clock::now();
            dec_lat.push_back(std::chrono::duration<double, std::nano>(t3 - t2).count());

            if (dn == 0) ++dec_failures;
            else total_dec_bytes += dn;
        }
    }

    auto stats = [](std::vector<double>& v) -> std::array<double, 4> {
        if (v.empty()) return {0, 0, 0, 0};
        std::sort(v.begin(), v.end());
        auto pct = [&](double p) {
            size_t idx = static_cast<size_t>(p * (v.size() - 1));
            return v[idx];
        };
        double sum = 0;
        for (double x : v) sum += x;
        return { sum / v.size(), pct(0.50), pct(0.95), pct(0.99) };
    };
    auto es = stats(enc_lat);
    auto ds = stats(dec_lat);

    state.counters["enc_us_mean"] = es[0] / 1000.0;
    state.counters["enc_us_p50"]  = es[1] / 1000.0;
    state.counters["enc_us_p95"]  = es[2] / 1000.0;
    state.counters["enc_us_p99"]  = es[3] / 1000.0;
    state.counters["dec_us_mean"] = ds[0] / 1000.0;
    state.counters["dec_us_p50"]  = ds[1] / 1000.0;
    state.counters["dec_us_p95"]  = ds[2] / 1000.0;
    state.counters["dec_us_p99"]  = ds[3] / 1000.0;

    double total_enc_s = es[0] * enc_lat.size() / 1e9;
    double total_dec_s = ds[0] * dec_lat.size() / 1e9;
    if (total_enc_s > 0)
        state.counters["enc_MBps"] = (total_in_bytes / (1024.0 * 1024.0)) / total_enc_s;
    if (total_dec_s > 0)
        state.counters["dec_MBps"] = (total_dec_bytes / (1024.0 * 1024.0)) / total_dec_s;

    if (total_in_bytes > 0)
        state.counters["BLI"] = static_cast<double>(total_enc_bytes) / total_in_bytes;

    if (enc_failures > 0) state.counters["enc_fail"] = enc_failures;
    if (dec_failures > 0) state.counters["dec_fail"] = dec_failures;
}

// ---------------------------------------------------------------------------
// Register all (codec x workload) combinations.
// ---------------------------------------------------------------------------
void register_benchmarks() {
    static auto codecs = build_codec_list();
    static auto workloads = build_workload_list();

    for (const auto& wl : workloads) {
        for (const auto& c : codecs) {
            std::string name = "BM_" + wl.name + "/" + c.name;
            benchmark::RegisterBenchmark(name.c_str(), BM_CodecWorkload, c, wl)
                ->Unit(benchmark::kMicrosecond)
                ->MinTime(1.0)
                ->UseRealTime();
        }
    }
}

}  // namespace

int main(int argc, char** argv) {
    register_benchmarks();
    benchmark::Initialize(&argc, argv);
    if (benchmark::ReportUnrecognizedArguments(argc, argv)) return 1;
    benchmark::RunSpecifiedBenchmarks();
    benchmark::Shutdown();
    return 0;
}
